@
@ -- FILES --
@

@ CustomerThread.cpp


unsigned char data[0] = {
};

unsigned char bss[0];

_RODATA__ZTSNST6THREAD11_STATE_IMPLIST12_BIND_SIMPLEIFST7_MEM_FNIMN4HIRT13RUNNINGTHREADEFIPNS3_17_NNIESCHEDULQUEUEEPST5MUTEXEEPNS3_14CUSTOMERTHREADES6_S8_EEEE_0000: .ascii "NSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEEE\0"


unsigned char data.rel.ro._ZTINSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEEE[12] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTINSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEEE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0xbe, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0xbc, 0x00, 0x00, 
    /*0010*/ 0x08, 0x00, 0x00, 0x00, 0x02, 0xbf, 0x00, 0x00, 
};

unsigned char data.rel.ro._ZTVNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEEE[20] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTVNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEEE[32] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0xbd, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0x8c, 0x00, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0x8d, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0xab, 0x00, 0x00, 
};

unsigned char bss._ZStL8__ioinit[1];

unsigned char data.rel.ro._ZTIN4hirt14CustomerThreadE[12] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt14CustomerThreadE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0xbe, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0xba, 0x00, 0x00, 
    /*0010*/ 0x08, 0x00, 0x00, 0x00, 0x02, 0xc1, 0x00, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt14CustomerThreadE[52] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0020*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0030*/ 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt14CustomerThreadE[96] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0xbb, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0xb3, 0x00, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0xb4, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0x9c, 0x00, 0x00, 
    /*0020*/ 0x14, 0x00, 0x00, 0x00, 0x02, 0x8f, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00, 0x02, 0xac, 0x00, 0x00, 
    /*0030*/ 0x1c, 0x00, 0x00, 0x00, 0x02, 0x93, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x02, 0x91, 0x00, 0x00, 
    /*0040*/ 0x24, 0x00, 0x00, 0x00, 0x02, 0x95, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00, 0x02, 0x87, 0x00, 0x00, 
    /*0050*/ 0x2c, 0x00, 0x00, 0x00, 0x02, 0x86, 0x00, 0x00, 0x30, 0x00, 0x00, 0x00, 0x02, 0x98, 0x00, 0x00, 
};

_RODATA__ZN4HIRT14CUSTOMERTHREAD10PREPROCESSEV_STR1_4_0000: .ascii "[RUNTIME ERROR] set cpu thread affinity failed!!\0\0\0\0",
_RODATA__ZN4HIRT14CUSTOMERTHREAD10PREPROCESSEV_STR1_4_0034: .ascii "hirt\0"


_RODATA__ZN4HIRT14CUSTOMERTHREAD5STARTEV_STR1_4_0000: .ascii "Customer\0"


_RODATA__ZTSN4HIRT14CUSTOMERTHREADE_0000: .ascii "N4hirt14CustomerThreadE\0",
_RODATA__ZTSN4HIRT14CUSTOMERTHREADE_0018: .ascii ""


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt13RunningThread16canHandleSegTaskEPKNS_7SegTaskE
@ Size: 0x8
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt13RunningThread16canHandleSegTaskEPKNS_7SegTaskE
    /*00000000*/ MOV         R0, #1 
    /*00000004*/ BX          LR 
FUNC_END _ZN4hirt13RunningThread16canHandleSegTaskEPKNS_7SegTaskE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThread25dealSegTimeForUseRateProcEP8timespecS2_
@ Size: 0x4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThread25dealSegTimeForUseRateProcEP8timespecS2_
    /*00000000*/ BX          LR 
FUNC_END _ZN4hirt14CustomerThread25dealSegTimeForUseRateProcEP8timespecS2_


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEED2Ev
@ Size: 0x40
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEED2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0038               @ LDR         R3, [PC, #32]               @ 0x0000000000000038 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_003c               @ LDR         R2, [PC, #28]               @ 0x000000000000003c 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R3, [R3, R2] 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R0] 
    /*0000002c*/ BL          _ZNSt6thread6_StateD2Ev
    /*00000030*/ MOV         R0, R4 
    /*00000034*/ POP         {R4, PC} 
    /*00000038*/ WORD_0038: .word 0x00000014
    /*0000003c*/ WORD_003c: .word 0x00000000
FUNC_END _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEED2Ev


FUNC_BEGIN _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEED1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0038               @ LDR         R3, [PC, #32]               @ 0x0000000000000038 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_003c               @ LDR         R2, [PC, #28]               @ 0x000000000000003c 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R3, [R3, R2] 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R0] 
    /*0000002c*/ BL          _ZNSt6thread6_StateD2Ev
    /*00000030*/ MOV         R0, R4 
    /*00000034*/ POP         {R4, PC} 
    /*00000038*/ WORD_0038: .word 0x00000014
    /*0000003c*/ WORD_003c: .word 0x00000000
FUNC_END _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEED1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEED0Ev
@ Size: 0x4c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEED0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0044               @ LDR         R3, [PC, #44]               @ 0x0000000000000044 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_0048               @ LDR         R2, [PC, #40]               @ 0x0000000000000048 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R3, [R3, R2] 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R0] 
    /*0000002c*/ BL          _ZNSt6thread6_StateD2Ev
    /*00000030*/ MOV         R0, R4 
    /*00000034*/ MOV         R1, #24 
    /*00000038*/ BL          _ZdlPvj
    /*0000003c*/ MOV         R0, R4 
    /*00000040*/ POP         {R4, PC} 
    /*00000044*/ WORD_0044: .word 0x00000020
    /*00000048*/ WORD_0048: .word 0x00000000
FUNC_END _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEED0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThread4stopEv
@ Size: 0x4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThread4stopEv
    _ZN4hirt14CustomerThread4stopEv_x0:
    /*00000000*/ B           _ZN4hirt14CustomerThread4stopEv_x0@ _ZN4hirt13RunningThread4stopEv [R_ARM_JUMP24: +0x0] 
FUNC_END _ZN4hirt14CustomerThread4stopEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThread14getDeviceIndexEv
@ Size: 0x4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThread14getDeviceIndexEv
    _ZN4hirt14CustomerThread14getDeviceIndexEv_x0:
    /*00000000*/ B           _ZN4hirt14CustomerThread14getDeviceIndexEv_x0@ sched_getcpu [R_ARM_JUMP24: +0x0] 
FUNC_END _ZN4hirt14CustomerThread14getDeviceIndexEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThread13waitTaskReadyEv
@ Size: 0x4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThread13waitTaskReadyEv
    _ZN4hirt14CustomerThread13waitTaskReadyEv_x0:
    /*00000000*/ B           _ZN4hirt14CustomerThread13waitTaskReadyEv_x0@ _ZN4hirt11TaskMonitor25waitLockCustomerTaskReadyEv [R_ARM_JUMP24: +0x0] 
FUNC_END _ZN4hirt14CustomerThread13waitTaskReadyEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThread17setLeftSegNumProcEj
@ Size: 0x20
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThread17setLeftSegNumProcEj
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ MOV         R4, R1 
    /*00000014*/ BL          _ZN4hirt11ProcManager11getInstanceEv
    /*00000018*/ STR         R4, [R0, #60]               @ 0x3c 
    /*0000001c*/ POP         {R4, PC} 
FUNC_END _ZN4hirt14CustomerThread17setLeftSegNumProcEj


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE
@ Size: 0xdc
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, [R1, #4] 
    /*00000014*/ MOV         R4, R1 
    /*00000018*/ CMP         R3, #0 
    /*0000001c*/ BNE         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x74
    /*00000020*/ LDR         IP, [R1, #100]              @ 0x64 
    /*00000024*/ CMP         IP, #0 
    /*00000028*/ BEQ         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x5c
    /*0000002c*/ LDR         R3, [R1, #104]              @ 0x68 
    /*00000030*/ LDR         R2, [R3, #80]               @ 0x50 
    /*00000034*/ CMP         R2, #0 
    /*00000038*/ BEQ         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x4c
    /*0000003c*/ B           _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xbc
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x40:
    /*00000040*/ LDR         R0, [R3, #80]               @ 0x50 
    /*00000044*/ CMP         R0, #0 
    /*00000048*/ BNE         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xbc
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x4c:
    /*0000004c*/ ADD         R2, R2, #1 
    /*00000050*/ ADD         R3, R3, #104                @ 0x68 
    /*00000054*/ CMP         R2, IP 
    /*00000058*/ BNE         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x40
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x5c:
    /*0000005c*/ LDR         R3, [R4] 
    /*00000060*/ MOV         R0, R4 
    /*00000064*/ LDR         R3, [R3, #12] 
    /*00000068*/ BLX         R3 
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x6c:
    /*0000006c*/ MOV         R0, #0 
    /*00000070*/ POP         {R4, PC} 
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x74:
    /*00000074*/ CMP         R3, #2 
    /*00000078*/ BNE         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x6c
    /*0000007c*/ LDR         R0, [R1, #96]               @ 0x60 
    /*00000080*/ CMP         R0, #0 
    /*00000084*/ BEQ         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x5c
    /*00000088*/ LDR         R3, [R1, #100]              @ 0x64 
    /*0000008c*/ LDR         R2, [R3, #24] 
    /*00000090*/ CMP         R2, #0 
    /*00000094*/ BEQ         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xa8
    /*00000098*/ B           _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xcc
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x9c:
    /*0000009c*/ LDR         R1, [R3, #24] 
    /*000000a0*/ CMP         R1, #0 
    /*000000a4*/ BNE         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xcc
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xa8:
    /*000000a8*/ ADD         R2, R2, #1 
    /*000000ac*/ ADD         R3, R3, #48                 @ 0x30 
    /*000000b0*/ CMP         R2, R0 
    /*000000b4*/ BNE         _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x9c
    /*000000b8*/ B           _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_x5c
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xbc:
    /*000000bc*/ BL          _ZN4hirt16TaskGroupManager11getInstanceEv
    /*000000c0*/ MOV         R1, R4 
    /*000000c4*/ POP         {R4, LR} 
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xc8:
    /*000000c8*/ B           _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xc8@ _ZN4hirt16TaskGroupManager13computeCpuSegEPNS_10CpuSegTaskE [R_ARM_JUMP24: +0x0] 
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xcc:
    /*000000cc*/ BL          _ZN4hirt16TaskGroupManager11getInstanceEv
    /*000000d0*/ MOV         R1, R4 
    /*000000d4*/ POP         {R4, LR} 
    _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xd8:
    /*000000d8*/ B           _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE_xd8@ _ZN4hirt16TaskGroupManager19computeConnectorSegEPNS_16ConnectorSegTaskE [R_ARM_JUMP24: +0x0] 
FUNC_END _ZN4hirt14CustomerThread13handleSegTaskEPNS_7SegTaskE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThread5startEv
@ Size: 0x160
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThread5startEv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4064]             @ 0xfe0 
    /*00000010*/ LDR         R4, WORD_013c               @ LDR         R4, [PC, #292]              @ 0x000000000000013c 
    /*00000014*/ MOV         R8, #0 
    /*00000018*/ LDR         R2, WORD_0140               @ LDR         R2, [PC, #288]              @ 0x0000000000000140 
    /*0000001c*/ SUB         SP, SP, #8 
    /*00000020*/ ADD         R4, PC, R4 
    /*00000024*/ MOV         R6, R0 
    /*00000028*/ LDR         R3, WORD_0144               @ LDR         R3, [PC, #276]              @ 0x0000000000000144 
    /*0000002c*/ MOV         R0, #4 
    /*00000030*/ LDR         R2, [R4, R2] 
    /*00000034*/ STR         R8, [R2] 
    /*00000038*/ LDR         R7, [R4, R3] 
    /*0000003c*/ MOV         R1, R7 
    /*00000040*/ BL          _ZnwjRKSt9nothrow_t
    /*00000044*/ SUBS        R5, R0, #0 
    /*00000048*/ BEQ         _ZN4hirt14CustomerThread5startEv_xc8
    /*0000004c*/ STR         R8, [R5] 
    /*00000050*/ MOV         R0, #24 
    /*00000054*/ BL          _Znwj
    /*00000058*/ LDR         R2, WORD_0148               @ LDR         R2, [PC, #232]              @ 0x0000000000000148 
    /*0000005c*/ MOV         R3, R0 
    /*00000060*/ LDR         IP, WORD_014c               @ LDR         IP, [PC, #228]              @ 0x000000000000014c 
    /*00000064*/ ADD         R1, SP, #8 
    /*00000068*/ LDR         LR, [R4, R2] 
    /*0000006c*/ MOV         R0, R5 
    /*00000070*/ LDR         R2, WORD_0150               @ LDR         R2, [PC, #216]              @ 0x0000000000000150 
    /*00000074*/ ADD         LR, LR, #8 
    /*00000078*/ STR         LR, [R3] 
    /*0000007c*/ LDR         IP, [R4, IP] 
    /*00000080*/ STR         IP, [R3, #4] 
    /*00000084*/ LDR         IP, [R4, R2] 
    /*00000088*/ LDR         R2, WORD_0154               @ LDR         R2, [PC, #196]              @ 0x0000000000000154 
    /*0000008c*/ STR         IP, [R3, #8] 
    /*00000090*/ STR         R6, [R3, #12] 
    /*00000094*/ LDR         R2, [R4, R2] 
    /*00000098*/ STR         R8, [R3, #20] 
    /*0000009c*/ STR         R2, [R3, #16] 
    /*000000a0*/ LDR         R2, WORD_0158               @ LDR         R2, [PC, #176]              @ 0x0000000000000158 
    /*000000a4*/ STR         R3, [R1, #-4]! 
    /*000000a8*/ LDR         R2, [R4, R2] 
    /*000000ac*/ BL          _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE
    /*000000b0*/ LDR         R0, [SP, #4] 
    /*000000b4*/ CMP         R0, R8 
    /*000000b8*/ BEQ         _ZN4hirt14CustomerThread5startEv_xc8
    /*000000bc*/ LDR         R3, [R0] 
    /*000000c0*/ LDR         R3, [R3, #4] 
    /*000000c4*/ BLX         R3 
    _ZN4hirt14CustomerThread5startEv_xc8:
    /*000000c8*/ LDR         R0, [R6, #4] 
    /*000000cc*/ STR         R5, [R6, #4] 
    /*000000d0*/ CMP         R0, #0 
    /*000000d4*/ BEQ         _ZN4hirt14CustomerThread5startEv_xf0
    /*000000d8*/ LDR         R3, [R0] 
    /*000000dc*/ CMP         R3, #0 
    /*000000e0*/ BNE         _ZN4hirt14CustomerThread5startEv_x10c
    /*000000e4*/ MOV         R1, #4 
    /*000000e8*/ BL          _ZdlPvj
    /*000000ec*/ LDR         R5, [R6, #4] 
    _ZN4hirt14CustomerThread5startEv_xf0:
    /*000000f0*/ LDR         R1, WORD_015c               @ LDR         R1, [PC, #100]              @ 0x000000000000015c 
    /*000000f4*/ LDR         R0, [R5] 
    /*000000f8*/ ADD         R1, PC, R1 
    /*000000fc*/ BL          pthread_setname_np
    /*00000100*/ MOV         R0, #0 
    /*00000104*/ ADD         SP, SP, #8 
    /*00000108*/ POP         {R4, R5, R6, R7, R8, PC} 
    _ZN4hirt14CustomerThread5startEv_x10c:
    /*0000010c*/ BL          _ZSt9terminatev
    /*00000110*/ LDR         R0, [SP, #4] 
    /*00000114*/ CMP         R0, #0 
    /*00000118*/ BEQ         _ZN4hirt14CustomerThread5startEv_x128
    /*0000011c*/ LDR         R3, [R0] 
    /*00000120*/ LDR         R3, [R3, #4] 
    /*00000124*/ BLX         R3 
    _ZN4hirt14CustomerThread5startEv_x128:
    /*00000128*/ MOV         R1, R7 
    /*0000012c*/ MOV         R0, R5 
    /*00000130*/ BL          _ZdlPvRKSt9nothrow_t
    /*00000134*/ BL          __cxa_end_cleanup
    /*00000138*/ B           _ZN4hirt14CustomerThread5startEv_x128
    /*0000013c*/ WORD_013c: .word 0x00000114
    /*00000140*/ WORD_0140: .word 0x00000000
    /*00000144*/ WORD_0144: .word 0x00000000
    /*00000148*/ WORD_0148: .word 0x00000000
    /*0000014c*/ WORD_014c: .word 0x00000000
    /*00000150*/ WORD_0150: .word 0x00000000
    /*00000154*/ WORD_0154: .word 0x00000000
    /*00000158*/ WORD_0158: .word 0x00000000
    /*0000015c*/ WORD_015c: .word 0x0000005c
FUNC_END _ZN4hirt14CustomerThread5startEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt14CustomerThread5startEv
@ Size: 0x1c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEE6_M_runEv
@ Size: 0x38
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEE6_M_runEv
    /*00000000*/ PUSH        {R4, LR} 
    /*00000004*/ LDR         IP, [R0, #20] 
    /*00000008*/ LDR         R3, [R0, #12] 
    /*0000000c*/ LDR         LR, [R0, #16] 
    /*00000010*/ TST         IP, #1 
    /*00000014*/ LDR         R1, [R0, #8] 
    /*00000018*/ LDRNE       R4, [R3, IP, ASR #1] 
    /*0000001c*/ LDR         R2, [R0, #4] 
    /*00000020*/ LDRNE       LR, [R4, LR] 
    /*00000024*/ ADDEQ       R0, R3, IP, ASR #1 
    /*00000028*/ ADDNE       R0, R3, IP, ASR #1 
    /*0000002c*/ MOV         R3, LR 
    /*00000030*/ POP         {R4, LR} 
    /*00000034*/ BX          R3 
FUNC_END _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_14CustomerThreadES6_S8_EEE6_M_runEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThread10preprocessEv
@ Size: 0x64
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThread10preprocessEv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #3960]             @ 0xf78 
    /*00000010*/ SUB         SP, SP, #128                @ 0x80 
    /*00000014*/ ADD         R1, R0, #8 
    /*00000018*/ MOV         R2, #128                    @ 0x80 
    /*0000001c*/ MOV         R0, SP 
    /*00000020*/ BL          memcpy
    /*00000024*/ BL          pthread_self
    /*00000028*/ MOV         R2, SP 
    /*0000002c*/ MOV         R1, #128                    @ 0x80 
    /*00000030*/ BL          pthread_setaffinity_np
    /*00000034*/ CMP         R0, #0 
    /*00000038*/ BEQ         _ZN4hirt14CustomerThread10preprocessEv_x54
    /*0000003c*/ LDR         R2, WORD_005c               @ LDR         R2, [PC, #24]               @ 0x000000000000005c 
    /*00000040*/ MOV         R1, #4 
    /*00000044*/ LDR         R0, WORD_0060               @ LDR         R0, [PC, #20]               @ 0x0000000000000060 
    /*00000048*/ ADD         R2, PC, R2 
    /*0000004c*/ ADD         R0, PC, R0 
    /*00000050*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt14CustomerThread10preprocessEv_x54:
    /*00000054*/ ADD         SP, SP, #128                @ 0x80 
    /*00000058*/ POP         {R4, PC} 
    /*0000005c*/ WORD_005c: .word 0x0000000c
    /*00000060*/ WORD_0060: .word 0x0000000c
FUNC_END _ZN4hirt14CustomerThread10preprocessEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThreadD2Ev
@ Size: 0x60
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThreadD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0058               @ LDR         R3, [PC, #64]               @ 0x0000000000000058 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_005c               @ LDR         R2, [PC, #60]               @ 0x000000000000005c 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R0, [R0, #4] 
    /*00000024*/ LDR         R3, [R3, R2] 
    /*00000028*/ CMP         R0, #0 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ STR         R3, [R4] 
    /*00000034*/ BEQ         _ZN4hirt14CustomerThreadD2Ev_x4c
    /*00000038*/ LDR         R3, [R0] 
    /*0000003c*/ CMP         R3, #0 
    /*00000040*/ BNE         _ZN4hirt14CustomerThreadD2Ev_x54
    /*00000044*/ MOV         R1, #4 
    /*00000048*/ BL          _ZdlPvj
    _ZN4hirt14CustomerThreadD2Ev_x4c:
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ POP         {R4, PC} 
    _ZN4hirt14CustomerThreadD2Ev_x54:
    /*00000054*/ BL          _ZSt9terminatev
    /*00000058*/ WORD_0058: .word 0x00000034
    /*0000005c*/ WORD_005c: .word 0x00000000
FUNC_END _ZN4hirt14CustomerThreadD2Ev


FUNC_BEGIN _ZN4hirt14CustomerThreadD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0058               @ LDR         R3, [PC, #64]               @ 0x0000000000000058 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_005c               @ LDR         R2, [PC, #60]               @ 0x000000000000005c 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R0, [R0, #4] 
    /*00000024*/ LDR         R3, [R3, R2] 
    /*00000028*/ CMP         R0, #0 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ STR         R3, [R4] 
    /*00000034*/ BEQ         _ZN4hirt14CustomerThreadD1Ev_x4c
    /*00000038*/ LDR         R3, [R0] 
    /*0000003c*/ CMP         R3, #0 
    /*00000040*/ BNE         _ZN4hirt14CustomerThreadD1Ev_x54
    /*00000044*/ MOV         R1, #4 
    /*00000048*/ BL          _ZdlPvj
    _ZN4hirt14CustomerThreadD1Ev_x4c:
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ POP         {R4, PC} 
    _ZN4hirt14CustomerThreadD1Ev_x54:
    /*00000054*/ BL          _ZSt9terminatev
    /*00000058*/ WORD_0058: .word 0x00000034
    /*0000005c*/ WORD_005c: .word 0x00000000
FUNC_END _ZN4hirt14CustomerThreadD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThreadD0Ev
@ Size: 0x6c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThreadD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0064               @ LDR         R3, [PC, #76]               @ 0x0000000000000064 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_0068               @ LDR         R2, [PC, #72]               @ 0x0000000000000068 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R0, [R0, #4] 
    /*00000024*/ LDR         R3, [R3, R2] 
    /*00000028*/ CMP         R0, #0 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ STR         R3, [R4] 
    /*00000034*/ BEQ         _ZN4hirt14CustomerThreadD0Ev_x4c
    /*00000038*/ LDR         R3, [R0] 
    /*0000003c*/ CMP         R3, #0 
    /*00000040*/ BNE         _ZN4hirt14CustomerThreadD0Ev_x60
    /*00000044*/ MOV         R1, #4 
    /*00000048*/ BL          _ZdlPvj
    _ZN4hirt14CustomerThreadD0Ev_x4c:
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ MOV         R1, #136                    @ 0x88 
    /*00000054*/ BL          _ZdlPvj
    /*00000058*/ MOV         R0, R4 
    /*0000005c*/ POP         {R4, PC} 
    _ZN4hirt14CustomerThreadD0Ev_x60:
    /*00000060*/ BL          _ZSt9terminatev
    /*00000064*/ WORD_0064: .word 0x00000040
    /*00000068*/ WORD_0068: .word 0x00000000
FUNC_END _ZN4hirt14CustomerThreadD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt14CustomerThread20setCpuThreadAffinityE9cpu_set_t
@ Size: 0x60
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt14CustomerThread20setCpuThreadAffinityE9cpu_set_t
    /*00000000*/ SUB         SP, SP, #16 
    /*00000004*/ MOV         IP, #16384                  @ 0x4000 
    /*00000008*/ PUSH        {R4, LR} 
    /*0000000c*/ SUB         IP, SP, IP 
    /*00000010*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000014*/ ADD         R4, SP, #12 
    /*00000018*/ STM         R4, {R1, R2, R3} 
    /*0000001c*/ BL          pthread_self
    /*00000020*/ MOV         R2, R4 
    /*00000024*/ MOV         R1, #128                    @ 0x80 
    /*00000028*/ BL          pthread_setaffinity_np
    /*0000002c*/ CMP         R0, #0 
    /*00000030*/ BEQ         _ZN4hirt14CustomerThread20setCpuThreadAffinityE9cpu_set_t_x4c
    /*00000034*/ LDR         R2, WORD_0058               @ LDR         R2, [PC, #28]               @ 0x0000000000000058 
    /*00000038*/ MOV         R1, #4 
    /*0000003c*/ LDR         R0, WORD_005c               @ LDR         R0, [PC, #24]               @ 0x000000000000005c 
    /*00000040*/ ADD         R2, PC, R2 
    /*00000044*/ ADD         R0, PC, R0 
    /*00000048*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt14CustomerThread20setCpuThreadAffinityE9cpu_set_t_x4c:
    /*0000004c*/ POP         {R4, LR} 
    /*00000050*/ ADD         SP, SP, #16 
    /*00000054*/ BX          LR 
    /*00000058*/ WORD_0058: .word 0x00000010
    /*0000005c*/ WORD_005c: .word 0x00000010
FUNC_END _ZN4hirt14CustomerThread20setCpuThreadAffinityE9cpu_set_t


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text.startup._GLOBAL__sub_I_CustomerThread.cpp
@ Size: 0x54
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _GLOBAL__sub_I_CustomerThread.cpp
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ LDR         R4, WORD_0044               @ LDR         R4, [PC, #44]               @ 0x0000000000000044 
    /*00000014*/ LDR         R5, WORD_0048               @ LDR         R5, [PC, #44]               @ 0x0000000000000048 
    /*00000018*/ ADD         R4, PC, R4 
    /*0000001c*/ ADD         R5, PC, R5 
    /*00000020*/ MOV         R0, R4 
    /*00000024*/ BL          _ZNSt8ios_base4InitC1Ev
    /*00000028*/ LDR         R3, WORD_004c               @ LDR         R3, [PC, #28]               @ 0x000000000000004c 
    /*0000002c*/ MOV         R0, R4 
    /*00000030*/ LDR         R2, WORD_0050               @ LDR         R2, [PC, #24]               @ 0x0000000000000050 
    /*00000034*/ LDR         R1, [R5, R3] 
    /*00000038*/ ADD         R2, PC, R2 
    /*0000003c*/ POP         {R4, R5, R6, LR} 
    _GLOBAL__sub_I_CustomerThread.cpp_x40:
    /*00000040*/ B           _GLOBAL__sub_I_CustomerThread.cpp_x40@ __aeabi_atexit [R_ARM_JUMP24: +0x0] 
    /*00000044*/ WORD_0044: .word 0x00000024
    /*00000048*/ WORD_0048: .word 0x00000024
    /*0000004c*/ WORD_004c: .word 0x00000000
    /*00000050*/ WORD_0050: .word 0x00000010
FUNC_END _GLOBAL__sub_I_CustomerThread.cpp


