@
@ -- FILES --
@

@ hi_operation.cpp


unsigned char data[0] = {
};

unsigned char bss[0];

_RODATA__ZTSN4HIRT23OPERATIONOFFLINERUNTIMEE_0000: .ascii "N4hirt23OperationOfflineRuntimeE\0"


unsigned char data.rel.ro._ZTIN4hirt23OperationOfflineRuntimeE[12] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt23OperationOfflineRuntimeE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0xc7, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0xc5, 0x00, 0x00, 
    /*0010*/ 0x08, 0x00, 0x00, 0x00, 0x02, 0xc4, 0x00, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt23OperationOfflineRuntimeE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt23OperationOfflineRuntimeE[40] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0xc6, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0xab, 0x00, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0xad, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0xb6, 0x00, 0x00, 
    /*0020*/ 0x14, 0x00, 0x00, 0x00, 0x02, 0xba, 0x00, 0x00, 
};

unsigned char bss._ZStL8__ioinit[1];

unsigned char data.rel.ro._ZTIN4hirt16OperationOfflineE[12] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt16OperationOfflineE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0xc7, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0xc3, 0x00, 0x00, 
    /*0010*/ 0x08, 0x00, 0x00, 0x00, 0x02, 0xc2, 0x00, 0x00, 
};

unsigned char data.rel.ro._ZTIN4hirt9OperationE[8] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt9OperationE[16] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0xca, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0xc1, 0x00, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt16OperationOfflineE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt16OperationOfflineE[40] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0xc4, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0xa9, 0x00, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0xac, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0xb6, 0x00, 0x00, 
    /*0020*/ 0x14, 0x00, 0x00, 0x00, 0x02, 0xba, 0x00, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt9OperationE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt9OperationE[40] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0xc2, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0xa6, 0x00, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0xa7, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0xb9, 0x00, 0x00, 
    /*0020*/ 0x14, 0x00, 0x00, 0x00, 0x02, 0xba, 0x00, 0x00, 
};

_RODATA__ZN4HIRT23OPERATIONOFFLINERUNTIMEC2ERKNST7__CXX1112BASIC_STRINGICST11CHAR_TRAITSICESAICEEENS_14OPERATION_TYPEE_STR1_4_0000: .ascii "\0"


_RODATA__ZN4HIRT9OPERATION8SETPARAMEPPKVJ_STR1_4_0000: .ascii "invalid param\0\0\0",
_RODATA__ZN4HIRT9OPERATION8SETPARAMEPPKVJ_STR1_4_0010: .ascii "hirt\0"


_RODATA__ZN4HIRT9OPERATIONC2ERKNST7__CXX1112BASIC_STRINGICST11CHAR_TRAITSICESAICEEE_STR1_4_0000: .ascii "basic_string::_M_construct null not valid\0"


_RODATA__ZTSN4HIRT16OPERATIONOFFLINEE_0000: .ascii "N4hirt16OperationOfflineE\0"


_RODATA__ZTSN4HIRT9OPERATIONE_0000: .ascii "N4hirt9OperationE\0"


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt9Operation8setParamEPPKvj
@ Size: 0x6c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt9Operation8setParamEPPKvj
    /*00000000*/ CMP         R1, #0 
    /*00000004*/ BEQ         _ZN4hirt9Operation8setParamEPPKvj_x34
    /*00000008*/ LDR         R1, [R1] 
    /*0000000c*/ CMP         R2, #0 
    /*00000010*/ CMPNE       R1, #0 
    /*00000014*/ MOVEQ       R3, #1 
    /*00000018*/ MOVNE       R3, #0 
    /*0000001c*/ BEQ         _ZN4hirt9Operation8setParamEPPKvj_x34
    /*00000020*/ STR         R1, [R0, #124]              @ 0x7c 
    /*00000024*/ MOV         IP, R0 
    /*00000028*/ MOV         R0, R3 
    /*0000002c*/ STR         R2, [IP, #128]              @ 0x80 
    /*00000030*/ BX          LR 
    _ZN4hirt9Operation8setParamEPPKvj_x34:
    /*00000034*/ MOV         IP, #16384                  @ 0x4000 
    /*00000038*/ PUSH        {R4, LR} 
    /*0000003c*/ SUB         IP, SP, IP 
    /*00000040*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000044*/ LDR         R2, WORD_0064               @ LDR         R2, [PC, #24]               @ 0x0000000000000064 
    /*00000048*/ MOV         R1, #4 
    /*0000004c*/ LDR         R0, WORD_0068               @ LDR         R0, [PC, #20]               @ 0x0000000000000068 
    /*00000050*/ ADD         R2, PC, R2 
    /*00000054*/ ADD         R0, PC, R0 
    /*00000058*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*0000005c*/ MVN         R0, #0 
    /*00000060*/ POP         {R4, PC} 
    /*00000064*/ WORD_0064: .word 0x0000000c
    /*00000068*/ WORD_0068: .word 0x0000000c
FUNC_END _ZN4hirt9Operation8setParamEPPKvj


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNK4hirt9Operation8getParamEPPvPj
@ Size: 0x74
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNK4hirt9Operation8getParamEPPvPj
    /*00000000*/ CMP         R1, #0 
    /*00000004*/ BEQ         _ZNK4hirt9Operation8getParamEPPvPj_x38
    /*00000008*/ LDR         R3, [R1] 
    /*0000000c*/ CMP         R2, #0 
    /*00000010*/ CMPNE       R3, #0 
    /*00000014*/ MOVEQ       R3, #1 
    /*00000018*/ MOVNE       R3, #0 
    /*0000001c*/ BEQ         _ZNK4hirt9Operation8getParamEPPvPj_x38
    /*00000020*/ LDR         IP, [R0, #124]              @ 0x7c 
    /*00000024*/ LDR         R0, [R0, #128]              @ 0x80 
    /*00000028*/ STR         IP, [R1] 
    /*0000002c*/ STR         R0, [R2] 
    /*00000030*/ MOV         R0, R3 
    /*00000034*/ BX          LR 
    _ZNK4hirt9Operation8getParamEPPvPj_x38:
    /*00000038*/ MOV         IP, #16384                  @ 0x4000 
    /*0000003c*/ PUSH        {R4, LR} 
    /*00000040*/ SUB         IP, SP, IP 
    /*00000044*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000048*/ LDR         R2, WORD_006c               @ LDR         R2, [PC, #28]               @ 0x000000000000006c 
    /*0000004c*/ MOV         R1, #4 
    /*00000050*/ LDR         R0, WORD_0070               @ LDR         R0, [PC, #24]               @ 0x0000000000000070 
    /*00000054*/ ADD         R2, PC, R2 
    /*00000058*/ ADD         R0, PC, R0 
    /*0000005c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000060*/ MVN         R3, #0 
    /*00000064*/ MOV         R0, R3 
    /*00000068*/ POP         {R4, PC} 
    /*0000006c*/ WORD_006c: .word 0x00000010
    /*00000070*/ WORD_0070: .word 0x00000010
FUNC_END _ZNK4hirt9Operation8getParamEPPvPj


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
@ Size: 0x178
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4040]             @ 0xfc8 
    /*00000010*/ SUB         SP, SP, #20 
    /*00000014*/ SUBS        R3, R1, #0 
    /*00000018*/ STR         R3, [SP, #12] 
    /*0000001c*/ BEQ         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x170
    /*00000020*/ MOV         R4, R0 
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x24:
    /*00000024*/ LDR         R7, [R3, #12] 
    /*00000028*/ CMP         R7, #0 
    /*0000002c*/ STRNE       R7, [SP, #4] 
    /*00000030*/ MOVNE       R3, R7 
    /*00000034*/ BEQ         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x158
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x38:
    /*00000038*/ LDR         R8, [R3, #12] 
    /*0000003c*/ CMP         R8, #0 
    /*00000040*/ STRNE       R8, [SP, #8] 
    /*00000044*/ MOVNE       R3, R8 
    /*00000048*/ BEQ         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x13c
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x4c:
    /*0000004c*/ LDR         R9, [R3, #12] 
    /*00000050*/ CMP         R9, #0 
    /*00000054*/ BEQ         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x120
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x58:
    /*00000058*/ LDR         SL, [R9, #12] 
    /*0000005c*/ CMP         SL, #0 
    /*00000060*/ BEQ         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x108
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x64:
    /*00000064*/ LDR         FP, [SL, #12] 
    /*00000068*/ CMP         FP, #0 
    /*0000006c*/ BEQ         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_xf4
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x70:
    /*00000070*/ LDR         R6, [FP, #12] 
    /*00000074*/ CMP         R6, #0 
    /*00000078*/ BEQ         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_xe0
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x7c:
    /*0000007c*/ LDR         R5, [R6, #12] 
    /*00000080*/ CMP         R5, #0 
    /*00000084*/ BEQ         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_xcc
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x88:
    /*00000088*/ LDR         R3, [R5, #12] 
    /*0000008c*/ CMP         R3, #0 
    /*00000090*/ MOVNE       R7, R3 
    /*00000094*/ BEQ         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_xb8
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x98:
    /*00000098*/ LDR         R1, [R7, #12] 
    /*0000009c*/ MOV         R0, R4 
    /*000000a0*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000000a4*/ LDR         R8, [R7, #8] 
    /*000000a8*/ MOV         R0, R7 
    /*000000ac*/ BL          _ZdlPv
    /*000000b0*/ SUBS        R7, R8, #0 
    /*000000b4*/ BNE         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x98
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_xb8:
    /*000000b8*/ LDR         R7, [R5, #8] 
    /*000000bc*/ MOV         R0, R5 
    /*000000c0*/ BL          _ZdlPv
    /*000000c4*/ SUBS        R5, R7, #0 
    /*000000c8*/ BNE         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x88
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_xcc:
    /*000000cc*/ LDR         R5, [R6, #8] 
    /*000000d0*/ MOV         R0, R6 
    /*000000d4*/ BL          _ZdlPv
    /*000000d8*/ SUBS        R6, R5, #0 
    /*000000dc*/ BNE         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x7c
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_xe0:
    /*000000e0*/ LDR         R5, [FP, #8] 
    /*000000e4*/ MOV         R0, FP 
    /*000000e8*/ BL          _ZdlPv
    /*000000ec*/ SUBS        FP, R5, #0 
    /*000000f0*/ BNE         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x70
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_xf4:
    /*000000f4*/ LDR         R5, [SL, #8] 
    /*000000f8*/ MOV         R0, SL 
    /*000000fc*/ BL          _ZdlPv
    /*00000100*/ SUBS        SL, R5, #0 
    /*00000104*/ BNE         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x64
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x108:
    /*00000108*/ LDR         R5, [R9, #8] 
    /*0000010c*/ MOV         R0, R9 
    /*00000110*/ BL          _ZdlPv
    /*00000114*/ SUBS        R9, R5, #0 
    /*00000118*/ BNE         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x58
    /*0000011c*/ LDR         R3, [SP, #8] 
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x120:
    /*00000120*/ LDR         R5, [R3, #8] 
    /*00000124*/ MOV         R0, R3 
    /*00000128*/ BL          _ZdlPv
    /*0000012c*/ SUBS        R3, R5, #0 
    /*00000130*/ STR         R3, [SP, #8] 
    /*00000134*/ BNE         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x4c
    /*00000138*/ LDR         R3, [SP, #4] 
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x13c:
    /*0000013c*/ LDR         R5, [R3, #8] 
    /*00000140*/ MOV         R0, R3 
    /*00000144*/ BL          _ZdlPv
    /*00000148*/ SUBS        R3, R5, #0 
    /*0000014c*/ STR         R3, [SP, #4] 
    /*00000150*/ BNE         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x38
    /*00000154*/ LDR         R3, [SP, #12] 
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x158:
    /*00000158*/ LDR         R5, [R3, #8] 
    /*0000015c*/ MOV         R0, R3 
    /*00000160*/ BL          _ZdlPv
    /*00000164*/ SUBS        R3, R5, #0 
    /*00000168*/ STR         R3, [SP, #12] 
    /*0000016c*/ BNE         _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x24
    _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE_x170:
    /*00000170*/ ADD         SP, SP, #20 
    /*00000174*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
FUNC_END _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
@ Size: 0x1a4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4072]             @ 0xfe8 
    /*00000010*/ LDR         R3, WORD_019c               @ LDR         R3, [PC, #388]              @ 0x000000000000019c 
    /*00000014*/ ADD         R2, R0, #32 
    /*00000018*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ ADD         LR, R0, #56                 @ 0x38 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ ADD         IP, R0, #108                @ 0x6c 
    /*0000002c*/ STR         R3, [R0] 
    /*00000030*/ MOV         R3, #0 
    /*00000034*/ STR         R3, [R0, #4] 
    /*00000038*/ SUB         SP, SP, #8 
    /*0000003c*/ STR         R3, [R0, #8] 
    /*00000040*/ MOV         R4, R0 
    /*00000044*/ STR         R3, [R0, #12] 
    /*00000048*/ STR         R3, [R0, #16] 
    /*0000004c*/ STR         R3, [R0, #20] 
    /*00000050*/ STR         R3, [R0, #24] 
    /*00000054*/ VST1.8      {D16-D17}, [R2] 
    /*00000058*/ STR         R2, [R0, #40]               @ 0x28 
    /*0000005c*/ STR         R2, [R0, #44]               @ 0x2c 
    /*00000060*/ STR         R3, [R0, #48]               @ 0x30 
    /*00000064*/ VST1.8      {D16-D17}, [LR] 
    /*00000068*/ STR         R3, [R0, #72]               @ 0x48 
    /*0000006c*/ LDR         R5, [R1, #4] 
    /*00000070*/ STR         IP, [R0, #100]              @ 0x64 
    /*00000074*/ LDR         R6, [R1] 
    /*00000078*/ RSB         R1, R5, #0 
    /*0000007c*/ SUB         R2, R6, R3 
    /*00000080*/ CLZ         R2, R2 
    /*00000084*/ CMP         R6, R1 
    /*00000088*/ LSR         R2, R2, #5 
    /*0000008c*/ MOVEQ       R2, #0 
    /*00000090*/ CMP         R2, R3 
    /*00000094*/ STR         LR, [R0, #64]               @ 0x40 
    /*00000098*/ STR         LR, [R0, #68]               @ 0x44 
    /*0000009c*/ STR         R3, [R0, #76]               @ 0x4c 
    /*000000a0*/ STR         R3, [R0, #80]               @ 0x50 
    /*000000a4*/ STR         R3, [R0, #84]               @ 0x54 
    /*000000a8*/ STR         R3, [R0, #88]               @ 0x58 
    /*000000ac*/ STR         R3, [R0, #92]               @ 0x5c 
    /*000000b0*/ STR         R3, [R0, #96]               @ 0x60 
    /*000000b4*/ BEQ         _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xc4
    /*000000b8*/ LDR         R0, WORD_01a0               @ LDR         R0, [PC, #224]              @ 0x00000000000001a0 
    /*000000bc*/ ADD         R0, PC, R0 
    /*000000c0*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xc4:
    /*000000c4*/ STR         R5, [SP, #4] 
    /*000000c8*/ CMP         R5, #15 
    /*000000cc*/ BHI         _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x108
    /*000000d0*/ CMP         R5, #1 
    /*000000d4*/ LDRBEQ      R3, [R6] 
    /*000000d8*/ STRBEQ      R3, [R4, #108]              @ 0x6c 
    /*000000dc*/ BEQ         _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xe8
    /*000000e0*/ CMP         R5, #0 
    /*000000e4*/ BNE         _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x194
    _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xe8:
    /*000000e8*/ STR         R5, [R4, #104]              @ 0x68 
    /*000000ec*/ MOV         R3, #0 
    /*000000f0*/ STRB        R3, [IP, R5] 
    /*000000f4*/ MOV         R0, R4 
    /*000000f8*/ STR         R3, [R4, #124]              @ 0x7c 
    /*000000fc*/ STR         R3, [R4, #128]              @ 0x80 
    /*00000100*/ ADD         SP, SP, #8 
    /*00000104*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x108:
    /*00000108*/ ADD         R0, R0, #100                @ 0x64 
    /*0000010c*/ ADD         R1, SP, #4 
    /*00000110*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*00000114*/ LDR         R3, [SP, #4] 
    /*00000118*/ STR         R0, [R4, #100]              @ 0x64 
    /*0000011c*/ STR         R3, [R4, #108]              @ 0x6c 
    _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x120:
    /*00000120*/ MOV         R2, R5 
    /*00000124*/ MOV         R1, R6 
    /*00000128*/ BL          memcpy
    /*0000012c*/ LDR         R5, [SP, #4] 
    /*00000130*/ LDR         IP, [R4, #100]              @ 0x64 
    /*00000134*/ B           _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xe8
    /*00000138*/ LDR         R0, [R4, #88]               @ 0x58 
    /*0000013c*/ CMP         R0, #0 
    /*00000140*/ BEQ         _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x148
    /*00000144*/ BL          _ZdlPv
    _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x148:
    /*00000148*/ LDR         R0, [R4, #76]               @ 0x4c 
    /*0000014c*/ CMP         R0, #0 
    /*00000150*/ BEQ         _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x158
    /*00000154*/ BL          _ZdlPv
    _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x158:
    /*00000158*/ LDR         R1, [R4, #60]               @ 0x3c 
    /*0000015c*/ ADD         R0, R4, #52                 @ 0x34 
    /*00000160*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*00000164*/ LDR         R1, [R4, #36]               @ 0x24 
    /*00000168*/ ADD         R0, R4, #28 
    /*0000016c*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*00000170*/ LDR         R0, [R4, #16] 
    /*00000174*/ CMP         R0, #0 
    /*00000178*/ BEQ         _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x180
    /*0000017c*/ BL          _ZdlPv
    _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x180:
    /*00000180*/ LDR         R0, [R4, #4] 
    /*00000184*/ CMP         R0, #0 
    /*00000188*/ BEQ         _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x190
    /*0000018c*/ BL          _ZdlPv
    _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x190:
    /*00000190*/ BL          __cxa_end_cleanup
    _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x194:
    /*00000194*/ MOV         R0, IP 
    /*00000198*/ B           _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x120
    /*0000019c*/ WORD_019c: .word 0x00000178
    /*000001a0*/ WORD_01a0: .word 0x000000dc
FUNC_END _ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE


FUNC_BEGIN _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4072]             @ 0xfe8 
    /*00000010*/ LDR         R3, WORD_019c               @ LDR         R3, [PC, #388]              @ 0x000000000000019c 
    /*00000014*/ ADD         R2, R0, #32 
    /*00000018*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ ADD         LR, R0, #56                 @ 0x38 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ ADD         IP, R0, #108                @ 0x6c 
    /*0000002c*/ STR         R3, [R0] 
    /*00000030*/ MOV         R3, #0 
    /*00000034*/ STR         R3, [R0, #4] 
    /*00000038*/ SUB         SP, SP, #8 
    /*0000003c*/ STR         R3, [R0, #8] 
    /*00000040*/ MOV         R4, R0 
    /*00000044*/ STR         R3, [R0, #12] 
    /*00000048*/ STR         R3, [R0, #16] 
    /*0000004c*/ STR         R3, [R0, #20] 
    /*00000050*/ STR         R3, [R0, #24] 
    /*00000054*/ VST1.8      {D16-D17}, [R2] 
    /*00000058*/ STR         R2, [R0, #40]               @ 0x28 
    /*0000005c*/ STR         R2, [R0, #44]               @ 0x2c 
    /*00000060*/ STR         R3, [R0, #48]               @ 0x30 
    /*00000064*/ VST1.8      {D16-D17}, [LR] 
    /*00000068*/ STR         R3, [R0, #72]               @ 0x48 
    /*0000006c*/ LDR         R5, [R1, #4] 
    /*00000070*/ STR         IP, [R0, #100]              @ 0x64 
    /*00000074*/ LDR         R6, [R1] 
    /*00000078*/ RSB         R1, R5, #0 
    /*0000007c*/ SUB         R2, R6, R3 
    /*00000080*/ CLZ         R2, R2 
    /*00000084*/ CMP         R6, R1 
    /*00000088*/ LSR         R2, R2, #5 
    /*0000008c*/ MOVEQ       R2, #0 
    /*00000090*/ CMP         R2, R3 
    /*00000094*/ STR         LR, [R0, #64]               @ 0x40 
    /*00000098*/ STR         LR, [R0, #68]               @ 0x44 
    /*0000009c*/ STR         R3, [R0, #76]               @ 0x4c 
    /*000000a0*/ STR         R3, [R0, #80]               @ 0x50 
    /*000000a4*/ STR         R3, [R0, #84]               @ 0x54 
    /*000000a8*/ STR         R3, [R0, #88]               @ 0x58 
    /*000000ac*/ STR         R3, [R0, #92]               @ 0x5c 
    /*000000b0*/ STR         R3, [R0, #96]               @ 0x60 
    /*000000b4*/ BEQ         _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xc4
    /*000000b8*/ LDR         R0, WORD_01a0               @ LDR         R0, [PC, #224]              @ 0x00000000000001a0 
    /*000000bc*/ ADD         R0, PC, R0 
    /*000000c0*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xc4:
    /*000000c4*/ STR         R5, [SP, #4] 
    /*000000c8*/ CMP         R5, #15 
    /*000000cc*/ BHI         _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x108
    /*000000d0*/ CMP         R5, #1 
    /*000000d4*/ LDRBEQ      R3, [R6] 
    /*000000d8*/ STRBEQ      R3, [R4, #108]              @ 0x6c 
    /*000000dc*/ BEQ         _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xe8
    /*000000e0*/ CMP         R5, #0 
    /*000000e4*/ BNE         _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x194
    _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xe8:
    /*000000e8*/ STR         R5, [R4, #104]              @ 0x68 
    /*000000ec*/ MOV         R3, #0 
    /*000000f0*/ STRB        R3, [IP, R5] 
    /*000000f4*/ MOV         R0, R4 
    /*000000f8*/ STR         R3, [R4, #124]              @ 0x7c 
    /*000000fc*/ STR         R3, [R4, #128]              @ 0x80 
    /*00000100*/ ADD         SP, SP, #8 
    /*00000104*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x108:
    /*00000108*/ ADD         R0, R0, #100                @ 0x64 
    /*0000010c*/ ADD         R1, SP, #4 
    /*00000110*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*00000114*/ LDR         R3, [SP, #4] 
    /*00000118*/ STR         R0, [R4, #100]              @ 0x64 
    /*0000011c*/ STR         R3, [R4, #108]              @ 0x6c 
    _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x120:
    /*00000120*/ MOV         R2, R5 
    /*00000124*/ MOV         R1, R6 
    /*00000128*/ BL          memcpy
    /*0000012c*/ LDR         R5, [SP, #4] 
    /*00000130*/ LDR         IP, [R4, #100]              @ 0x64 
    /*00000134*/ B           _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xe8
    /*00000138*/ LDR         R0, [R4, #88]               @ 0x58 
    /*0000013c*/ CMP         R0, #0 
    /*00000140*/ BEQ         _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x148
    /*00000144*/ BL          _ZdlPv
    _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x148:
    /*00000148*/ LDR         R0, [R4, #76]               @ 0x4c 
    /*0000014c*/ CMP         R0, #0 
    /*00000150*/ BEQ         _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x158
    /*00000154*/ BL          _ZdlPv
    _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x158:
    /*00000158*/ LDR         R1, [R4, #60]               @ 0x3c 
    /*0000015c*/ ADD         R0, R4, #52                 @ 0x34 
    /*00000160*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*00000164*/ LDR         R1, [R4, #36]               @ 0x24 
    /*00000168*/ ADD         R0, R4, #28 
    /*0000016c*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*00000170*/ LDR         R0, [R4, #16] 
    /*00000174*/ CMP         R0, #0 
    /*00000178*/ BEQ         _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x180
    /*0000017c*/ BL          _ZdlPv
    _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x180:
    /*00000180*/ LDR         R0, [R4, #4] 
    /*00000184*/ CMP         R0, #0 
    /*00000188*/ BEQ         _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x190
    /*0000018c*/ BL          _ZdlPv
    _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x190:
    /*00000190*/ BL          __cxa_end_cleanup
    _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x194:
    /*00000194*/ MOV         R0, IP 
    /*00000198*/ B           _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_x120
    /*0000019c*/ WORD_019c: .word 0x00000178
    /*000001a0*/ WORD_01a0: .word 0x000000dc
FUNC_END _ZN4hirt9OperationC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt9OperationC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
@ Size: 0x17
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt9OperationD2Ev
@ Size: 0x20c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt9OperationD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R3, R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4056]             @ 0xfd8 
    /*00000010*/ LDR         R3, WORD_0208               @ LDR         R3, [PC, #496]              @ 0x0000000000000208 
    /*00000014*/ MOV         SL, #0 
    /*00000018*/ LDR         R8, [R0, #76]               @ 0x4c 
    /*0000001c*/ MOV         R6, R0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ STR         SL, [R0, #124]              @ 0x7c 
    /*00000028*/ ADD         R2, R3, #8 
    /*0000002c*/ LDR         R3, [R0, #80]               @ 0x50 
    /*00000030*/ STR         R2, [R0] 
    /*00000034*/ CMP         R8, R3 
    /*00000038*/ ADDNE       R9, R8, #4 
    /*0000003c*/ BEQ         _ZN4hirt9OperationD2Ev_xcc
    _ZN4hirt9OperationD2Ev_x40:
    /*00000040*/ LDR         R7, [R8] 
    /*00000044*/ CMP         R7, #0 
    /*00000048*/ BEQ         _ZN4hirt9OperationD2Ev_xa8
    /*0000004c*/ LDR         R5, [R7, #8] 
    /*00000050*/ LDR         FP, [R7, #12] 
    /*00000054*/ CMP         R5, FP 
    /*00000058*/ BEQ         _ZN4hirt9OperationD2Ev_x84
    /*0000005c*/ ADD         R4, R5, #8 
    _ZN4hirt9OperationD2Ev_x60:
    /*00000060*/ LDR         R0, [R4, #-8] 
    /*00000064*/ ADD         R5, R5, #24 
    /*00000068*/ CMP         R4, R0 
    /*0000006c*/ ADD         R4, R4, #24 
    /*00000070*/ BEQ         _ZN4hirt9OperationD2Ev_x78
    /*00000074*/ BL          _ZdlPv
    _ZN4hirt9OperationD2Ev_x78:
    /*00000078*/ CMP         FP, R5 
    /*0000007c*/ BNE         _ZN4hirt9OperationD2Ev_x60
    /*00000080*/ LDR         FP, [R7, #8] 
    _ZN4hirt9OperationD2Ev_x84:
    /*00000084*/ CMP         FP, #0 
    /*00000088*/ BEQ         _ZN4hirt9OperationD2Ev_x94
    /*0000008c*/ MOV         R0, FP 
    /*00000090*/ BL          _ZdlPv
    _ZN4hirt9OperationD2Ev_x94:
    /*00000094*/ MOV         R0, R7 
    /*00000098*/ MOV         R1, #20 
    /*0000009c*/ BL          _ZdlPvj
    /*000000a0*/ LDR         R3, [R6, #80]               @ 0x50 
    /*000000a4*/ STR         SL, [R8] 
    _ZN4hirt9OperationD2Ev_xa8:
    /*000000a8*/ CMP         R3, R9 
    /*000000ac*/ BEQ         _ZN4hirt9OperationD2Ev_xbc
    /*000000b0*/ SUB         R2, R3, R9 
    /*000000b4*/ LSRS        R1, R2, #2 
    /*000000b8*/ BNE         _ZN4hirt9OperationD2Ev_x1e0
    _ZN4hirt9OperationD2Ev_xbc:
    /*000000bc*/ SUB         R3, R3, #4 
    /*000000c0*/ CMP         R8, R3 
    /*000000c4*/ STR         R3, [R6, #80]               @ 0x50 
    /*000000c8*/ BNE         _ZN4hirt9OperationD2Ev_x40
    _ZN4hirt9OperationD2Ev_xcc:
    /*000000cc*/ LDR         R8, [R6, #88]               @ 0x58 
    /*000000d0*/ LDR         R3, [R6, #92]               @ 0x5c 
    /*000000d4*/ CMP         R8, R3 
    /*000000d8*/ ADDNE       R9, R8, #4 
    /*000000dc*/ MOVNE       SL, #0 
    /*000000e0*/ BEQ         _ZN4hirt9OperationD2Ev_x16c
    _ZN4hirt9OperationD2Ev_xe4:
    /*000000e4*/ LDR         R7, [R8] 
    /*000000e8*/ CMP         R7, #0 
    /*000000ec*/ BEQ         _ZN4hirt9OperationD2Ev_x148
    /*000000f0*/ LDMIB       R7, {R5, FP} 
    /*000000f4*/ CMP         R5, FP 
    /*000000f8*/ BEQ         _ZN4hirt9OperationD2Ev_x124
    /*000000fc*/ ADD         R4, R5, #8 
    _ZN4hirt9OperationD2Ev_x100:
    /*00000100*/ LDR         R0, [R4, #-8] 
    /*00000104*/ ADD         R5, R5, #24 
    /*00000108*/ CMP         R0, R4 
    /*0000010c*/ ADD         R4, R4, #24 
    /*00000110*/ BEQ         _ZN4hirt9OperationD2Ev_x118
    /*00000114*/ BL          _ZdlPv
    _ZN4hirt9OperationD2Ev_x118:
    /*00000118*/ CMP         FP, R5 
    /*0000011c*/ BNE         _ZN4hirt9OperationD2Ev_x100
    /*00000120*/ LDR         FP, [R7, #4] 
    _ZN4hirt9OperationD2Ev_x124:
    /*00000124*/ CMP         FP, #0 
    /*00000128*/ BEQ         _ZN4hirt9OperationD2Ev_x134
    /*0000012c*/ MOV         R0, FP 
    /*00000130*/ BL          _ZdlPv
    _ZN4hirt9OperationD2Ev_x134:
    /*00000134*/ MOV         R0, R7 
    /*00000138*/ MOV         R1, #16 
    /*0000013c*/ BL          _ZdlPvj
    /*00000140*/ LDR         R3, [R6, #92]               @ 0x5c 
    /*00000144*/ STR         SL, [R8] 
    _ZN4hirt9OperationD2Ev_x148:
    /*00000148*/ CMP         R3, R9 
    /*0000014c*/ BEQ         _ZN4hirt9OperationD2Ev_x15c
    /*00000150*/ SUB         R2, R3, R9 
    /*00000154*/ LSRS        R1, R2, #2 
    /*00000158*/ BNE         _ZN4hirt9OperationD2Ev_x1f4
    _ZN4hirt9OperationD2Ev_x15c:
    /*0000015c*/ SUB         R3, R3, #4 
    /*00000160*/ CMP         R8, R3 
    /*00000164*/ STR         R3, [R6, #92]               @ 0x5c 
    /*00000168*/ BNE         _ZN4hirt9OperationD2Ev_xe4
    _ZN4hirt9OperationD2Ev_x16c:
    /*0000016c*/ LDR         R0, [R6, #100]              @ 0x64 
    /*00000170*/ ADD         R3, R6, #108                @ 0x6c 
    /*00000174*/ CMP         R0, R3 
    /*00000178*/ BEQ         _ZN4hirt9OperationD2Ev_x180
    /*0000017c*/ BL          _ZdlPv
    _ZN4hirt9OperationD2Ev_x180:
    /*00000180*/ LDR         R0, [R6, #88]               @ 0x58 
    /*00000184*/ CMP         R0, #0 
    /*00000188*/ BEQ         _ZN4hirt9OperationD2Ev_x190
    /*0000018c*/ BL          _ZdlPv
    _ZN4hirt9OperationD2Ev_x190:
    /*00000190*/ LDR         R0, [R6, #76]               @ 0x4c 
    /*00000194*/ CMP         R0, #0 
    /*00000198*/ BEQ         _ZN4hirt9OperationD2Ev_x1a0
    /*0000019c*/ BL          _ZdlPv
    _ZN4hirt9OperationD2Ev_x1a0:
    /*000001a0*/ LDR         R1, [R6, #60]               @ 0x3c 
    /*000001a4*/ ADD         R0, R6, #52                 @ 0x34 
    /*000001a8*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001ac*/ LDR         R1, [R6, #36]               @ 0x24 
    /*000001b0*/ ADD         R0, R6, #28 
    /*000001b4*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001b8*/ LDR         R0, [R6, #16] 
    /*000001bc*/ CMP         R0, #0 
    /*000001c0*/ BEQ         _ZN4hirt9OperationD2Ev_x1c8
    /*000001c4*/ BL          _ZdlPv
    _ZN4hirt9OperationD2Ev_x1c8:
    /*000001c8*/ LDR         R0, [R6, #4] 
    /*000001cc*/ CMP         R0, #0 
    /*000001d0*/ BEQ         _ZN4hirt9OperationD2Ev_x1d8
    /*000001d4*/ BL          _ZdlPv
    _ZN4hirt9OperationD2Ev_x1d8:
    /*000001d8*/ MOV         R0, R6 
    /*000001dc*/ POP         {R3, R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZN4hirt9OperationD2Ev_x1e0:
    /*000001e0*/ MOV         R1, R9 
    /*000001e4*/ MOV         R0, R8 
    /*000001e8*/ BL          memmove
    /*000001ec*/ LDR         R3, [R6, #80]               @ 0x50 
    /*000001f0*/ B           _ZN4hirt9OperationD2Ev_xbc
    _ZN4hirt9OperationD2Ev_x1f4:
    /*000001f4*/ MOV         R1, R9 
    /*000001f8*/ MOV         R0, R8 
    /*000001fc*/ BL          memmove
    /*00000200*/ LDR         R3, [R6, #92]               @ 0x5c 
    /*00000204*/ B           _ZN4hirt9OperationD2Ev_x15c
    /*00000208*/ WORD_0208: .word 0x000001e0
FUNC_END _ZN4hirt9OperationD2Ev


FUNC_BEGIN _ZN4hirt9OperationD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R3, R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4056]             @ 0xfd8 
    /*00000010*/ LDR         R3, WORD_0208               @ LDR         R3, [PC, #496]              @ 0x0000000000000208 
    /*00000014*/ MOV         SL, #0 
    /*00000018*/ LDR         R8, [R0, #76]               @ 0x4c 
    /*0000001c*/ MOV         R6, R0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ STR         SL, [R0, #124]              @ 0x7c 
    /*00000028*/ ADD         R2, R3, #8 
    /*0000002c*/ LDR         R3, [R0, #80]               @ 0x50 
    /*00000030*/ STR         R2, [R0] 
    /*00000034*/ CMP         R8, R3 
    /*00000038*/ ADDNE       R9, R8, #4 
    /*0000003c*/ BEQ         _ZN4hirt9OperationD1Ev_xcc
    _ZN4hirt9OperationD1Ev_x40:
    /*00000040*/ LDR         R7, [R8] 
    /*00000044*/ CMP         R7, #0 
    /*00000048*/ BEQ         _ZN4hirt9OperationD1Ev_xa8
    /*0000004c*/ LDR         R5, [R7, #8] 
    /*00000050*/ LDR         FP, [R7, #12] 
    /*00000054*/ CMP         R5, FP 
    /*00000058*/ BEQ         _ZN4hirt9OperationD1Ev_x84
    /*0000005c*/ ADD         R4, R5, #8 
    _ZN4hirt9OperationD1Ev_x60:
    /*00000060*/ LDR         R0, [R4, #-8] 
    /*00000064*/ ADD         R5, R5, #24 
    /*00000068*/ CMP         R4, R0 
    /*0000006c*/ ADD         R4, R4, #24 
    /*00000070*/ BEQ         _ZN4hirt9OperationD1Ev_x78
    /*00000074*/ BL          _ZdlPv
    _ZN4hirt9OperationD1Ev_x78:
    /*00000078*/ CMP         FP, R5 
    /*0000007c*/ BNE         _ZN4hirt9OperationD1Ev_x60
    /*00000080*/ LDR         FP, [R7, #8] 
    _ZN4hirt9OperationD1Ev_x84:
    /*00000084*/ CMP         FP, #0 
    /*00000088*/ BEQ         _ZN4hirt9OperationD1Ev_x94
    /*0000008c*/ MOV         R0, FP 
    /*00000090*/ BL          _ZdlPv
    _ZN4hirt9OperationD1Ev_x94:
    /*00000094*/ MOV         R0, R7 
    /*00000098*/ MOV         R1, #20 
    /*0000009c*/ BL          _ZdlPvj
    /*000000a0*/ LDR         R3, [R6, #80]               @ 0x50 
    /*000000a4*/ STR         SL, [R8] 
    _ZN4hirt9OperationD1Ev_xa8:
    /*000000a8*/ CMP         R3, R9 
    /*000000ac*/ BEQ         _ZN4hirt9OperationD1Ev_xbc
    /*000000b0*/ SUB         R2, R3, R9 
    /*000000b4*/ LSRS        R1, R2, #2 
    /*000000b8*/ BNE         _ZN4hirt9OperationD1Ev_x1e0
    _ZN4hirt9OperationD1Ev_xbc:
    /*000000bc*/ SUB         R3, R3, #4 
    /*000000c0*/ CMP         R8, R3 
    /*000000c4*/ STR         R3, [R6, #80]               @ 0x50 
    /*000000c8*/ BNE         _ZN4hirt9OperationD1Ev_x40
    _ZN4hirt9OperationD1Ev_xcc:
    /*000000cc*/ LDR         R8, [R6, #88]               @ 0x58 
    /*000000d0*/ LDR         R3, [R6, #92]               @ 0x5c 
    /*000000d4*/ CMP         R8, R3 
    /*000000d8*/ ADDNE       R9, R8, #4 
    /*000000dc*/ MOVNE       SL, #0 
    /*000000e0*/ BEQ         _ZN4hirt9OperationD1Ev_x16c
    _ZN4hirt9OperationD1Ev_xe4:
    /*000000e4*/ LDR         R7, [R8] 
    /*000000e8*/ CMP         R7, #0 
    /*000000ec*/ BEQ         _ZN4hirt9OperationD1Ev_x148
    /*000000f0*/ LDMIB       R7, {R5, FP} 
    /*000000f4*/ CMP         R5, FP 
    /*000000f8*/ BEQ         _ZN4hirt9OperationD1Ev_x124
    /*000000fc*/ ADD         R4, R5, #8 
    _ZN4hirt9OperationD1Ev_x100:
    /*00000100*/ LDR         R0, [R4, #-8] 
    /*00000104*/ ADD         R5, R5, #24 
    /*00000108*/ CMP         R0, R4 
    /*0000010c*/ ADD         R4, R4, #24 
    /*00000110*/ BEQ         _ZN4hirt9OperationD1Ev_x118
    /*00000114*/ BL          _ZdlPv
    _ZN4hirt9OperationD1Ev_x118:
    /*00000118*/ CMP         FP, R5 
    /*0000011c*/ BNE         _ZN4hirt9OperationD1Ev_x100
    /*00000120*/ LDR         FP, [R7, #4] 
    _ZN4hirt9OperationD1Ev_x124:
    /*00000124*/ CMP         FP, #0 
    /*00000128*/ BEQ         _ZN4hirt9OperationD1Ev_x134
    /*0000012c*/ MOV         R0, FP 
    /*00000130*/ BL          _ZdlPv
    _ZN4hirt9OperationD1Ev_x134:
    /*00000134*/ MOV         R0, R7 
    /*00000138*/ MOV         R1, #16 
    /*0000013c*/ BL          _ZdlPvj
    /*00000140*/ LDR         R3, [R6, #92]               @ 0x5c 
    /*00000144*/ STR         SL, [R8] 
    _ZN4hirt9OperationD1Ev_x148:
    /*00000148*/ CMP         R3, R9 
    /*0000014c*/ BEQ         _ZN4hirt9OperationD1Ev_x15c
    /*00000150*/ SUB         R2, R3, R9 
    /*00000154*/ LSRS        R1, R2, #2 
    /*00000158*/ BNE         _ZN4hirt9OperationD1Ev_x1f4
    _ZN4hirt9OperationD1Ev_x15c:
    /*0000015c*/ SUB         R3, R3, #4 
    /*00000160*/ CMP         R8, R3 
    /*00000164*/ STR         R3, [R6, #92]               @ 0x5c 
    /*00000168*/ BNE         _ZN4hirt9OperationD1Ev_xe4
    _ZN4hirt9OperationD1Ev_x16c:
    /*0000016c*/ LDR         R0, [R6, #100]              @ 0x64 
    /*00000170*/ ADD         R3, R6, #108                @ 0x6c 
    /*00000174*/ CMP         R0, R3 
    /*00000178*/ BEQ         _ZN4hirt9OperationD1Ev_x180
    /*0000017c*/ BL          _ZdlPv
    _ZN4hirt9OperationD1Ev_x180:
    /*00000180*/ LDR         R0, [R6, #88]               @ 0x58 
    /*00000184*/ CMP         R0, #0 
    /*00000188*/ BEQ         _ZN4hirt9OperationD1Ev_x190
    /*0000018c*/ BL          _ZdlPv
    _ZN4hirt9OperationD1Ev_x190:
    /*00000190*/ LDR         R0, [R6, #76]               @ 0x4c 
    /*00000194*/ CMP         R0, #0 
    /*00000198*/ BEQ         _ZN4hirt9OperationD1Ev_x1a0
    /*0000019c*/ BL          _ZdlPv
    _ZN4hirt9OperationD1Ev_x1a0:
    /*000001a0*/ LDR         R1, [R6, #60]               @ 0x3c 
    /*000001a4*/ ADD         R0, R6, #52                 @ 0x34 
    /*000001a8*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001ac*/ LDR         R1, [R6, #36]               @ 0x24 
    /*000001b0*/ ADD         R0, R6, #28 
    /*000001b4*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001b8*/ LDR         R0, [R6, #16] 
    /*000001bc*/ CMP         R0, #0 
    /*000001c0*/ BEQ         _ZN4hirt9OperationD1Ev_x1c8
    /*000001c4*/ BL          _ZdlPv
    _ZN4hirt9OperationD1Ev_x1c8:
    /*000001c8*/ LDR         R0, [R6, #4] 
    /*000001cc*/ CMP         R0, #0 
    /*000001d0*/ BEQ         _ZN4hirt9OperationD1Ev_x1d8
    /*000001d4*/ BL          _ZdlPv
    _ZN4hirt9OperationD1Ev_x1d8:
    /*000001d8*/ MOV         R0, R6 
    /*000001dc*/ POP         {R3, R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZN4hirt9OperationD1Ev_x1e0:
    /*000001e0*/ MOV         R1, R9 
    /*000001e4*/ MOV         R0, R8 
    /*000001e8*/ BL          memmove
    /*000001ec*/ LDR         R3, [R6, #80]               @ 0x50 
    /*000001f0*/ B           _ZN4hirt9OperationD1Ev_xbc
    _ZN4hirt9OperationD1Ev_x1f4:
    /*000001f4*/ MOV         R1, R9 
    /*000001f8*/ MOV         R0, R8 
    /*000001fc*/ BL          memmove
    /*00000200*/ LDR         R3, [R6, #92]               @ 0x5c 
    /*00000204*/ B           _ZN4hirt9OperationD1Ev_x15c
    /*00000208*/ WORD_0208: .word 0x000001e0
FUNC_END _ZN4hirt9OperationD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt9OperationD0Ev
@ Size: 0x2c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt9OperationD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ MOV         R4, R0 
    /*00000014*/ BL          _ZN4hirt9OperationD1Ev
    /*00000018*/ MOV         R0, R4 
    /*0000001c*/ MOV         R1, #132                    @ 0x84 
    /*00000020*/ BL          _ZdlPvj
    /*00000024*/ MOV         R0, R4 
    /*00000028*/ POP         {R4, PC} 
FUNC_END _ZN4hirt9OperationD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt16OperationOfflineD2Ev
@ Size: 0x4c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt16OperationOfflineD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0048               @ LDR         R3, [PC, #48]               @ 0x0000000000000048 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #152]              @ 0x98 
    /*0000001c*/ ADD         R2, R4, #160                @ 0xa0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ CMP         R0, R2 
    /*00000028*/ ADD         R3, R3, #8 
    /*0000002c*/ STR         R3, [R4] 
    /*00000030*/ BEQ         _ZN4hirt16OperationOfflineD2Ev_x38
    /*00000034*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineD2Ev_x38:
    /*00000038*/ MOV         R0, R4 
    /*0000003c*/ BL          _ZN4hirt9OperationD2Ev
    /*00000040*/ MOV         R0, R4 
    /*00000044*/ POP         {R4, PC} 
    /*00000048*/ WORD_0048: .word 0x00000020
FUNC_END _ZN4hirt16OperationOfflineD2Ev


FUNC_BEGIN _ZN4hirt16OperationOfflineD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0048               @ LDR         R3, [PC, #48]               @ 0x0000000000000048 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #152]              @ 0x98 
    /*0000001c*/ ADD         R2, R4, #160                @ 0xa0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ CMP         R0, R2 
    /*00000028*/ ADD         R3, R3, #8 
    /*0000002c*/ STR         R3, [R4] 
    /*00000030*/ BEQ         _ZN4hirt16OperationOfflineD1Ev_x38
    /*00000034*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineD1Ev_x38:
    /*00000038*/ MOV         R0, R4 
    /*0000003c*/ BL          _ZN4hirt9OperationD2Ev
    /*00000040*/ MOV         R0, R4 
    /*00000044*/ POP         {R4, PC} 
    /*00000048*/ WORD_0048: .word 0x00000020
FUNC_END _ZN4hirt16OperationOfflineD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt23OperationOfflineRuntimeD2Ev
@ Size: 0x4c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt23OperationOfflineRuntimeD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0048               @ LDR         R3, [PC, #48]               @ 0x0000000000000048 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #152]              @ 0x98 
    /*0000001c*/ ADD         R2, R4, #160                @ 0xa0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ CMP         R0, R2 
    /*00000028*/ ADD         R3, R3, #8 
    /*0000002c*/ STR         R3, [R4] 
    /*00000030*/ BEQ         _ZN4hirt23OperationOfflineRuntimeD2Ev_x38
    /*00000034*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeD2Ev_x38:
    /*00000038*/ MOV         R0, R4 
    /*0000003c*/ BL          _ZN4hirt9OperationD2Ev
    /*00000040*/ MOV         R0, R4 
    /*00000044*/ POP         {R4, PC} 
    /*00000048*/ WORD_0048: .word 0x00000020
FUNC_END _ZN4hirt23OperationOfflineRuntimeD2Ev


FUNC_BEGIN _ZN4hirt23OperationOfflineRuntimeD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0048               @ LDR         R3, [PC, #48]               @ 0x0000000000000048 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #152]              @ 0x98 
    /*0000001c*/ ADD         R2, R4, #160                @ 0xa0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ CMP         R0, R2 
    /*00000028*/ ADD         R3, R3, #8 
    /*0000002c*/ STR         R3, [R4] 
    /*00000030*/ BEQ         _ZN4hirt23OperationOfflineRuntimeD1Ev_x38
    /*00000034*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeD1Ev_x38:
    /*00000038*/ MOV         R0, R4 
    /*0000003c*/ BL          _ZN4hirt9OperationD2Ev
    /*00000040*/ MOV         R0, R4 
    /*00000044*/ POP         {R4, PC} 
    /*00000048*/ WORD_0048: .word 0x00000020
FUNC_END _ZN4hirt23OperationOfflineRuntimeD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt16OperationOfflineD0Ev
@ Size: 0x58
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt16OperationOfflineD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0054               @ LDR         R3, [PC, #60]               @ 0x0000000000000054 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #152]              @ 0x98 
    /*0000001c*/ ADD         R2, R4, #160                @ 0xa0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ CMP         R0, R2 
    /*00000028*/ ADD         R3, R3, #8 
    /*0000002c*/ STR         R3, [R4] 
    /*00000030*/ BEQ         _ZN4hirt16OperationOfflineD0Ev_x38
    /*00000034*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineD0Ev_x38:
    /*00000038*/ MOV         R0, R4 
    /*0000003c*/ BL          _ZN4hirt9OperationD2Ev
    /*00000040*/ MOV         R0, R4 
    /*00000044*/ MOV         R1, #188                    @ 0xbc 
    /*00000048*/ BL          _ZdlPvj
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ POP         {R4, PC} 
    /*00000054*/ WORD_0054: .word 0x0000002c
FUNC_END _ZN4hirt16OperationOfflineD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt23OperationOfflineRuntimeD0Ev
@ Size: 0x58
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt23OperationOfflineRuntimeD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0054               @ LDR         R3, [PC, #60]               @ 0x0000000000000054 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #152]              @ 0x98 
    /*0000001c*/ ADD         R2, R4, #160                @ 0xa0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ CMP         R0, R2 
    /*00000028*/ ADD         R3, R3, #8 
    /*0000002c*/ STR         R3, [R4] 
    /*00000030*/ BEQ         _ZN4hirt23OperationOfflineRuntimeD0Ev_x38
    /*00000034*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeD0Ev_x38:
    /*00000038*/ MOV         R0, R4 
    /*0000003c*/ BL          _ZN4hirt9OperationD2Ev
    /*00000040*/ MOV         R0, R4 
    /*00000044*/ MOV         R1, #192                    @ 0xc0 
    /*00000048*/ BL          _ZdlPvj
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ POP         {R4, PC} 
    /*00000054*/ WORD_0054: .word 0x0000002c
FUNC_END _ZN4hirt23OperationOfflineRuntimeD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE
@ Size: 0x254
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4056]             @ 0xfd8 
    /*00000010*/ LDR         R3, WORD_0240               @ LDR         R3, [PC, #552]              @ 0x0000000000000240 
    /*00000014*/ ADD         R5, R0, #32 
    /*00000018*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ ADD         LR, R0, #56                 @ 0x38 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ ADD         IP, R0, #108                @ 0x6c 
    /*0000002c*/ STR         R3, [R0] 
    /*00000030*/ MOV         R3, #0 
    /*00000034*/ STR         R3, [R0, #4] 
    /*00000038*/ MOV         R6, R2 
    /*0000003c*/ STR         R3, [R0, #8] 
    /*00000040*/ SUB         SP, SP, #20 
    /*00000044*/ STR         R3, [R0, #12] 
    /*00000048*/ MOV         R4, R0 
    /*0000004c*/ STR         R3, [R0, #16] 
    /*00000050*/ STR         R3, [R0, #20] 
    /*00000054*/ STR         R3, [R0, #24] 
    /*00000058*/ VST1.8      {D16-D17}, [R5] 
    /*0000005c*/ STR         R5, [R0, #40]               @ 0x28 
    /*00000060*/ STR         R5, [R0, #44]               @ 0x2c 
    /*00000064*/ STR         R3, [R0, #48]               @ 0x30 
    /*00000068*/ VST1.8      {D16-D17}, [LR] 
    /*0000006c*/ STR         R3, [R0, #72]               @ 0x48 
    /*00000070*/ LDR         R5, [R1, #4] 
    /*00000074*/ STR         IP, [R0, #100]              @ 0x64 
    /*00000078*/ LDR         R7, [R1] 
    /*0000007c*/ RSB         R1, R5, #0 
    /*00000080*/ SUB         R2, R7, R3 
    /*00000084*/ CLZ         R2, R2 
    /*00000088*/ CMP         R7, R1 
    /*0000008c*/ LSR         R2, R2, #5 
    /*00000090*/ MOVEQ       R2, #0 
    /*00000094*/ CMP         R2, R3 
    /*00000098*/ STR         LR, [R0, #64]               @ 0x40 
    /*0000009c*/ STR         LR, [R0, #68]               @ 0x44 
    /*000000a0*/ STR         R3, [R0, #76]               @ 0x4c 
    /*000000a4*/ STR         R3, [R0, #80]               @ 0x50 
    /*000000a8*/ STR         R3, [R0, #84]               @ 0x54 
    /*000000ac*/ STR         R3, [R0, #88]               @ 0x58 
    /*000000b0*/ STR         R3, [R0, #92]               @ 0x5c 
    /*000000b4*/ STR         R3, [R0, #96]               @ 0x60 
    /*000000b8*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xc8
    /*000000bc*/ LDR         R0, WORD_0244               @ LDR         R0, [PC, #384]              @ 0x0000000000000244 
    /*000000c0*/ ADD         R0, PC, R0 
    /*000000c4*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xc8:
    /*000000c8*/ STR         R5, [SP, #12] 
    /*000000cc*/ CMP         R5, #15 
    /*000000d0*/ BHI         _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x190
    /*000000d4*/ CMP         R5, #1 
    /*000000d8*/ LDRBEQ      R3, [R7] 
    /*000000dc*/ STRBEQ      R3, [R4, #108]              @ 0x6c 
    /*000000e0*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xec
    /*000000e4*/ CMP         R5, #0 
    /*000000e8*/ BNE         _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x21c
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xec:
    /*000000ec*/ LDR         R2, WORD_0248               @ LDR         R2, [PC, #340]              @ 0x0000000000000248 
    /*000000f0*/ MOV         R3, #0 
    /*000000f4*/ STR         R5, [R4, #104]              @ 0x68 
    /*000000f8*/ MOV         R1, R3 
    /*000000fc*/ ADD         R2, PC, R2 
    /*00000100*/ MOV         LR, #3 
    /*00000104*/ STRB        R3, [IP, R5] 
    /*00000108*/ ADD         R2, R2, #8 
    /*0000010c*/ STR         R2, [R4] 
    /*00000110*/ MOV         R2, R3 
    /*00000114*/ STR         R3, [R4, #124]              @ 0x7c 
    /*00000118*/ ADD         R5, R4, #160                @ 0xa0 
    /*0000011c*/ STR         R3, [R4, #128]              @ 0x80 
    /*00000120*/ ADD         R0, R4, #152                @ 0x98 
    /*00000124*/ STR         R3, [R4, #156]              @ 0x9c 
    /*00000128*/ STRB        R3, [R4, #160]              @ 0xa0 
    /*0000012c*/ STR         R3, [R4, #148]              @ 0x94 
    /*00000130*/ STR         R3, [SP] 
    /*00000134*/ LDR         R3, WORD_024c               @ LDR         R3, [PC, #272]              @ 0x000000000000024c 
    /*00000138*/ STR         LR, [R4, #144]              @ 0x90 
    /*0000013c*/ STR         R5, [R4, #152]              @ 0x98 
    /*00000140*/ ADD         R3, PC, R3 
    /*00000144*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEjjPKcj
    /*00000148*/ VMOV.I32    D16, #0                     @ 0x00000000 
    /*0000014c*/ LDR         R3, WORD_0250               @ LDR         R3, [PC, #252]              @ 0x0000000000000250 
    /*00000150*/ ADD         R1, R4, #136                @ 0x88 
    /*00000154*/ MOV         R2, #0 
    /*00000158*/ MOV         R0, #3 
    /*0000015c*/ ADD         R3, PC, R3 
    /*00000160*/ STRB        R0, [R4, #177]              @ 0xb1 
    /*00000164*/ ADD         R3, R3, #8 
    /*00000168*/ STR         R2, [R4, #184]              @ 0xb8 
    /*0000016c*/ MOV         R0, R4 
    /*00000170*/ STRB        R2, [R4, #176]              @ 0xb0 
    /*00000174*/ STR         R2, [R4, #180]              @ 0xb4 
    /*00000178*/ STR         R2, [R4, #132]              @ 0x84 
    /*0000017c*/ VST1.32     {D16}, [R1] 
    /*00000180*/ STR         R6, [R4, #188]              @ 0xbc 
    /*00000184*/ STR         R3, [R4] 
    /*00000188*/ ADD         SP, SP, #20 
    /*0000018c*/ POP         {R4, R5, R6, R7, PC} 
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x190:
    /*00000190*/ ADD         R0, R0, #100                @ 0x64 
    /*00000194*/ ADD         R1, SP, #12 
    /*00000198*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*0000019c*/ LDR         R3, [SP, #12] 
    /*000001a0*/ STR         R0, [R4, #100]              @ 0x64 
    /*000001a4*/ STR         R3, [R4, #108]              @ 0x6c 
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1a8:
    /*000001a8*/ MOV         R2, R5 
    /*000001ac*/ MOV         R1, R7 
    /*000001b0*/ BL          memcpy
    /*000001b4*/ LDR         R5, [SP, #12] 
    /*000001b8*/ LDR         IP, [R4, #100]              @ 0x64 
    /*000001bc*/ B           _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xec
    /*000001c0*/ LDR         R0, [R4, #88]               @ 0x58 
    /*000001c4*/ CMP         R0, #0 
    /*000001c8*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1d0
    /*000001cc*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1d0:
    /*000001d0*/ LDR         R0, [R4, #76]               @ 0x4c 
    /*000001d4*/ CMP         R0, #0 
    /*000001d8*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1e0
    /*000001dc*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1e0:
    /*000001e0*/ LDR         R1, [R4, #60]               @ 0x3c 
    /*000001e4*/ ADD         R0, R4, #52                 @ 0x34 
    /*000001e8*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001ec*/ LDR         R1, [R4, #36]               @ 0x24 
    /*000001f0*/ ADD         R0, R4, #28 
    /*000001f4*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001f8*/ LDR         R0, [R4, #16] 
    /*000001fc*/ CMP         R0, #0 
    /*00000200*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x208
    /*00000204*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x208:
    /*00000208*/ LDR         R0, [R4, #4] 
    /*0000020c*/ CMP         R0, #0 
    /*00000210*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x218
    /*00000214*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x218:
    /*00000218*/ BL          __cxa_end_cleanup
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x21c:
    /*0000021c*/ MOV         R0, IP 
    /*00000220*/ B           _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1a8
    /*00000224*/ LDR         R0, [R4, #152]              @ 0x98 
    /*00000228*/ CMP         R5, R0 
    /*0000022c*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x234
    /*00000230*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x234:
    /*00000234*/ MOV         R0, R4 
    /*00000238*/ BL          _ZN4hirt9OperationD2Ev
    /*0000023c*/ B           _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x218
    /*00000240*/ WORD_0240: .word 0x0000021c
    /*00000244*/ WORD_0244: .word 0x0000017c
    /*00000248*/ WORD_0248: .word 0x00000144
    /*0000024c*/ WORD_024c: .word 0x00000104
    /*00000250*/ WORD_0250: .word 0x000000ec
FUNC_END _ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE


FUNC_BEGIN _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4056]             @ 0xfd8 
    /*00000010*/ LDR         R3, WORD_0240               @ LDR         R3, [PC, #552]              @ 0x0000000000000240 
    /*00000014*/ ADD         R5, R0, #32 
    /*00000018*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ ADD         LR, R0, #56                 @ 0x38 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ ADD         IP, R0, #108                @ 0x6c 
    /*0000002c*/ STR         R3, [R0] 
    /*00000030*/ MOV         R3, #0 
    /*00000034*/ STR         R3, [R0, #4] 
    /*00000038*/ MOV         R6, R2 
    /*0000003c*/ STR         R3, [R0, #8] 
    /*00000040*/ SUB         SP, SP, #20 
    /*00000044*/ STR         R3, [R0, #12] 
    /*00000048*/ MOV         R4, R0 
    /*0000004c*/ STR         R3, [R0, #16] 
    /*00000050*/ STR         R3, [R0, #20] 
    /*00000054*/ STR         R3, [R0, #24] 
    /*00000058*/ VST1.8      {D16-D17}, [R5] 
    /*0000005c*/ STR         R5, [R0, #40]               @ 0x28 
    /*00000060*/ STR         R5, [R0, #44]               @ 0x2c 
    /*00000064*/ STR         R3, [R0, #48]               @ 0x30 
    /*00000068*/ VST1.8      {D16-D17}, [LR] 
    /*0000006c*/ STR         R3, [R0, #72]               @ 0x48 
    /*00000070*/ LDR         R5, [R1, #4] 
    /*00000074*/ STR         IP, [R0, #100]              @ 0x64 
    /*00000078*/ LDR         R7, [R1] 
    /*0000007c*/ RSB         R1, R5, #0 
    /*00000080*/ SUB         R2, R7, R3 
    /*00000084*/ CLZ         R2, R2 
    /*00000088*/ CMP         R7, R1 
    /*0000008c*/ LSR         R2, R2, #5 
    /*00000090*/ MOVEQ       R2, #0 
    /*00000094*/ CMP         R2, R3 
    /*00000098*/ STR         LR, [R0, #64]               @ 0x40 
    /*0000009c*/ STR         LR, [R0, #68]               @ 0x44 
    /*000000a0*/ STR         R3, [R0, #76]               @ 0x4c 
    /*000000a4*/ STR         R3, [R0, #80]               @ 0x50 
    /*000000a8*/ STR         R3, [R0, #84]               @ 0x54 
    /*000000ac*/ STR         R3, [R0, #88]               @ 0x58 
    /*000000b0*/ STR         R3, [R0, #92]               @ 0x5c 
    /*000000b4*/ STR         R3, [R0, #96]               @ 0x60 
    /*000000b8*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xc8
    /*000000bc*/ LDR         R0, WORD_0244               @ LDR         R0, [PC, #384]              @ 0x0000000000000244 
    /*000000c0*/ ADD         R0, PC, R0 
    /*000000c4*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xc8:
    /*000000c8*/ STR         R5, [SP, #12] 
    /*000000cc*/ CMP         R5, #15 
    /*000000d0*/ BHI         _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x190
    /*000000d4*/ CMP         R5, #1 
    /*000000d8*/ LDRBEQ      R3, [R7] 
    /*000000dc*/ STRBEQ      R3, [R4, #108]              @ 0x6c 
    /*000000e0*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xec
    /*000000e4*/ CMP         R5, #0 
    /*000000e8*/ BNE         _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x21c
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xec:
    /*000000ec*/ LDR         R2, WORD_0248               @ LDR         R2, [PC, #340]              @ 0x0000000000000248 
    /*000000f0*/ MOV         R3, #0 
    /*000000f4*/ STR         R5, [R4, #104]              @ 0x68 
    /*000000f8*/ MOV         R1, R3 
    /*000000fc*/ ADD         R2, PC, R2 
    /*00000100*/ MOV         LR, #3 
    /*00000104*/ STRB        R3, [IP, R5] 
    /*00000108*/ ADD         R2, R2, #8 
    /*0000010c*/ STR         R2, [R4] 
    /*00000110*/ MOV         R2, R3 
    /*00000114*/ STR         R3, [R4, #124]              @ 0x7c 
    /*00000118*/ ADD         R5, R4, #160                @ 0xa0 
    /*0000011c*/ STR         R3, [R4, #128]              @ 0x80 
    /*00000120*/ ADD         R0, R4, #152                @ 0x98 
    /*00000124*/ STR         R3, [R4, #156]              @ 0x9c 
    /*00000128*/ STRB        R3, [R4, #160]              @ 0xa0 
    /*0000012c*/ STR         R3, [R4, #148]              @ 0x94 
    /*00000130*/ STR         R3, [SP] 
    /*00000134*/ LDR         R3, WORD_024c               @ LDR         R3, [PC, #272]              @ 0x000000000000024c 
    /*00000138*/ STR         LR, [R4, #144]              @ 0x90 
    /*0000013c*/ STR         R5, [R4, #152]              @ 0x98 
    /*00000140*/ ADD         R3, PC, R3 
    /*00000144*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEjjPKcj
    /*00000148*/ VMOV.I32    D16, #0                     @ 0x00000000 
    /*0000014c*/ LDR         R3, WORD_0250               @ LDR         R3, [PC, #252]              @ 0x0000000000000250 
    /*00000150*/ ADD         R1, R4, #136                @ 0x88 
    /*00000154*/ MOV         R2, #0 
    /*00000158*/ MOV         R0, #3 
    /*0000015c*/ ADD         R3, PC, R3 
    /*00000160*/ STRB        R0, [R4, #177]              @ 0xb1 
    /*00000164*/ ADD         R3, R3, #8 
    /*00000168*/ STR         R2, [R4, #184]              @ 0xb8 
    /*0000016c*/ MOV         R0, R4 
    /*00000170*/ STRB        R2, [R4, #176]              @ 0xb0 
    /*00000174*/ STR         R2, [R4, #180]              @ 0xb4 
    /*00000178*/ STR         R2, [R4, #132]              @ 0x84 
    /*0000017c*/ VST1.32     {D16}, [R1] 
    /*00000180*/ STR         R6, [R4, #188]              @ 0xbc 
    /*00000184*/ STR         R3, [R4] 
    /*00000188*/ ADD         SP, SP, #20 
    /*0000018c*/ POP         {R4, R5, R6, R7, PC} 
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x190:
    /*00000190*/ ADD         R0, R0, #100                @ 0x64 
    /*00000194*/ ADD         R1, SP, #12 
    /*00000198*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*0000019c*/ LDR         R3, [SP, #12] 
    /*000001a0*/ STR         R0, [R4, #100]              @ 0x64 
    /*000001a4*/ STR         R3, [R4, #108]              @ 0x6c 
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1a8:
    /*000001a8*/ MOV         R2, R5 
    /*000001ac*/ MOV         R1, R7 
    /*000001b0*/ BL          memcpy
    /*000001b4*/ LDR         R5, [SP, #12] 
    /*000001b8*/ LDR         IP, [R4, #100]              @ 0x64 
    /*000001bc*/ B           _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_xec
    /*000001c0*/ LDR         R0, [R4, #88]               @ 0x58 
    /*000001c4*/ CMP         R0, #0 
    /*000001c8*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1d0
    /*000001cc*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1d0:
    /*000001d0*/ LDR         R0, [R4, #76]               @ 0x4c 
    /*000001d4*/ CMP         R0, #0 
    /*000001d8*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1e0
    /*000001dc*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1e0:
    /*000001e0*/ LDR         R1, [R4, #60]               @ 0x3c 
    /*000001e4*/ ADD         R0, R4, #52                 @ 0x34 
    /*000001e8*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001ec*/ LDR         R1, [R4, #36]               @ 0x24 
    /*000001f0*/ ADD         R0, R4, #28 
    /*000001f4*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001f8*/ LDR         R0, [R4, #16] 
    /*000001fc*/ CMP         R0, #0 
    /*00000200*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x208
    /*00000204*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x208:
    /*00000208*/ LDR         R0, [R4, #4] 
    /*0000020c*/ CMP         R0, #0 
    /*00000210*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x218
    /*00000214*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x218:
    /*00000218*/ BL          __cxa_end_cleanup
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x21c:
    /*0000021c*/ MOV         R0, IP 
    /*00000220*/ B           _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x1a8
    /*00000224*/ LDR         R0, [R4, #152]              @ 0x98 
    /*00000228*/ CMP         R5, R0 
    /*0000022c*/ BEQ         _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x234
    /*00000230*/ BL          _ZdlPv
    _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x234:
    /*00000234*/ MOV         R0, R4 
    /*00000238*/ BL          _ZN4hirt9OperationD2Ev
    /*0000023c*/ B           _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE_x218
    /*00000240*/ WORD_0240: .word 0x0000021c
    /*00000244*/ WORD_0244: .word 0x0000017c
    /*00000248*/ WORD_0248: .word 0x00000144
    /*0000024c*/ WORD_024c: .word 0x00000104
    /*00000250*/ WORD_0250: .word 0x000000ec
FUNC_END _ZN4hirt23OperationOfflineRuntimeC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt23OperationOfflineRuntimeC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14OPERATION_TYPEE
@ Size: 0x23
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE
@ Size: 0x238
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4056]             @ 0xfd8 
    /*00000010*/ LDR         R3, WORD_0228               @ LDR         R3, [PC, #528]              @ 0x0000000000000228 
    /*00000014*/ ADD         R5, R0, #32 
    /*00000018*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ ADD         LR, R0, #56                 @ 0x38 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ ADD         IP, R0, #108                @ 0x6c 
    /*0000002c*/ STR         R3, [R0] 
    /*00000030*/ MOV         R3, #0 
    /*00000034*/ STR         R3, [R0, #4] 
    /*00000038*/ MOV         R6, R2 
    /*0000003c*/ STR         R3, [R0, #8] 
    /*00000040*/ SUB         SP, SP, #20 
    /*00000044*/ STR         R3, [R0, #12] 
    /*00000048*/ MOV         R4, R0 
    /*0000004c*/ STR         R3, [R0, #16] 
    /*00000050*/ STR         R3, [R0, #20] 
    /*00000054*/ STR         R3, [R0, #24] 
    /*00000058*/ VST1.8      {D16-D17}, [R5] 
    /*0000005c*/ STR         R5, [R0, #40]               @ 0x28 
    /*00000060*/ STR         R5, [R0, #44]               @ 0x2c 
    /*00000064*/ STR         R3, [R0, #48]               @ 0x30 
    /*00000068*/ VST1.8      {D16-D17}, [LR] 
    /*0000006c*/ STR         R3, [R0, #72]               @ 0x48 
    /*00000070*/ LDR         R5, [R1, #4] 
    /*00000074*/ STR         IP, [R0, #100]              @ 0x64 
    /*00000078*/ LDR         R7, [R1] 
    /*0000007c*/ RSB         R1, R5, #0 
    /*00000080*/ SUB         R2, R7, R3 
    /*00000084*/ CLZ         R2, R2 
    /*00000088*/ CMP         R7, R1 
    /*0000008c*/ LSR         R2, R2, #5 
    /*00000090*/ MOVEQ       R2, #0 
    /*00000094*/ CMP         R2, R3 
    /*00000098*/ STR         LR, [R0, #64]               @ 0x40 
    /*0000009c*/ STR         LR, [R0, #68]               @ 0x44 
    /*000000a0*/ STR         R3, [R0, #76]               @ 0x4c 
    /*000000a4*/ STR         R3, [R0, #80]               @ 0x50 
    /*000000a8*/ STR         R3, [R0, #84]               @ 0x54 
    /*000000ac*/ STR         R3, [R0, #88]               @ 0x58 
    /*000000b0*/ STR         R3, [R0, #92]               @ 0x5c 
    /*000000b4*/ STR         R3, [R0, #96]               @ 0x60 
    /*000000b8*/ BEQ         _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xc8
    /*000000bc*/ LDR         R0, WORD_022c               @ LDR         R0, [PC, #360]              @ 0x000000000000022c 
    /*000000c0*/ ADD         R0, PC, R0 
    /*000000c4*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xc8:
    /*000000c8*/ STR         R5, [SP, #12] 
    /*000000cc*/ CMP         R5, #15 
    /*000000d0*/ BHI         _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x178
    /*000000d4*/ CMP         R5, #1 
    /*000000d8*/ LDRBEQ      R3, [R7] 
    /*000000dc*/ STRBEQ      R3, [R4, #108]              @ 0x6c 
    /*000000e0*/ BEQ         _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xec
    /*000000e4*/ CMP         R5, #0 
    /*000000e8*/ BNE         _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x204
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xec:
    /*000000ec*/ LDR         R2, WORD_0230               @ LDR         R2, [PC, #316]              @ 0x0000000000000230 
    /*000000f0*/ MOV         R3, #0 
    /*000000f4*/ STR         R5, [R4, #104]              @ 0x68 
    /*000000f8*/ MOV         R1, R3 
    /*000000fc*/ ADD         R2, PC, R2 
    /*00000100*/ ADD         R7, R4, #160                @ 0xa0 
    /*00000104*/ STRB        R3, [IP, R5] 
    /*00000108*/ ADD         R2, R2, #8 
    /*0000010c*/ STR         R2, [R4] 
    /*00000110*/ MOV         R2, R3 
    /*00000114*/ STR         R3, [R4, #124]              @ 0x7c 
    /*00000118*/ ADD         R0, R4, #152                @ 0x98 
    /*0000011c*/ STR         R3, [R4, #128]              @ 0x80 
    /*00000120*/ STR         R3, [R4, #156]              @ 0x9c 
    /*00000124*/ STRB        R3, [R4, #160]              @ 0xa0 
    /*00000128*/ STR         R3, [R4, #148]              @ 0x94 
    /*0000012c*/ STR         R3, [SP] 
    /*00000130*/ LDR         R3, WORD_0234               @ LDR         R3, [PC, #252]              @ 0x0000000000000234 
    /*00000134*/ STR         R6, [R4, #144]              @ 0x90 
    /*00000138*/ STR         R7, [R4, #152]              @ 0x98 
    /*0000013c*/ ADD         R3, PC, R3 
    /*00000140*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEjjPKcj
    /*00000144*/ VMOV.I32    D16, #0                     @ 0x00000000 
    /*00000148*/ ADD         R2, R4, #180                @ 0xb4 
    /*0000014c*/ ADD         R3, R4, #136                @ 0x88 
    /*00000150*/ MOV         R1, #0 
    /*00000154*/ MOV         R0, #3 
    /*00000158*/ STRB        R0, [R4, #177]              @ 0xb1 
    /*0000015c*/ MOV         R0, R4 
    /*00000160*/ STRB        R1, [R4, #176]              @ 0xb0 
    /*00000164*/ VST1.32     {D16}, [R2] 
    /*00000168*/ STR         R1, [R4, #132]              @ 0x84 
    /*0000016c*/ VST1.32     {D16}, [R3] 
    /*00000170*/ ADD         SP, SP, #20 
    /*00000174*/ POP         {R4, R5, R6, R7, PC} 
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x178:
    /*00000178*/ ADD         R0, R0, #100                @ 0x64 
    /*0000017c*/ ADD         R1, SP, #12 
    /*00000180*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*00000184*/ LDR         R3, [SP, #12] 
    /*00000188*/ STR         R0, [R4, #100]              @ 0x64 
    /*0000018c*/ STR         R3, [R4, #108]              @ 0x6c 
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x190:
    /*00000190*/ MOV         R2, R5 
    /*00000194*/ MOV         R1, R7 
    /*00000198*/ BL          memcpy
    /*0000019c*/ LDR         R5, [SP, #12] 
    /*000001a0*/ LDR         IP, [R4, #100]              @ 0x64 
    /*000001a4*/ B           _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xec
    /*000001a8*/ LDR         R0, [R4, #88]               @ 0x58 
    /*000001ac*/ CMP         R0, #0 
    /*000001b0*/ BEQ         _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1b8
    /*000001b4*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1b8:
    /*000001b8*/ LDR         R0, [R4, #76]               @ 0x4c 
    /*000001bc*/ CMP         R0, #0 
    /*000001c0*/ BEQ         _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1c8
    /*000001c4*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1c8:
    /*000001c8*/ LDR         R1, [R4, #60]               @ 0x3c 
    /*000001cc*/ ADD         R0, R4, #52                 @ 0x34 
    /*000001d0*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001d4*/ LDR         R1, [R4, #36]               @ 0x24 
    /*000001d8*/ ADD         R0, R4, #28 
    /*000001dc*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001e0*/ LDR         R0, [R4, #16] 
    /*000001e4*/ CMP         R0, #0 
    /*000001e8*/ BEQ         _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1f0
    /*000001ec*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1f0:
    /*000001f0*/ LDR         R0, [R4, #4] 
    /*000001f4*/ CMP         R0, #0 
    /*000001f8*/ BEQ         _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x200
    /*000001fc*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x200:
    /*00000200*/ BL          __cxa_end_cleanup
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x204:
    /*00000204*/ MOV         R0, IP 
    /*00000208*/ B           _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x190
    /*0000020c*/ LDR         R0, [R4, #152]              @ 0x98 
    /*00000210*/ CMP         R7, R0 
    /*00000214*/ BEQ         _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x21c
    /*00000218*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x21c:
    /*0000021c*/ MOV         R0, R4 
    /*00000220*/ BL          _ZN4hirt9OperationD2Ev
    /*00000224*/ B           _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x200
    /*00000228*/ WORD_0228: .word 0x00000204
    /*0000022c*/ WORD_022c: .word 0x00000164
    /*00000230*/ WORD_0230: .word 0x0000012c
    /*00000234*/ WORD_0234: .word 0x000000f0
FUNC_END _ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE


FUNC_BEGIN _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4056]             @ 0xfd8 
    /*00000010*/ LDR         R3, WORD_0228               @ LDR         R3, [PC, #528]              @ 0x0000000000000228 
    /*00000014*/ ADD         R5, R0, #32 
    /*00000018*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ ADD         LR, R0, #56                 @ 0x38 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ ADD         IP, R0, #108                @ 0x6c 
    /*0000002c*/ STR         R3, [R0] 
    /*00000030*/ MOV         R3, #0 
    /*00000034*/ STR         R3, [R0, #4] 
    /*00000038*/ MOV         R6, R2 
    /*0000003c*/ STR         R3, [R0, #8] 
    /*00000040*/ SUB         SP, SP, #20 
    /*00000044*/ STR         R3, [R0, #12] 
    /*00000048*/ MOV         R4, R0 
    /*0000004c*/ STR         R3, [R0, #16] 
    /*00000050*/ STR         R3, [R0, #20] 
    /*00000054*/ STR         R3, [R0, #24] 
    /*00000058*/ VST1.8      {D16-D17}, [R5] 
    /*0000005c*/ STR         R5, [R0, #40]               @ 0x28 
    /*00000060*/ STR         R5, [R0, #44]               @ 0x2c 
    /*00000064*/ STR         R3, [R0, #48]               @ 0x30 
    /*00000068*/ VST1.8      {D16-D17}, [LR] 
    /*0000006c*/ STR         R3, [R0, #72]               @ 0x48 
    /*00000070*/ LDR         R5, [R1, #4] 
    /*00000074*/ STR         IP, [R0, #100]              @ 0x64 
    /*00000078*/ LDR         R7, [R1] 
    /*0000007c*/ RSB         R1, R5, #0 
    /*00000080*/ SUB         R2, R7, R3 
    /*00000084*/ CLZ         R2, R2 
    /*00000088*/ CMP         R7, R1 
    /*0000008c*/ LSR         R2, R2, #5 
    /*00000090*/ MOVEQ       R2, #0 
    /*00000094*/ CMP         R2, R3 
    /*00000098*/ STR         LR, [R0, #64]               @ 0x40 
    /*0000009c*/ STR         LR, [R0, #68]               @ 0x44 
    /*000000a0*/ STR         R3, [R0, #76]               @ 0x4c 
    /*000000a4*/ STR         R3, [R0, #80]               @ 0x50 
    /*000000a8*/ STR         R3, [R0, #84]               @ 0x54 
    /*000000ac*/ STR         R3, [R0, #88]               @ 0x58 
    /*000000b0*/ STR         R3, [R0, #92]               @ 0x5c 
    /*000000b4*/ STR         R3, [R0, #96]               @ 0x60 
    /*000000b8*/ BEQ         _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xc8
    /*000000bc*/ LDR         R0, WORD_022c               @ LDR         R0, [PC, #360]              @ 0x000000000000022c 
    /*000000c0*/ ADD         R0, PC, R0 
    /*000000c4*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xc8:
    /*000000c8*/ STR         R5, [SP, #12] 
    /*000000cc*/ CMP         R5, #15 
    /*000000d0*/ BHI         _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x178
    /*000000d4*/ CMP         R5, #1 
    /*000000d8*/ LDRBEQ      R3, [R7] 
    /*000000dc*/ STRBEQ      R3, [R4, #108]              @ 0x6c 
    /*000000e0*/ BEQ         _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xec
    /*000000e4*/ CMP         R5, #0 
    /*000000e8*/ BNE         _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x204
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xec:
    /*000000ec*/ LDR         R2, WORD_0230               @ LDR         R2, [PC, #316]              @ 0x0000000000000230 
    /*000000f0*/ MOV         R3, #0 
    /*000000f4*/ STR         R5, [R4, #104]              @ 0x68 
    /*000000f8*/ MOV         R1, R3 
    /*000000fc*/ ADD         R2, PC, R2 
    /*00000100*/ ADD         R7, R4, #160                @ 0xa0 
    /*00000104*/ STRB        R3, [IP, R5] 
    /*00000108*/ ADD         R2, R2, #8 
    /*0000010c*/ STR         R2, [R4] 
    /*00000110*/ MOV         R2, R3 
    /*00000114*/ STR         R3, [R4, #124]              @ 0x7c 
    /*00000118*/ ADD         R0, R4, #152                @ 0x98 
    /*0000011c*/ STR         R3, [R4, #128]              @ 0x80 
    /*00000120*/ STR         R3, [R4, #156]              @ 0x9c 
    /*00000124*/ STRB        R3, [R4, #160]              @ 0xa0 
    /*00000128*/ STR         R3, [R4, #148]              @ 0x94 
    /*0000012c*/ STR         R3, [SP] 
    /*00000130*/ LDR         R3, WORD_0234               @ LDR         R3, [PC, #252]              @ 0x0000000000000234 
    /*00000134*/ STR         R6, [R4, #144]              @ 0x90 
    /*00000138*/ STR         R7, [R4, #152]              @ 0x98 
    /*0000013c*/ ADD         R3, PC, R3 
    /*00000140*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_replaceEjjPKcj
    /*00000144*/ VMOV.I32    D16, #0                     @ 0x00000000 
    /*00000148*/ ADD         R2, R4, #180                @ 0xb4 
    /*0000014c*/ ADD         R3, R4, #136                @ 0x88 
    /*00000150*/ MOV         R1, #0 
    /*00000154*/ MOV         R0, #3 
    /*00000158*/ STRB        R0, [R4, #177]              @ 0xb1 
    /*0000015c*/ MOV         R0, R4 
    /*00000160*/ STRB        R1, [R4, #176]              @ 0xb0 
    /*00000164*/ VST1.32     {D16}, [R2] 
    /*00000168*/ STR         R1, [R4, #132]              @ 0x84 
    /*0000016c*/ VST1.32     {D16}, [R3] 
    /*00000170*/ ADD         SP, SP, #20 
    /*00000174*/ POP         {R4, R5, R6, R7, PC} 
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x178:
    /*00000178*/ ADD         R0, R0, #100                @ 0x64 
    /*0000017c*/ ADD         R1, SP, #12 
    /*00000180*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*00000184*/ LDR         R3, [SP, #12] 
    /*00000188*/ STR         R0, [R4, #100]              @ 0x64 
    /*0000018c*/ STR         R3, [R4, #108]              @ 0x6c 
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x190:
    /*00000190*/ MOV         R2, R5 
    /*00000194*/ MOV         R1, R7 
    /*00000198*/ BL          memcpy
    /*0000019c*/ LDR         R5, [SP, #12] 
    /*000001a0*/ LDR         IP, [R4, #100]              @ 0x64 
    /*000001a4*/ B           _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_xec
    /*000001a8*/ LDR         R0, [R4, #88]               @ 0x58 
    /*000001ac*/ CMP         R0, #0 
    /*000001b0*/ BEQ         _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1b8
    /*000001b4*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1b8:
    /*000001b8*/ LDR         R0, [R4, #76]               @ 0x4c 
    /*000001bc*/ CMP         R0, #0 
    /*000001c0*/ BEQ         _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1c8
    /*000001c4*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1c8:
    /*000001c8*/ LDR         R1, [R4, #60]               @ 0x3c 
    /*000001cc*/ ADD         R0, R4, #52                 @ 0x34 
    /*000001d0*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001d4*/ LDR         R1, [R4, #36]               @ 0x24 
    /*000001d8*/ ADD         R0, R4, #28 
    /*000001dc*/ BL          _ZNSt8_Rb_treeIjjSt9_IdentityIjESt4lessIjESaIjEE8_M_eraseEPSt13_Rb_tree_nodeIjE
    /*000001e0*/ LDR         R0, [R4, #16] 
    /*000001e4*/ CMP         R0, #0 
    /*000001e8*/ BEQ         _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1f0
    /*000001ec*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x1f0:
    /*000001f0*/ LDR         R0, [R4, #4] 
    /*000001f4*/ CMP         R0, #0 
    /*000001f8*/ BEQ         _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x200
    /*000001fc*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x200:
    /*00000200*/ BL          __cxa_end_cleanup
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x204:
    /*00000204*/ MOV         R0, IP 
    /*00000208*/ B           _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x190
    /*0000020c*/ LDR         R0, [R4, #152]              @ 0x98 
    /*00000210*/ CMP         R7, R0 
    /*00000214*/ BEQ         _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x21c
    /*00000218*/ BL          _ZdlPv
    _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x21c:
    /*0000021c*/ MOV         R0, R4 
    /*00000220*/ BL          _ZN4hirt9OperationD2Ev
    /*00000224*/ B           _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE_x200
    /*00000228*/ WORD_0228: .word 0x00000204
    /*0000022c*/ WORD_022c: .word 0x00000164
    /*00000230*/ WORD_0230: .word 0x0000012c
    /*00000234*/ WORD_0234: .word 0x000000f0
FUNC_END _ZN4hirt16OperationOfflineC1ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt16OperationOfflineC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_18OPERATION_CLASSIFYE
@ Size: 0x23
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT_
@ Size: 0xd4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT_
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4064]             @ 0xfe0 
    /*00000010*/ LDM         R0, {R2, R3} 
    /*00000014*/ MOV         R6, R0 
    /*00000018*/ MOV         R9, R1 
    /*0000001c*/ SUB         R3, R3, R2 
    /*00000020*/ ASRS        R3, R3, #2 
    /*00000024*/ BEQ         _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x3c
    /*00000028*/ LSL         R5, R3, #1 
    /*0000002c*/ CMP         R3, R5 
    /*00000030*/ BLS         _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__xb8
    _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x34:
    /*00000034*/ MVN         R5, #3 
    /*00000038*/ B           _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x40
    _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x3c:
    /*0000003c*/ MOV         R5, #4 
    _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x40:
    /*00000040*/ MOV         R0, R5 
    /*00000044*/ BL          _Znwj
    /*00000048*/ MOV         R7, R0 
    _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x4c:
    /*0000004c*/ LDR         R8, [R6] 
    /*00000050*/ LDR         R4, [R6, #4] 
    /*00000054*/ LDR         R2, [R9] 
    /*00000058*/ SUB         R4, R4, R8 
    /*0000005c*/ CMN         R7, R4 
    /*00000060*/ ASR         R3, R4, #2 
    /*00000064*/ STRNE       R2, [R7, R4] 
    /*00000068*/ CMP         R3, #0 
    /*0000006c*/ BNE         _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x9c
    /*00000070*/ CMP         R8, #0 
    /*00000074*/ ADD         R4, R4, #4 
    /*00000078*/ ADD         R4, R7, R4 
    /*0000007c*/ BEQ         _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x88
    _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x80:
    /*00000080*/ MOV         R0, R8 
    /*00000084*/ BL          _ZdlPv
    _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x88:
    /*00000088*/ ADD         R5, R7, R5 
    /*0000008c*/ STR         R5, [R6, #8] 
    /*00000090*/ STR         R7, [R6] 
    /*00000094*/ STR         R4, [R6, #4] 
    /*00000098*/ POP         {R4, R5, R6, R7, R8, R9, SL, PC} 
    _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x9c:
    /*0000009c*/ MOV         R2, R4 
    /*000000a0*/ MOV         R1, R8 
    /*000000a4*/ MOV         R0, R7 
    /*000000a8*/ ADD         R4, R4, #4 
    /*000000ac*/ ADD         R4, R7, R4 
    /*000000b0*/ BL          memmove
    /*000000b4*/ B           _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x80
    _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__xb8:
    /*000000b8*/ CMN         R5, #-1073741823            @ 0xc0000001 
    /*000000bc*/ BHI         _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x34
    /*000000c0*/ CMP         R5, #0 
    /*000000c4*/ LSLNE       R5, R3, #3 
    /*000000c8*/ BNE         _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x40
    /*000000cc*/ MOV         R7, R5 
    /*000000d0*/ B           _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT__x4c
FUNC_END _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT_


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt16OperationOffline8addInputEPNS_7OperandE
@ Size: 0x74
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt16OperationOffline8addInputEPNS_7OperandE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4072]             @ 0xfe8 
    /*00000010*/ MOV         R5, R0 
    /*00000014*/ SUB         SP, SP, #12 
    /*00000018*/ MOV         R0, R1 
    /*0000001c*/ MOV         R4, R1 
    /*00000020*/ BL          _ZN4hirt14OperandOffline17increaseReferenceEv
    /*00000024*/ LDR         R3, [R5, #8] 
    /*00000028*/ LDR         R2, [R5, #12] 
    /*0000002c*/ STR         R4, [SP, #4] 
    /*00000030*/ CMP         R3, R2 
    /*00000034*/ BEQ         _ZN4hirt16OperationOffline8addInputEPNS_7OperandE_x60
    /*00000038*/ CMP         R3, #0 
    /*0000003c*/ ADD         R3, R3, #4 
    /*00000040*/ STRNE       R4, [R3, #-4] 
    /*00000044*/ LDRNE       R4, [SP, #4] 
    /*00000048*/ STR         R3, [R5, #8] 
    _ZN4hirt16OperationOffline8addInputEPNS_7OperandE_x4c:
    /*0000004c*/ MOV         R1, R5 
    /*00000050*/ MOV         R0, R4 
    /*00000054*/ BL          _ZN4hirt7Operand11addConsumerERNS_9OperationE
    /*00000058*/ ADD         SP, SP, #12 
    /*0000005c*/ POP         {R4, R5, PC} 
    _ZN4hirt16OperationOffline8addInputEPNS_7OperandE_x60:
    /*00000060*/ ADD         R1, SP, #4 
    /*00000064*/ ADD         R0, R5, #4 
    /*00000068*/ BL          _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT_
    /*0000006c*/ LDR         R4, [SP, #4] 
    /*00000070*/ B           _ZN4hirt16OperationOffline8addInputEPNS_7OperandE_x4c
FUNC_END _ZN4hirt16OperationOffline8addInputEPNS_7OperandE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt9Operation8addInputEPNS_7OperandE
@ Size: 0x68
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt9Operation8addInputEPNS_7OperandE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ LDR         R3, [R0, #8] 
    /*00000014*/ SUB         SP, SP, #8 
    /*00000018*/ LDR         R2, [R0, #12] 
    /*0000001c*/ MOV         R4, R0 
    /*00000020*/ STR         R1, [SP, #4] 
    /*00000024*/ CMP         R3, R2 
    /*00000028*/ BEQ         _ZN4hirt9Operation8addInputEPNS_7OperandE_x54
    /*0000002c*/ CMP         R3, #0 
    /*00000030*/ MOV         R0, R1 
    /*00000034*/ STRNE       R1, [R3] 
    /*00000038*/ ADD         R3, R3, #4 
    /*0000003c*/ LDRNE       R0, [SP, #4] 
    /*00000040*/ STR         R3, [R4, #8] 
    _ZN4hirt9Operation8addInputEPNS_7OperandE_x44:
    /*00000044*/ MOV         R1, R4 
    /*00000048*/ BL          _ZN4hirt7Operand11addConsumerERNS_9OperationE
    /*0000004c*/ ADD         SP, SP, #8 
    /*00000050*/ POP         {R4, PC} 
    _ZN4hirt9Operation8addInputEPNS_7OperandE_x54:
    /*00000054*/ ADD         R0, R0, #4 
    /*00000058*/ ADD         R1, SP, #4 
    /*0000005c*/ BL          _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT_
    /*00000060*/ LDR         R0, [SP, #4] 
    /*00000064*/ B           _ZN4hirt9Operation8addInputEPNS_7OperandE_x44
FUNC_END _ZN4hirt9Operation8addInputEPNS_7OperandE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt9Operation9addOutputEPNS_7OperandE
@ Size: 0x68
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt9Operation9addOutputEPNS_7OperandE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ LDR         R3, [R0, #20] 
    /*00000014*/ SUB         SP, SP, #8 
    /*00000018*/ LDR         R2, [R0, #24] 
    /*0000001c*/ MOV         R4, R0 
    /*00000020*/ STR         R1, [SP, #4] 
    /*00000024*/ CMP         R3, R2 
    /*00000028*/ BEQ         _ZN4hirt9Operation9addOutputEPNS_7OperandE_x54
    /*0000002c*/ CMP         R3, #0 
    /*00000030*/ MOV         R0, R1 
    /*00000034*/ STRNE       R1, [R3] 
    /*00000038*/ ADD         R3, R3, #4 
    /*0000003c*/ LDRNE       R0, [SP, #4] 
    /*00000040*/ STR         R3, [R4, #20] 
    _ZN4hirt9Operation9addOutputEPNS_7OperandE_x44:
    /*00000044*/ MOV         R1, R4 
    /*00000048*/ BL          _ZN4hirt7Operand11addProducerERNS_9OperationE
    /*0000004c*/ ADD         SP, SP, #8 
    /*00000050*/ POP         {R4, PC} 
    _ZN4hirt9Operation9addOutputEPNS_7OperandE_x54:
    /*00000054*/ ADD         R0, R0, #16 
    /*00000058*/ ADD         R1, SP, #4 
    /*0000005c*/ BL          _ZNSt6vectorIPN4hirt7OperandESaIS2_EE19_M_emplace_back_auxIJRKS2_EEEvDpOT_
    /*00000060*/ LDR         R0, [SP, #4] 
    /*00000064*/ B           _ZN4hirt9Operation9addOutputEPNS_7OperandE_x44
FUNC_END _ZN4hirt9Operation9addOutputEPNS_7OperandE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text.startup._GLOBAL__sub_I_hi_operation.cpp
@ Size: 0x54
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _GLOBAL__sub_I_hi_operation.cpp
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ LDR         R4, WORD_0044               @ LDR         R4, [PC, #44]               @ 0x0000000000000044 
    /*00000014*/ LDR         R5, WORD_0048               @ LDR         R5, [PC, #44]               @ 0x0000000000000048 
    /*00000018*/ ADD         R4, PC, R4 
    /*0000001c*/ ADD         R5, PC, R5 
    /*00000020*/ MOV         R0, R4 
    /*00000024*/ BL          _ZNSt8ios_base4InitC1Ev
    /*00000028*/ LDR         R3, WORD_004c               @ LDR         R3, [PC, #28]               @ 0x000000000000004c 
    /*0000002c*/ MOV         R0, R4 
    /*00000030*/ LDR         R2, WORD_0050               @ LDR         R2, [PC, #24]               @ 0x0000000000000050 
    /*00000034*/ LDR         R1, [R5, R3] 
    /*00000038*/ ADD         R2, PC, R2 
    /*0000003c*/ POP         {R4, R5, R6, LR} 
    _GLOBAL__sub_I_hi_operation.cpp_x40:
    /*00000040*/ B           _GLOBAL__sub_I_hi_operation.cpp_x40@ __aeabi_atexit [R_ARM_JUMP24: +0x0] 
    /*00000044*/ WORD_0044: .word 0x00000024
    /*00000048*/ WORD_0048: .word 0x00000024
    /*0000004c*/ WORD_004c: .word 0x00000000
    /*00000050*/ WORD_0050: .word 0x00000010
FUNC_END _GLOBAL__sub_I_hi_operation.cpp


