@
@ -- FILES --
@

@ NNIEThread.cpp


unsigned char data[0] = {
};

unsigned char bss[0];

_RODATA__ZTSNST6THREAD11_STATE_IMPLIST12_BIND_SIMPLEIFST7_MEM_FNIMN4HIRT13RUNNINGTHREADEFIPNS3_17_NNIESCHEDULQUEUEEPST5MUTEXEEPNS3_10NNIETHREADES6_S8_EEEE_0000: .ascii "NSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEEE\0"


unsigned char data.rel.ro._ZTINSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEEE[12] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTINSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEEE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0xc4, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0xc2, 0x00, 0x00, 
    /*0010*/ 0x08, 0x00, 0x00, 0x00, 0x02, 0xc5, 0x00, 0x00, 
};

unsigned char data.rel.ro._ZTVNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEEE[20] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTVNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEEE[32] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0xc3, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0x93, 0x00, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0x94, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0xb6, 0x00, 0x00, 
};

unsigned char bss._ZN4hirt10NNIEThread12mStartedNNIEE[8];

unsigned char bss._ZN4hirt10NNIEThread15mModelTaskArrayE[8];

unsigned char bss._ZN4hirt10NNIEThread15mModelTaskMutexE[24];

unsigned char bss._ZStL8__ioinit[1];

unsigned char data.rel.ro._ZTIN4hirt10NNIEThreadE[12] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt10NNIEThreadE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0xc4, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0xc0, 0x00, 0x00, 
    /*0010*/ 0x08, 0x00, 0x00, 0x00, 0x02, 0xcd, 0x00, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt10NNIEThreadE[52] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0020*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0030*/ 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt10NNIEThreadE[96] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0xc1, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0xba, 0x00, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0xbb, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0xa1, 0x00, 0x00, 
    /*0020*/ 0x14, 0x00, 0x00, 0x00, 0x02, 0x96, 0x00, 0x00, 0x18, 0x00, 0x00, 0x00, 0x02, 0x8d, 0x00, 0x00, 
    /*0030*/ 0x1c, 0x00, 0x00, 0x00, 0x02, 0x99, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x02, 0x8e, 0x00, 0x00, 
    /*0040*/ 0x24, 0x00, 0x00, 0x00, 0x02, 0x9b, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00, 0x02, 0xb1, 0x00, 0x00, 
    /*0050*/ 0x2c, 0x00, 0x00, 0x00, 0x02, 0xb7, 0x00, 0x00, 0x30, 0x00, 0x00, 0x00, 0x02, 0x9d, 0x00, 0x00, 
};

_RODATA__ZN4HIRT10NNIETHREAD25DEALSEGTIMEFORUSERATEPROCEP8TIMESPECS2__STR1_4_0000: .ascii "%s:[%d] copy timespec start error\0\0\0",
_RODATA__ZN4HIRT10NNIETHREAD25DEALSEGTIMEFORUSERATEPROCEP8TIMESPECS2__STR1_4_0024: .ascii "%s:[%d] copy timespec end error\0",
_RODATA__ZN4HIRT10NNIETHREAD25DEALSEGTIMEFORUSERATEPROCEP8TIMESPECS2__STR1_4_0044: .ascii ""


_RODATA__ZN4HIRT10NNIETHREAD5STARTEV_STR1_4_0000: .ascii "nnie %d is already started\0\0",
_RODATA__ZN4HIRT10NNIETHREAD5STARTEV_STR1_4_001c: .ascii "hirt\0\0\0\0",
_RODATA__ZN4HIRT10NNIETHREAD5STARTEV_STR1_4_0024: .ascii "NNIE\0"


_RODATA__ZTSN4HIRT10NNIETHREADE_0000: .ascii "N4hirt10NNIEThreadE\0",
_RODATA__ZTSN4HIRT10NNIETHREADE_0014: .ascii ""


_RODATA__ZZN4HIRT10NNIETHREAD25DEALSEGTIMEFORUSERATEPROCEP8TIMESPECS2_E12__FUNCTION___0000: .ascii "dealSegTimeForUseRateProc\0"


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThread10preprocessEv
@ Size: 0x4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThread10preprocessEv
    /*00000000*/ BX          LR 
FUNC_END _ZN4hirt10NNIEThread10preprocessEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThread14getDeviceIndexEv
@ Size: 0x8
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThread14getDeviceIndexEv
    /*00000000*/ LDR         R0, [R0, #8] 
    /*00000004*/ BX          LR 
FUNC_END _ZN4hirt10NNIEThread14getDeviceIndexEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEED2Ev
@ Size: 0x40
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEED2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0038               @ LDR         R3, [PC, #32]               @ 0x0000000000000038 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_003c               @ LDR         R2, [PC, #28]               @ 0x000000000000003c 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R3, [R3, R2] 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R0] 
    /*0000002c*/ BL          _ZNSt6thread6_StateD2Ev
    /*00000030*/ MOV         R0, R4 
    /*00000034*/ POP         {R4, PC} 
    /*00000038*/ WORD_0038: .word 0x00000014
    /*0000003c*/ WORD_003c: .word 0x00000000
FUNC_END _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEED2Ev


FUNC_BEGIN _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEED1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0038               @ LDR         R3, [PC, #32]               @ 0x0000000000000038 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_003c               @ LDR         R2, [PC, #28]               @ 0x000000000000003c 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R3, [R3, R2] 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R0] 
    /*0000002c*/ BL          _ZNSt6thread6_StateD2Ev
    /*00000030*/ MOV         R0, R4 
    /*00000034*/ POP         {R4, PC} 
    /*00000038*/ WORD_0038: .word 0x00000014
    /*0000003c*/ WORD_003c: .word 0x00000000
FUNC_END _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEED1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEED0Ev
@ Size: 0x4c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEED0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0044               @ LDR         R3, [PC, #44]               @ 0x0000000000000044 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_0048               @ LDR         R2, [PC, #40]               @ 0x0000000000000048 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R3, [R3, R2] 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R0] 
    /*0000002c*/ BL          _ZNSt6thread6_StateD2Ev
    /*00000030*/ MOV         R0, R4 
    /*00000034*/ MOV         R1, #24 
    /*00000038*/ BL          _ZdlPvj
    /*0000003c*/ MOV         R0, R4 
    /*00000040*/ POP         {R4, PC} 
    /*00000044*/ WORD_0044: .word 0x00000020
    /*00000048*/ WORD_0048: .word 0x00000000
FUNC_END _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEED0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThread4stopEv
@ Size: 0x34
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThread4stopEv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ MOV         R4, R0 
    /*00000014*/ BL          _ZN4hirt13RunningThread4stopEv
    /*00000018*/ LDR         R3, WORD_0030               @ LDR         R3, [PC, #16]               @ 0x0000000000000030 
    /*0000001c*/ MOV         R1, #0 
    /*00000020*/ LDR         R2, [R4, #8] 
    /*00000024*/ ADD         R3, PC, R3 
    /*00000028*/ STR         R1, [R3, R2, LSL #2] 
    /*0000002c*/ POP         {R4, PC} 
    /*00000030*/ WORD_0030: .word 0x00000004
FUNC_END _ZN4hirt10NNIEThread4stopEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThread13waitTaskReadyEv
@ Size: 0x4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThread13waitTaskReadyEv
    _ZN4hirt10NNIEThread13waitTaskReadyEv_x0:
    /*00000000*/ B           _ZN4hirt10NNIEThread13waitTaskReadyEv_x0@ _ZN4hirt11TaskMonitor21waitLockNNIETaskReadyEv [R_ARM_JUMP24: +0x0] 
FUNC_END _ZN4hirt10NNIEThread13waitTaskReadyEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThread17setLeftSegNumProcEj
@ Size: 0x20
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThread17setLeftSegNumProcEj
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ MOV         R4, R1 
    /*00000014*/ BL          _ZN4hirt11ProcManager11getInstanceEv
    /*00000018*/ STR         R4, [R0, #56]               @ 0x38 
    /*0000001c*/ POP         {R4, PC} 
FUNC_END _ZN4hirt10NNIEThread17setLeftSegNumProcEj


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThread13handleSegTaskEPNS_7SegTaskE
@ Size: 0xd8
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThread13handleSegTaskEPNS_7SegTaskE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ LDR         R3, [R1, #100]              @ 0x64 
    /*00000014*/ MOV         R4, R1 
    /*00000018*/ LDR         R5, WORD_00c4               @ LDR         R5, [PC, #164]              @ 0x00000000000000c4 
    /*0000001c*/ LDR         R3, [R3, #24] 
    /*00000020*/ ADD         R5, PC, R5 
    /*00000024*/ CMP         R3, #0 
    /*00000028*/ BEQ         _ZN4hirt10NNIEThread13handleSegTaskEPNS_7SegTaskE_x8c
    /*0000002c*/ MOV         R6, R0 
    /*00000030*/ BL          _ZN4hirt16TaskGroupManager11getInstanceEv
    /*00000034*/ MOV         R1, R4 
    /*00000038*/ LDR         R2, [R6, #8] 
    /*0000003c*/ BL          _ZN4hirt16TaskGroupManager14computeNnieSegEPNS_11NnieSegTaskEj
    /*00000040*/ LDR         R3, WORD_00c8               @ LDR         R3, [PC, #128]              @ 0x00000000000000c8 
    /*00000044*/ MOV         R4, R0 
    /*00000048*/ LDR         R3, [R5, R3] 
    /*0000004c*/ CMP         R3, #0 
    /*00000050*/ BEQ         _ZN4hirt10NNIEThread13handleSegTaskEPNS_7SegTaskE_xa8
    /*00000054*/ LDR         R5, WORD_00cc               @ LDR         R5, [PC, #112]              @ 0x00000000000000cc 
    /*00000058*/ ADD         R5, PC, R5 
    /*0000005c*/ MOV         R0, R5 
    /*00000060*/ BL          pthread_mutex_lock
    /*00000064*/ SUBS        R1, R0, #0 
    /*00000068*/ BNE         _ZN4hirt10NNIEThread13handleSegTaskEPNS_7SegTaskE_xc0
    /*0000006c*/ LDR         R3, WORD_00d0               @ LDR         R3, [PC, #92]               @ 0x00000000000000d0 
    /*00000070*/ MOV         R0, R5 
    /*00000074*/ LDR         R2, [R6, #8] 
    /*00000078*/ ADD         R3, PC, R3 
    /*0000007c*/ STR         R1, [R3, R2, LSL #2] 
    /*00000080*/ BL          pthread_mutex_unlock
    /*00000084*/ MOV         R0, R4 
    /*00000088*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt10NNIEThread13handleSegTaskEPNS_7SegTaskE_x8c:
    /*0000008c*/ LDR         R2, [R1] 
    /*00000090*/ MOV         R0, R1 
    /*00000094*/ MOV         R4, R3 
    /*00000098*/ LDR         R2, [R2, #12] 
    /*0000009c*/ BLX         R2 
    /*000000a0*/ MOV         R0, R4 
    /*000000a4*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt10NNIEThread13handleSegTaskEPNS_7SegTaskE_xa8:
    /*000000a8*/ LDR         R2, WORD_00d4               @ LDR         R2, [PC, #36]               @ 0x00000000000000d4 
    /*000000ac*/ MOV         R0, R4 
    /*000000b0*/ LDR         R1, [R6, #8] 
    /*000000b4*/ ADD         R2, PC, R2 
    /*000000b8*/ STR         R3, [R2, R1, LSL #2] 
    /*000000bc*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt10NNIEThread13handleSegTaskEPNS_7SegTaskE_xc0:
    /*000000c0*/ BL          _ZSt20__throw_system_errori
    /*000000c4*/ WORD_00c4: .word 0x0000009c
    /*000000c8*/ WORD_00c8: .word 0x00000000
    /*000000cc*/ WORD_00cc: .word 0x0000006c
    /*000000d0*/ WORD_00d0: .word 0x00000050
    /*000000d4*/ WORD_00d4: .word 0x00000018
FUNC_END _ZN4hirt10NNIEThread13handleSegTaskEPNS_7SegTaskE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThread5startEv
@ Size: 0x1b0
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThread5startEv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4064]             @ 0xfe0 
    /*00000010*/ LDR         IP, WORD_0180               @ LDR         IP, [PC, #360]              @ 0x0000000000000180 
    /*00000014*/ SUB         SP, SP, #8 
    /*00000018*/ LDR         R1, [R0, #8] 
    /*0000001c*/ ADD         IP, PC, IP 
    /*00000020*/ LDR         R4, WORD_0184               @ LDR         R4, [PC, #348]              @ 0x0000000000000184 
    /*00000024*/ LDR         R7, [IP, R1, LSL #2] 
    /*00000028*/ ADD         R4, PC, R4 
    /*0000002c*/ CMP         R7, #0 
    /*00000030*/ BNE         _ZN4hirt10NNIEThread5startEv_x12c
    /*00000034*/ LDR         R2, WORD_0188               @ LDR         R2, [PC, #332]              @ 0x0000000000000188 
    /*00000038*/ MOV         R6, R0 
    /*0000003c*/ LDR         R3, WORD_018c               @ LDR         R3, [PC, #328]              @ 0x000000000000018c 
    /*00000040*/ MOV         R0, #1 
    /*00000044*/ LDR         R2, [R4, R2] 
    /*00000048*/ STR         R0, [IP, R1, LSL #2] 
    /*0000004c*/ MOV         R0, #4 
    /*00000050*/ STR         R7, [R2] 
    /*00000054*/ LDR         R8, [R4, R3] 
    /*00000058*/ MOV         R1, R8 
    /*0000005c*/ BL          _ZnwjRKSt9nothrow_t
    /*00000060*/ SUBS        R5, R0, #0 
    /*00000064*/ BEQ         _ZN4hirt10NNIEThread5startEv_xe8
    /*00000068*/ STR         R7, [R5] 
    /*0000006c*/ MOV         R0, #24 
    /*00000070*/ BL          _Znwj
    /*00000074*/ LDR         R2, WORD_0190               @ LDR         R2, [PC, #276]              @ 0x0000000000000190 
    /*00000078*/ MOV         R3, R0 
    /*0000007c*/ LDR         IP, WORD_0194               @ LDR         IP, [PC, #272]              @ 0x0000000000000194 
    /*00000080*/ ADD         R1, SP, #8 
    /*00000084*/ LDR         LR, [R4, R2] 
    /*00000088*/ MOV         R0, R5 
    /*0000008c*/ LDR         R2, WORD_0198               @ LDR         R2, [PC, #260]              @ 0x0000000000000198 
    /*00000090*/ ADD         LR, LR, #8 
    /*00000094*/ STR         LR, [R3] 
    /*00000098*/ LDR         IP, [R4, IP] 
    /*0000009c*/ STR         IP, [R3, #4] 
    /*000000a0*/ LDR         IP, [R4, R2] 
    /*000000a4*/ LDR         R2, WORD_019c               @ LDR         R2, [PC, #240]              @ 0x000000000000019c 
    /*000000a8*/ STR         IP, [R3, #8] 
    /*000000ac*/ MOV         IP, #0 
    /*000000b0*/ STR         R6, [R3, #12] 
    /*000000b4*/ LDR         R2, [R4, R2] 
    /*000000b8*/ STR         IP, [R3, #20] 
    /*000000bc*/ STR         R2, [R3, #16] 
    /*000000c0*/ LDR         R2, WORD_01a0               @ LDR         R2, [PC, #216]              @ 0x00000000000001a0 
    /*000000c4*/ STR         R3, [R1, #-4]! 
    /*000000c8*/ LDR         R2, [R4, R2] 
    /*000000cc*/ BL          _ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE
    /*000000d0*/ LDR         R0, [SP, #4] 
    /*000000d4*/ CMP         R0, #0 
    /*000000d8*/ BEQ         _ZN4hirt10NNIEThread5startEv_xe8
    /*000000dc*/ LDR         R3, [R0] 
    /*000000e0*/ LDR         R3, [R3, #4] 
    /*000000e4*/ BLX         R3 
    _ZN4hirt10NNIEThread5startEv_xe8:
    /*000000e8*/ LDR         R0, [R6, #4] 
    /*000000ec*/ STR         R5, [R6, #4] 
    /*000000f0*/ CMP         R0, #0 
    /*000000f4*/ BEQ         _ZN4hirt10NNIEThread5startEv_x110
    /*000000f8*/ LDR         R3, [R0] 
    /*000000fc*/ CMP         R3, #0 
    /*00000100*/ BNE         _ZN4hirt10NNIEThread5startEv_x150
    /*00000104*/ MOV         R1, #4 
    /*00000108*/ BL          _ZdlPvj
    /*0000010c*/ LDR         R5, [R6, #4] 
    _ZN4hirt10NNIEThread5startEv_x110:
    /*00000110*/ LDR         R1, WORD_01a4               @ LDR         R1, [PC, #140]              @ 0x00000000000001a4 
    /*00000114*/ LDR         R0, [R5] 
    /*00000118*/ ADD         R1, PC, R1 
    /*0000011c*/ BL          pthread_setname_np
    /*00000120*/ MOV         R0, #0 
    _ZN4hirt10NNIEThread5startEv_x124:
    /*00000124*/ ADD         SP, SP, #8 
    /*00000128*/ POP         {R4, R5, R6, R7, R8, PC} 
    _ZN4hirt10NNIEThread5startEv_x12c:
    /*0000012c*/ LDR         R2, WORD_01a8               @ LDR         R2, [PC, #116]              @ 0x00000000000001a8 
    /*00000130*/ MOV         R3, R1 
    /*00000134*/ LDR         R0, WORD_01ac               @ LDR         R0, [PC, #112]              @ 0x00000000000001ac 
    /*00000138*/ MOV         R1, #4 
    /*0000013c*/ ADD         R2, PC, R2 
    /*00000140*/ ADD         R0, PC, R0 
    /*00000144*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000148*/ MVN         R0, #0 
    /*0000014c*/ B           _ZN4hirt10NNIEThread5startEv_x124
    _ZN4hirt10NNIEThread5startEv_x150:
    /*00000150*/ BL          _ZSt9terminatev
    /*00000154*/ LDR         R0, [SP, #4] 
    /*00000158*/ CMP         R0, #0 
    /*0000015c*/ BEQ         _ZN4hirt10NNIEThread5startEv_x16c
    /*00000160*/ LDR         R3, [R0] 
    /*00000164*/ LDR         R3, [R3, #4] 
    /*00000168*/ BLX         R3 
    _ZN4hirt10NNIEThread5startEv_x16c:
    /*0000016c*/ MOV         R1, R8 
    /*00000170*/ MOV         R0, R5 
    /*00000174*/ BL          _ZdlPvRKSt9nothrow_t
    /*00000178*/ BL          __cxa_end_cleanup
    /*0000017c*/ B           _ZN4hirt10NNIEThread5startEv_x16c
    /*00000180*/ WORD_0180: .word 0x0000015c
    /*00000184*/ WORD_0184: .word 0x00000154
    /*00000188*/ WORD_0188: .word 0x00000000
    /*0000018c*/ WORD_018c: .word 0x00000000
    /*00000190*/ WORD_0190: .word 0x00000000
    /*00000194*/ WORD_0194: .word 0x00000000
    /*00000198*/ WORD_0198: .word 0x00000000
    /*0000019c*/ WORD_019c: .word 0x00000000
    /*000001a0*/ WORD_01a0: .word 0x00000000
    /*000001a4*/ WORD_01a4: .word 0x00000084
    /*000001a8*/ WORD_01a8: .word 0x00000064
    /*000001ac*/ WORD_01ac: .word 0x00000064
FUNC_END _ZN4hirt10NNIEThread5startEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt10NNIEThread5startEv
@ Size: 0x1c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2_
@ Size: 0x140
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2_
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4056]             @ 0xfd8 
    /*00000010*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*00000014*/ SUB         SP, SP, #24 
    /*00000018*/ MOV         R3, #8 
    /*0000001c*/ ADD         R4, SP, #8 
    /*00000020*/ MOV         R6, R2 
    /*00000024*/ MOV         R5, R0 
    /*00000028*/ MOV         R2, R1 
    /*0000002c*/ MOV         R0, R4 
    /*00000030*/ MOV         R1, R3 
    /*00000034*/ VST1.8      {D16-D17}, [R4 :64] 
    /*00000038*/ BL          memcpy_s
    /*0000003c*/ CMP         R0, #0 
    /*00000040*/ BNE         _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__x100
    _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__x44:
    /*00000044*/ MOV         R3, #8 
    /*00000048*/ MOV         R2, R6 
    /*0000004c*/ MOV         R1, R3 
    /*00000050*/ ADD         R0, SP, #16 
    /*00000054*/ BL          memcpy_s
    /*00000058*/ CMP         R0, #0 
    /*0000005c*/ BNE         _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__xd8
    _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__x60:
    /*00000060*/ BL          _ZN4hirt11ProcManager11getInstanceEv
    /*00000064*/ LDR         R2, [R5, #8] 
    /*00000068*/ MOV         R3, #12 
    /*0000006c*/ ADD         R0, R0, #64                 @ 0x40 
    /*00000070*/ MUL         R3, R3, R2 
    /*00000074*/ ADD         R5, R0, R3 
    /*00000078*/ LDR         R2, [R5, #8] 
    /*0000007c*/ CMP         R2, #20 
    /*00000080*/ BLS         _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__xa0
    /*00000084*/ LDR         R6, [R0, R3] 
    /*00000088*/ SUB         R2, R2, #1 
    /*0000008c*/ STR         R2, [R5, #8] 
    /*00000090*/ MOV         R0, R6 
    /*00000094*/ BL          _ZNSt8__detail15_List_node_base9_M_unhookEv
    /*00000098*/ MOV         R0, R6 
    /*0000009c*/ BL          _ZdlPv
    _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__xa0:
    /*000000a0*/ MOV         R0, #24 
    /*000000a4*/ BL          _Znwj
    /*000000a8*/ MOV         LR, R0 
    /*000000ac*/ LDM         R4, {R0, R1, R2, R3} 
    /*000000b0*/ ADD         IP, LR, #8 
    /*000000b4*/ STM         IP, {R0, R1, R2, R3} 
    /*000000b8*/ MOV         R0, LR 
    /*000000bc*/ MOV         R1, R5 
    /*000000c0*/ BL          _ZNSt8__detail15_List_node_base7_M_hookEPS0_
    /*000000c4*/ LDR         R3, [R5, #8] 
    /*000000c8*/ ADD         R3, R3, #1 
    /*000000cc*/ STR         R3, [R5, #8] 
    /*000000d0*/ ADD         SP, SP, #24 
    /*000000d4*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__xd8:
    /*000000d8*/ STR         R0, [SP] 
    /*000000dc*/ MOV         R1, #4 
    /*000000e0*/ LDR         R3, WORD_0128               @ LDR         R3, [PC, #64]               @ 0x0000000000000128 
    /*000000e4*/ LDR         R2, WORD_012c               @ LDR         R2, [PC, #64]               @ 0x000000000000012c 
    /*000000e8*/ LDR         R0, WORD_0130               @ LDR         R0, [PC, #64]               @ 0x0000000000000130 
    /*000000ec*/ ADD         R3, PC, R3 
    /*000000f0*/ ADD         R2, PC, R2 
    /*000000f4*/ ADD         R0, PC, R0 
    /*000000f8*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000000fc*/ B           _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__x60
    _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__x100:
    /*00000100*/ STR         R0, [SP] 
    /*00000104*/ MOV         R1, #4 
    /*00000108*/ LDR         R3, WORD_0134               @ LDR         R3, [PC, #36]               @ 0x0000000000000134 
    /*0000010c*/ LDR         R2, WORD_0138               @ LDR         R2, [PC, #36]               @ 0x0000000000000138 
    /*00000110*/ LDR         R0, WORD_013c               @ LDR         R0, [PC, #36]               @ 0x000000000000013c 
    /*00000114*/ ADD         R3, PC, R3 
    /*00000118*/ ADD         R2, PC, R2 
    /*0000011c*/ ADD         R0, PC, R0 
    /*00000120*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000124*/ B           _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2__x44
    /*00000128*/ WORD_0128: .word 0x00000034
    /*0000012c*/ WORD_012c: .word 0x00000034
    /*00000130*/ WORD_0130: .word 0x00000034
    /*00000134*/ WORD_0134: .word 0x00000018
    /*00000138*/ WORD_0138: .word 0x00000018
    /*0000013c*/ WORD_013c: .word 0x00000018
FUNC_END _ZN4hirt10NNIEThread25dealSegTimeForUseRateProcEP8timespecS2_


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEE6_M_runEv
@ Size: 0x38
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEE6_M_runEv
    /*00000000*/ PUSH        {R4, LR} 
    /*00000004*/ LDR         IP, [R0, #20] 
    /*00000008*/ LDR         R3, [R0, #12] 
    /*0000000c*/ LDR         LR, [R0, #16] 
    /*00000010*/ TST         IP, #1 
    /*00000014*/ LDR         R1, [R0, #8] 
    /*00000018*/ LDRNE       R4, [R3, IP, ASR #1] 
    /*0000001c*/ LDR         R2, [R0, #4] 
    /*00000020*/ LDRNE       LR, [R4, LR] 
    /*00000024*/ ADDEQ       R0, R3, IP, ASR #1 
    /*00000028*/ ADDNE       R0, R3, IP, ASR #1 
    /*0000002c*/ MOV         R3, LR 
    /*00000030*/ POP         {R4, LR} 
    /*00000034*/ BX          R3 
FUNC_END _ZNSt6thread11_State_implISt12_Bind_simpleIFSt7_Mem_fnIMN4hirt13RunningThreadEFiPNS3_17_NnieSchedulQueueEPSt5mutexEEPNS3_10NNIEThreadES6_S8_EEE6_M_runEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE
@ Size: 0xf4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ LDR         R3, WORD_00d4               @ LDR         R3, [PC, #188]              @ 0x00000000000000d4 
    /*00000014*/ MOV         R5, R0 
    /*00000018*/ LDR         R2, WORD_00d8               @ LDR         R2, [PC, #184]              @ 0x00000000000000d8 
    /*0000001c*/ MOV         R6, R1 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ LDR         R4, [R3, R2] 
    /*00000028*/ CMP         R4, #0 
    /*0000002c*/ BEQ         _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_x44
    /*00000030*/ LDR         R0, WORD_00dc               @ LDR         R0, [PC, #164]              @ 0x00000000000000dc 
    /*00000034*/ ADD         R0, PC, R0 
    /*00000038*/ BL          pthread_mutex_lock
    /*0000003c*/ CMP         R0, #0 
    /*00000040*/ BNE         _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xd0
    _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_x44:
    /*00000044*/ LDR         R2, [R5, #8] 
    /*00000048*/ CMP         R2, #0 
    /*0000004c*/ BEQ         _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xac
    /*00000050*/ LDR         R3, WORD_00e0               @ LDR         R3, [PC, #136]              @ 0x00000000000000e0 
    /*00000054*/ LDR         R1, [R6, #88]               @ 0x58 
    /*00000058*/ ADD         R3, PC, R3 
    /*0000005c*/ LDR         R3, [R3] 
    /*00000060*/ CMP         R1, R3 
    /*00000064*/ BEQ         _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xb4
    /*00000068*/ CMP         R2, #1 
    /*0000006c*/ BEQ         _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_x84
    _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_x70:
    /*00000070*/ LDR         R3, WORD_00e4               @ LDR         R3, [PC, #108]              @ 0x00000000000000e4 
    /*00000074*/ ADD         R3, PC, R3 
    /*00000078*/ LDR         R3, [R3, #4] 
    /*0000007c*/ CMP         R1, R3 
    /*00000080*/ BEQ         _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xb4
    _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_x84:
    /*00000084*/ LDR         R3, WORD_00e8               @ LDR         R3, [PC, #92]               @ 0x00000000000000e8 
    /*00000088*/ CMP         R4, #0 
    /*0000008c*/ ADD         R3, PC, R3 
    /*00000090*/ STR         R1, [R3, R2, LSL #2] 
    /*00000094*/ BEQ         _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xa4
    /*00000098*/ LDR         R0, WORD_00ec               @ LDR         R0, [PC, #76]               @ 0x00000000000000ec 
    /*0000009c*/ ADD         R0, PC, R0 
    /*000000a0*/ BL          pthread_mutex_unlock
    _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xa4:
    /*000000a4*/ MOV         R0, #1 
    /*000000a8*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xac:
    /*000000ac*/ LDR         R1, [R6, #88]               @ 0x58 
    /*000000b0*/ B           _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_x70
    _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xb4:
    /*000000b4*/ CMP         R4, #0 
    /*000000b8*/ BEQ         _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xc8
    /*000000bc*/ LDR         R0, WORD_00f0               @ LDR         R0, [PC, #44]               @ 0x00000000000000f0 
    /*000000c0*/ ADD         R0, PC, R0 
    /*000000c4*/ BL          pthread_mutex_unlock
    _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xc8:
    /*000000c8*/ MOV         R0, #0 
    /*000000cc*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE_xd0:
    /*000000d0*/ BL          _ZSt20__throw_system_errori
    /*000000d4*/ WORD_00d4: .word 0x000000ac
    /*000000d8*/ WORD_00d8: .word 0x00000000
    /*000000dc*/ WORD_00dc: .word 0x000000a0
    /*000000e0*/ WORD_00e0: .word 0x00000080
    /*000000e4*/ WORD_00e4: .word 0x00000068
    /*000000e8*/ WORD_00e8: .word 0x00000054
    /*000000ec*/ WORD_00ec: .word 0x00000048
    /*000000f0*/ WORD_00f0: .word 0x00000028
FUNC_END _ZN4hirt10NNIEThread16canHandleSegTaskEPKNS_7SegTaskE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThreadD2Ev
@ Size: 0x60
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThreadD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0058               @ LDR         R3, [PC, #64]               @ 0x0000000000000058 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_005c               @ LDR         R2, [PC, #60]               @ 0x000000000000005c 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R0, [R0, #4] 
    /*00000024*/ LDR         R3, [R3, R2] 
    /*00000028*/ CMP         R0, #0 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ STR         R3, [R4] 
    /*00000034*/ BEQ         _ZN4hirt10NNIEThreadD2Ev_x4c
    /*00000038*/ LDR         R3, [R0] 
    /*0000003c*/ CMP         R3, #0 
    /*00000040*/ BNE         _ZN4hirt10NNIEThreadD2Ev_x54
    /*00000044*/ MOV         R1, #4 
    /*00000048*/ BL          _ZdlPvj
    _ZN4hirt10NNIEThreadD2Ev_x4c:
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ POP         {R4, PC} 
    _ZN4hirt10NNIEThreadD2Ev_x54:
    /*00000054*/ BL          _ZSt9terminatev
    /*00000058*/ WORD_0058: .word 0x00000034
    /*0000005c*/ WORD_005c: .word 0x00000000
FUNC_END _ZN4hirt10NNIEThreadD2Ev


FUNC_BEGIN _ZN4hirt10NNIEThreadD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0058               @ LDR         R3, [PC, #64]               @ 0x0000000000000058 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_005c               @ LDR         R2, [PC, #60]               @ 0x000000000000005c 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R0, [R0, #4] 
    /*00000024*/ LDR         R3, [R3, R2] 
    /*00000028*/ CMP         R0, #0 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ STR         R3, [R4] 
    /*00000034*/ BEQ         _ZN4hirt10NNIEThreadD1Ev_x4c
    /*00000038*/ LDR         R3, [R0] 
    /*0000003c*/ CMP         R3, #0 
    /*00000040*/ BNE         _ZN4hirt10NNIEThreadD1Ev_x54
    /*00000044*/ MOV         R1, #4 
    /*00000048*/ BL          _ZdlPvj
    _ZN4hirt10NNIEThreadD1Ev_x4c:
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ POP         {R4, PC} 
    _ZN4hirt10NNIEThreadD1Ev_x54:
    /*00000054*/ BL          _ZSt9terminatev
    /*00000058*/ WORD_0058: .word 0x00000034
    /*0000005c*/ WORD_005c: .word 0x00000000
FUNC_END _ZN4hirt10NNIEThreadD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10NNIEThreadD0Ev
@ Size: 0x6c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10NNIEThreadD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0064               @ LDR         R3, [PC, #76]               @ 0x0000000000000064 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R2, WORD_0068               @ LDR         R2, [PC, #72]               @ 0x0000000000000068 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ LDR         R0, [R0, #4] 
    /*00000024*/ LDR         R3, [R3, R2] 
    /*00000028*/ CMP         R0, #0 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ STR         R3, [R4] 
    /*00000034*/ BEQ         _ZN4hirt10NNIEThreadD0Ev_x4c
    /*00000038*/ LDR         R3, [R0] 
    /*0000003c*/ CMP         R3, #0 
    /*00000040*/ BNE         _ZN4hirt10NNIEThreadD0Ev_x60
    /*00000044*/ MOV         R1, #4 
    /*00000048*/ BL          _ZdlPvj
    _ZN4hirt10NNIEThreadD0Ev_x4c:
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ MOV         R1, #12 
    /*00000054*/ BL          _ZdlPvj
    /*00000058*/ MOV         R0, R4 
    /*0000005c*/ POP         {R4, PC} 
    _ZN4hirt10NNIEThreadD0Ev_x60:
    /*00000060*/ BL          _ZSt9terminatev
    /*00000064*/ WORD_0064: .word 0x00000040
    /*00000068*/ WORD_0068: .word 0x00000000
FUNC_END _ZN4hirt10NNIEThreadD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text.startup._GLOBAL__sub_I_NNIEThread.cpp
@ Size: 0x54
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _GLOBAL__sub_I_NNIEThread.cpp
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ LDR         R4, WORD_0044               @ LDR         R4, [PC, #44]               @ 0x0000000000000044 
    /*00000014*/ LDR         R5, WORD_0048               @ LDR         R5, [PC, #44]               @ 0x0000000000000048 
    /*00000018*/ ADD         R4, PC, R4 
    /*0000001c*/ ADD         R5, PC, R5 
    /*00000020*/ MOV         R0, R4 
    /*00000024*/ BL          _ZNSt8ios_base4InitC1Ev
    /*00000028*/ LDR         R3, WORD_004c               @ LDR         R3, [PC, #28]               @ 0x000000000000004c 
    /*0000002c*/ MOV         R0, R4 
    /*00000030*/ LDR         R2, WORD_0050               @ LDR         R2, [PC, #24]               @ 0x0000000000000050 
    /*00000034*/ LDR         R1, [R5, R3] 
    /*00000038*/ ADD         R2, PC, R2 
    /*0000003c*/ POP         {R4, R5, R6, LR} 
    _GLOBAL__sub_I_NNIEThread.cpp_x40:
    /*00000040*/ B           _GLOBAL__sub_I_NNIEThread.cpp_x40@ __aeabi_atexit [R_ARM_JUMP24: +0x0] 
    /*00000044*/ WORD_0044: .word 0x00000024
    /*00000048*/ WORD_0048: .word 0x00000024
    /*0000004c*/ WORD_004c: .word 0x00000000
    /*00000050*/ WORD_0050: .word 0x00000010
FUNC_END _GLOBAL__sub_I_NNIEThread.cpp


