@
@ -- FILES --
@

@ ProcManager.cpp


unsigned char data[0] = {
};

unsigned char bss[0];

unsigned char bss._ZGVZN4hirt11ProcManager11getInstanceEvE9mInstance[4];

unsigned char bss._ZN4hirt11ProcManager6mMutexE[24];

unsigned char bss._ZStL8__ioinit[1];

unsigned char bss._ZZN4hirt11ProcManager11getInstanceEvE9mInstance[104];

unsigned char data._ZL11acEntryName[10] = {
    /*0000*/ 0x74, 0x61, 0x73, 0x6b, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char data._ZL9acDirName[10] = {
    /*0000*/ 0x73, 0x76, 0x70, 0x72, 0x74, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char data.rel.ro._ZTIN4hirt11ProcManagerE[8] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt11ProcManagerE[16] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0xb1, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0xaa, 0x00, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt11ProcManagerE[16] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt11ProcManagerE[24] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0xab, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0x95, 0x00, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0x96, 0x00, 0x00, 
};

_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_0000: .ascii "NNIE\0\0\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_0008: .ascii "CPU\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_000c: .ascii "Left Seg Num Info\n\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_0020: .ascii "==========================================================================================\n\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_007c: .ascii "Left Unready Seg Num: %d\n\0\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_0098: .ascii "Left Ready Seg Num On NNIE: %d\n\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_00b8: .ascii "Left Ready Seg Num On CPU: %d\n\n\n\0\0\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_00dc: .ascii "NNIE_%d Cost Time / Total Cost Time / Use Rate\n\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_010c: .ascii "no any data\n\n\n\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_011c: .ascii "%lld\t\t/%lld\t\t/%%%d\n\n\n\0\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_0134: .ascii "GroupName\t\t\tPicIdent\tGroupTaskAddr\tFrameId\t\tSegInfo\n\0\0\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_016c: .ascii "TaskShowInfo error\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_0180: .ascii "%-*.*s\t%lld\t\t%p\t%lld\t\t\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_0198: .ascii "\n\0\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_019c: .ascii "\t\t\t\t\t\t\t\t\t\t\0\0",
_RODATA__ZL12TASKSHOWINFOP20HIPROC_SHOW_BUFFER_SPV_STR1_4_01a8: .ascii "%s(%lld, %s_%d)\n\0"


_RODATA__ZN4HIRT11PROCMANAGER16ADDTASKPROCENTRYEV_STR1_4_0000: .ascii "add proc entry error\0"


_RODATA__ZN4HIRT11PROCMANAGER8INITPROCEV_STR1_4_0000: .ascii "add proc dir error\0\0",
_RODATA__ZN4HIRT11PROCMANAGER8INITPROCEV_STR1_4_0014: .ascii "hirt\0"


_RODATA__ZN4HIRT11PROCMANAGERC2EV_STR1_4_0000: .ascii "%s:[%d] clear task entry error\n\0",
_RODATA__ZN4HIRT11PROCMANAGERC2EV_STR1_4_0020: .ascii "%s:[%d] clear left seg num error\n\0"


_RODATA__ZTSN4HIRT11PROCMANAGERE_0000: .ascii "N4hirt11ProcManagerE\0"


_RODATA__ZZN4HIRT11PROCMANAGERC4EVE12__FUNCTION___0000: .ascii "ProcManager\0",
_RODATA__ZZN4HIRT11PROCMANAGERC4EVE12__FUNCTION___000c: .ascii ""


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11ProcManager8initProcEv
@ Size: 0x74
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11ProcManager8initProcEv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ MOV         R4, R0 
    /*00000014*/ BL          HI_PROC_Init
    /*00000018*/ CMP         R0, #0 
    /*0000001c*/ BNE         _ZN4hirt11ProcManager8initProcEv_x64
    /*00000020*/ LDR         R0, [R4, #100]              @ 0x64 
    /*00000024*/ BL          HI_PROC_AddDir
    /*00000028*/ SUBS        R5, R0, #0 
    /*0000002c*/ MOVEQ       R3, #1 
    /*00000030*/ STREQ       R3, [R4, #76]               @ 0x4c 
    /*00000034*/ BNE         _ZN4hirt11ProcManager8initProcEv_x40
    _ZN4hirt11ProcManager8initProcEv_x38:
    /*00000038*/ MOV         R0, R5 
    /*0000003c*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt11ProcManager8initProcEv_x40:
    /*00000040*/ LDR         R2, WORD_006c               @ LDR         R2, [PC, #36]               @ 0x000000000000006c 
    /*00000044*/ MOV         R1, #4 
    /*00000048*/ LDR         R0, WORD_0070               @ LDR         R0, [PC, #32]               @ 0x0000000000000070 
    /*0000004c*/ ADD         R2, PC, R2 
    /*00000050*/ ADD         R0, PC, R0 
    /*00000054*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000058*/ BL          HI_PROC_DeInit
    /*0000005c*/ MOV         R0, R5 
    /*00000060*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt11ProcManager8initProcEv_x64:
    /*00000064*/ MVN         R5, #0 
    /*00000068*/ B           _ZN4hirt11ProcManager8initProcEv_x38
    /*0000006c*/ WORD_006c: .word 0x00000018
    /*00000070*/ WORD_0070: .word 0x00000018
FUNC_END _ZN4hirt11ProcManager8initProcEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11ProcManager10deinitProcEv
@ Size: 0x38
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11ProcManager10deinitProcEv
    /*00000000*/ LDR         R3, [R0, #76]               @ 0x4c 
    /*00000004*/ CMP         R3, #0 
    /*00000008*/ BNE         _ZN4hirt11ProcManager10deinitProcEv_x14
    /*0000000c*/ MOV         R0, #0 
    /*00000010*/ BX          LR 
    _ZN4hirt11ProcManager10deinitProcEv_x14:
    /*00000014*/ MOV         IP, #16384                  @ 0x4000 
    /*00000018*/ PUSH        {R4, LR} 
    /*0000001c*/ SUB         IP, SP, IP 
    /*00000020*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000024*/ LDR         R0, [R0, #100]              @ 0x64 
    /*00000028*/ BL          HI_PROC_RemoveDir
    /*0000002c*/ BL          HI_PROC_DeInit
    /*00000030*/ MOV         R0, #0 
    /*00000034*/ POP         {R4, PC} 
FUNC_END _ZN4hirt11ProcManager10deinitProcEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11ProcManager16addTaskProcEntryEv
@ Size: 0xa4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11ProcManager16addTaskProcEntryEv
    /*00000000*/ LDR         R3, [R0, #76]               @ 0x4c 
    /*00000004*/ CMP         R3, #0 
    /*00000008*/ BNE         _ZN4hirt11ProcManager16addTaskProcEntryEv_x14
    /*0000000c*/ MOV         R0, #0 
    /*00000010*/ BX          LR 
    _ZN4hirt11ProcManager16addTaskProcEntryEv_x14:
    /*00000014*/ MOV         IP, #16384                  @ 0x4000 
    /*00000018*/ PUSH        {R4, LR} 
    /*0000001c*/ SUB         IP, SP, IP 
    /*00000020*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000024*/ LDR         IP, WORD_0094               @ LDR         IP, [PC, #104]              @ 0x0000000000000094 
    /*00000028*/ MOV         R3, R0 
    /*0000002c*/ LDR         R2, WORD_0098               @ LDR         R2, [PC, #100]              @ 0x0000000000000098 
    /*00000030*/ MOV         R4, #0 
    /*00000034*/ LDR         R0, [R0, #100]              @ 0x64 
    /*00000038*/ ADD         LR, R3, #28 
    /*0000003c*/ ADD         IP, PC, IP 
    /*00000040*/ ADD         R1, R3, #80                 @ 0x50 
    /*00000044*/ ADD         R2, PC, R2 
    /*00000048*/ STR         R0, [R3, #84]               @ 0x54 
    /*0000004c*/ MOV         R0, #192                    @ 0xc0 
    /*00000050*/ STR         IP, [R3, #80]               @ 0x50 
    /*00000054*/ STR         R2, [R3, #88]               @ 0x58 
    /*00000058*/ STR         R4, [R3, #92]               @ 0x5c 
    /*0000005c*/ STR         LR, [R3, #96]               @ 0x60 
    /*00000060*/ BL          HI_PROC_AddEntry
    /*00000064*/ CMP         R0, R4 
    /*00000068*/ BNE         _ZN4hirt11ProcManager16addTaskProcEntryEv_x74
    /*0000006c*/ MOV         R0, #0 
    /*00000070*/ POP         {R4, PC} 
    _ZN4hirt11ProcManager16addTaskProcEntryEv_x74:
    /*00000074*/ LDR         R2, WORD_009c               @ LDR         R2, [PC, #32]               @ 0x000000000000009c 
    /*00000078*/ MOV         R1, #4 
    /*0000007c*/ LDR         R0, WORD_00a0               @ LDR         R0, [PC, #28]               @ 0x00000000000000a0 
    /*00000080*/ ADD         R2, PC, R2 
    /*00000084*/ ADD         R0, PC, R0 
    /*00000088*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*0000008c*/ MVN         R0, #0 
    /*00000090*/ POP         {R4, PC} 
    /*00000094*/ WORD_0094: .word 0x00000050
    /*00000098*/ WORD_0098: .word 0x0000004c
    /*0000009c*/ WORD_009c: .word 0x00000014
    /*000000a0*/ WORD_00a0: .word 0x00000014
FUNC_END _ZN4hirt11ProcManager16addTaskProcEntryEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11ProcManager19removeTaskProcEntryEv
@ Size: 0x20
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11ProcManager19removeTaskProcEntryEv
    /*00000000*/ LDR         R3, [R0, #76]               @ 0x4c 
    /*00000004*/ CMP         R3, #0 
    /*00000008*/ BNE         _ZN4hirt11ProcManager19removeTaskProcEntryEv_x14
    /*0000000c*/ MOV         R0, R3 
    /*00000010*/ BX          LR 
    _ZN4hirt11ProcManager19removeTaskProcEntryEv_x14:
    /*00000014*/ ADD         R1, R0, #80                 @ 0x50 
    /*00000018*/ MOV         R0, #192                    @ 0xc0 
    _ZN4hirt11ProcManager19removeTaskProcEntryEv_x1c:
    /*0000001c*/ B           _ZN4hirt11ProcManager19removeTaskProcEntryEv_x1c@ HI_PROC_RemoveEntry [R_ARM_JUMP24: +0x0] 
FUNC_END _ZN4hirt11ProcManager19removeTaskProcEntryEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E
@ Size: 0x2e0
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4032]             @ 0xfc0 
    /*00000010*/ SUB         SP, SP, #28 
    /*00000014*/ SUBS        R3, R1, #0 
    /*00000018*/ STR         R3, [SP, #20] 
    /*0000001c*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x2d8
    /*00000020*/ MOV         R7, R0 
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x24:
    /*00000024*/ LDR         R3, [R3, #12] 
    /*00000028*/ CMP         R3, #0 
    /*0000002c*/ STRNE       R3, [SP, #16] 
    /*00000030*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x294
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x34:
    /*00000034*/ LDR         R3, [R3, #12] 
    /*00000038*/ CMP         R3, #0 
    /*0000003c*/ STRNE       R3, [SP, #12] 
    /*00000040*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x250
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x44:
    /*00000044*/ LDR         R3, [R3, #12] 
    /*00000048*/ CMP         R3, #0 
    /*0000004c*/ STRNE       R3, [SP, #8] 
    /*00000050*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x20c
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x54:
    /*00000054*/ LDR         R9, [R3, #12] 
    /*00000058*/ CMP         R9, #0 
    /*0000005c*/ STRNE       R9, [SP, #4] 
    /*00000060*/ MOVNE       R3, R9 
    /*00000064*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1cc
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x68:
    /*00000068*/ LDR         R9, [R3, #12] 
    /*0000006c*/ CMP         R9, #0 
    /*00000070*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x188
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x74:
    /*00000074*/ LDR         SL, [R9, #12] 
    /*00000078*/ CMP         SL, #0 
    /*0000007c*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x14c
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x80:
    /*00000080*/ LDR         R8, [SL, #12] 
    /*00000084*/ CMP         R8, #0 
    /*00000088*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x114
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x8c:
    /*0000008c*/ LDR         R5, [R8, #12] 
    /*00000090*/ CMP         R5, #0 
    /*00000094*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_xdc
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x98:
    /*00000098*/ LDR         R1, [R5, #12] 
    /*0000009c*/ MOV         R4, R5 
    /*000000a0*/ MOV         R0, R7 
    /*000000a4*/ BL          _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E
    /*000000a8*/ LDR         R0, [R4, #24]! 
    /*000000ac*/ LDR         R6, [R5, #8] 
    /*000000b0*/ CMP         R0, R4 
    /*000000b4*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_xcc
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_xb8:
    /*000000b8*/ LDR         FP, [R0] 
    /*000000bc*/ BL          _ZdlPv
    /*000000c0*/ CMP         FP, R4 
    /*000000c4*/ MOV         R0, FP 
    /*000000c8*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_xb8
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_xcc:
    /*000000cc*/ MOV         R0, R5 
    /*000000d0*/ BL          _ZdlPv
    /*000000d4*/ SUBS        R5, R6, #0 
    /*000000d8*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x98
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_xdc:
    /*000000dc*/ LDR         R6, [R8, #8] 
    /*000000e0*/ MOV         R5, R8 
    /*000000e4*/ LDR         R0, [R5, #24]! 
    /*000000e8*/ CMP         R0, R5 
    /*000000ec*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x104
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_xf0:
    /*000000f0*/ LDR         R4, [R0] 
    /*000000f4*/ BL          _ZdlPv
    /*000000f8*/ CMP         R4, R5 
    /*000000fc*/ MOV         R0, R4 
    /*00000100*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_xf0
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x104:
    /*00000104*/ MOV         R0, R8 
    /*00000108*/ BL          _ZdlPv
    /*0000010c*/ SUBS        R8, R6, #0 
    /*00000110*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x8c
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x114:
    /*00000114*/ LDR         R6, [SL, #8] 
    /*00000118*/ MOV         R5, SL 
    /*0000011c*/ LDR         R0, [R5, #24]! 
    /*00000120*/ CMP         R0, R5 
    /*00000124*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x13c
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x128:
    /*00000128*/ LDR         R4, [R0] 
    /*0000012c*/ BL          _ZdlPv
    /*00000130*/ CMP         R4, R5 
    /*00000134*/ MOV         R0, R4 
    /*00000138*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x128
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x13c:
    /*0000013c*/ MOV         R0, SL 
    /*00000140*/ BL          _ZdlPv
    /*00000144*/ SUBS        SL, R6, #0 
    /*00000148*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x80
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x14c:
    /*0000014c*/ LDR         R5, [R9, #8] 
    /*00000150*/ MOV         R4, R9 
    /*00000154*/ LDR         R0, [R4, #24]! 
    /*00000158*/ CMP         R0, R4 
    /*0000015c*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x174
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x160:
    /*00000160*/ LDR         R6, [R0] 
    /*00000164*/ BL          _ZdlPv
    /*00000168*/ CMP         R6, R4 
    /*0000016c*/ MOV         R0, R6 
    /*00000170*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x160
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x174:
    /*00000174*/ MOV         R0, R9 
    /*00000178*/ BL          _ZdlPv
    /*0000017c*/ SUBS        R9, R5, #0 
    /*00000180*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x74
    /*00000184*/ LDR         R3, [SP, #4] 
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x188:
    /*00000188*/ LDR         R5, [R3, #8] 
    /*0000018c*/ MOV         R4, R3 
    /*00000190*/ LDR         R0, [R4, #24]! 
    /*00000194*/ CMP         R4, R0 
    /*00000198*/ MOVEQ       R0, R3 
    /*0000019c*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1b8
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1a0:
    /*000001a0*/ LDR         R6, [R0] 
    /*000001a4*/ BL          _ZdlPv
    /*000001a8*/ CMP         R4, R6 
    /*000001ac*/ MOV         R0, R6 
    /*000001b0*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1a0
    /*000001b4*/ LDR         R0, [SP, #4] 
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1b8:
    /*000001b8*/ BL          _ZdlPv
    /*000001bc*/ SUBS        R3, R5, #0 
    /*000001c0*/ STR         R3, [SP, #4] 
    /*000001c4*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x68
    /*000001c8*/ LDR         R3, [SP, #8] 
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1cc:
    /*000001cc*/ LDR         R5, [R3, #8] 
    /*000001d0*/ MOV         R4, R3 
    /*000001d4*/ LDR         R0, [R4, #24]! 
    /*000001d8*/ CMP         R0, R4 
    /*000001dc*/ MOVEQ       R0, R3 
    /*000001e0*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1fc
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1e4:
    /*000001e4*/ LDR         R6, [R0] 
    /*000001e8*/ BL          _ZdlPv
    /*000001ec*/ CMP         R6, R4 
    /*000001f0*/ MOV         R0, R6 
    /*000001f4*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1e4
    /*000001f8*/ LDR         R0, [SP, #8] 
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x1fc:
    /*000001fc*/ BL          _ZdlPv
    /*00000200*/ SUBS        R3, R5, #0 
    /*00000204*/ STR         R3, [SP, #8] 
    /*00000208*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x54
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x20c:
    /*0000020c*/ LDR         R3, [SP, #12] 
    /*00000210*/ LDR         R5, [R3, #8] 
    /*00000214*/ MOV         R4, R3 
    /*00000218*/ LDR         R0, [R4, #24]! 
    /*0000021c*/ CMP         R0, R4 
    /*00000220*/ MOVEQ       R0, R3 
    /*00000224*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x240
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x228:
    /*00000228*/ LDR         R6, [R0] 
    /*0000022c*/ BL          _ZdlPv
    /*00000230*/ CMP         R6, R4 
    /*00000234*/ MOV         R0, R6 
    /*00000238*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x228
    /*0000023c*/ LDR         R0, [SP, #12] 
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x240:
    /*00000240*/ BL          _ZdlPv
    /*00000244*/ SUBS        R3, R5, #0 
    /*00000248*/ STR         R3, [SP, #12] 
    /*0000024c*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x44
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x250:
    /*00000250*/ LDR         R3, [SP, #16] 
    /*00000254*/ LDR         R5, [R3, #8] 
    /*00000258*/ MOV         R4, R3 
    /*0000025c*/ LDR         R0, [R4, #24]! 
    /*00000260*/ CMP         R0, R4 
    /*00000264*/ MOVEQ       R0, R3 
    /*00000268*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x284
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x26c:
    /*0000026c*/ LDR         R6, [R0] 
    /*00000270*/ BL          _ZdlPv
    /*00000274*/ CMP         R6, R4 
    /*00000278*/ MOV         R0, R6 
    /*0000027c*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x26c
    /*00000280*/ LDR         R0, [SP, #16] 
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x284:
    /*00000284*/ BL          _ZdlPv
    /*00000288*/ SUBS        R3, R5, #0 
    /*0000028c*/ STR         R3, [SP, #16] 
    /*00000290*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x34
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x294:
    /*00000294*/ LDR         R3, [SP, #20] 
    /*00000298*/ LDR         R5, [R3, #8] 
    /*0000029c*/ MOV         R4, R3 
    /*000002a0*/ LDR         R0, [R4, #24]! 
    /*000002a4*/ CMP         R0, R4 
    /*000002a8*/ MOVEQ       R0, R3 
    /*000002ac*/ BEQ         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x2c8
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x2b0:
    /*000002b0*/ LDR         R6, [R0] 
    /*000002b4*/ BL          _ZdlPv
    /*000002b8*/ CMP         R6, R4 
    /*000002bc*/ MOV         R0, R6 
    /*000002c0*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x2b0
    /*000002c4*/ LDR         R0, [SP, #20] 
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x2c8:
    /*000002c8*/ BL          _ZdlPv
    /*000002cc*/ SUBS        R3, R5, #0 
    /*000002d0*/ STR         R3, [SP, #20] 
    /*000002d4*/ BNE         _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x24
    _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E_x2d8:
    /*000002d8*/ ADD         SP, SP, #28 
    /*000002dc*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
FUNC_END _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11ProcManagerD2Ev
@ Size: 0xbc
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11ProcManagerD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4064]             @ 0xfe0 
    /*00000010*/ LDR         R3, WORD_00b8               @ LDR         R3, [PC, #160]              @ 0x00000000000000b8 
    /*00000014*/ ADD         R9, R0, #64                 @ 0x40 
    /*00000018*/ MOV         R6, R0 
    /*0000001c*/ MOV         R7, R0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ MOV         R5, R9 
    /*00000028*/ ADD         R8, R0, #76                 @ 0x4c 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ STR         R3, [R6], #28 
    _ZN4hirt11ProcManagerD2Ev_x34:
    /*00000034*/ LDR         R0, [R8, #-12]! 
    /*00000038*/ CMP         R0, R5 
    /*0000003c*/ BEQ         _ZN4hirt11ProcManagerD2Ev_x54
    _ZN4hirt11ProcManagerD2Ev_x40:
    /*00000040*/ LDR         R4, [R0] 
    /*00000044*/ BL          _ZdlPv
    /*00000048*/ CMP         R4, R5 
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ BNE         _ZN4hirt11ProcManagerD2Ev_x40
    _ZN4hirt11ProcManagerD2Ev_x54:
    /*00000054*/ CMP         R9, R8 
    /*00000058*/ SUB         R5, R5, #12 
    /*0000005c*/ BNE         _ZN4hirt11ProcManagerD2Ev_x34
    /*00000060*/ LDR         R8, [R7, #36]               @ 0x24 
    /*00000064*/ CMP         R8, #0 
    /*00000068*/ BEQ         _ZN4hirt11ProcManagerD2Ev_xb0
    _ZN4hirt11ProcManagerD2Ev_x6c:
    /*0000006c*/ LDR         R1, [R8, #12] 
    /*00000070*/ MOV         R5, R8 
    /*00000074*/ MOV         R0, R6 
    /*00000078*/ BL          _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E
    /*0000007c*/ LDR         R0, [R5, #24]! 
    /*00000080*/ LDR         R9, [R8, #8] 
    /*00000084*/ CMP         R0, R5 
    /*00000088*/ BEQ         _ZN4hirt11ProcManagerD2Ev_xa0
    _ZN4hirt11ProcManagerD2Ev_x8c:
    /*0000008c*/ LDR         R4, [R0] 
    /*00000090*/ BL          _ZdlPv
    /*00000094*/ CMP         R4, R5 
    /*00000098*/ MOV         R0, R4 
    /*0000009c*/ BNE         _ZN4hirt11ProcManagerD2Ev_x8c
    _ZN4hirt11ProcManagerD2Ev_xa0:
    /*000000a0*/ MOV         R0, R8 
    /*000000a4*/ BL          _ZdlPv
    /*000000a8*/ SUBS        R8, R9, #0 
    /*000000ac*/ BNE         _ZN4hirt11ProcManagerD2Ev_x6c
    _ZN4hirt11ProcManagerD2Ev_xb0:
    /*000000b0*/ MOV         R0, R7 
    /*000000b4*/ POP         {R4, R5, R6, R7, R8, R9, SL, PC} 
    /*000000b8*/ WORD_00b8: .word 0x00000090
FUNC_END _ZN4hirt11ProcManagerD2Ev


FUNC_BEGIN _ZN4hirt11ProcManagerD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4064]             @ 0xfe0 
    /*00000010*/ LDR         R3, WORD_00b8               @ LDR         R3, [PC, #160]              @ 0x00000000000000b8 
    /*00000014*/ ADD         R9, R0, #64                 @ 0x40 
    /*00000018*/ MOV         R6, R0 
    /*0000001c*/ MOV         R7, R0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ MOV         R5, R9 
    /*00000028*/ ADD         R8, R0, #76                 @ 0x4c 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ STR         R3, [R6], #28 
    _ZN4hirt11ProcManagerD1Ev_x34:
    /*00000034*/ LDR         R0, [R8, #-12]! 
    /*00000038*/ CMP         R0, R5 
    /*0000003c*/ BEQ         _ZN4hirt11ProcManagerD1Ev_x54
    _ZN4hirt11ProcManagerD1Ev_x40:
    /*00000040*/ LDR         R4, [R0] 
    /*00000044*/ BL          _ZdlPv
    /*00000048*/ CMP         R4, R5 
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ BNE         _ZN4hirt11ProcManagerD1Ev_x40
    _ZN4hirt11ProcManagerD1Ev_x54:
    /*00000054*/ CMP         R9, R8 
    /*00000058*/ SUB         R5, R5, #12 
    /*0000005c*/ BNE         _ZN4hirt11ProcManagerD1Ev_x34
    /*00000060*/ LDR         R8, [R7, #36]               @ 0x24 
    /*00000064*/ CMP         R8, #0 
    /*00000068*/ BEQ         _ZN4hirt11ProcManagerD1Ev_xb0
    _ZN4hirt11ProcManagerD1Ev_x6c:
    /*0000006c*/ LDR         R1, [R8, #12] 
    /*00000070*/ MOV         R5, R8 
    /*00000074*/ MOV         R0, R6 
    /*00000078*/ BL          _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E
    /*0000007c*/ LDR         R0, [R5, #24]! 
    /*00000080*/ LDR         R9, [R8, #8] 
    /*00000084*/ CMP         R0, R5 
    /*00000088*/ BEQ         _ZN4hirt11ProcManagerD1Ev_xa0
    _ZN4hirt11ProcManagerD1Ev_x8c:
    /*0000008c*/ LDR         R4, [R0] 
    /*00000090*/ BL          _ZdlPv
    /*00000094*/ CMP         R4, R5 
    /*00000098*/ MOV         R0, R4 
    /*0000009c*/ BNE         _ZN4hirt11ProcManagerD1Ev_x8c
    _ZN4hirt11ProcManagerD1Ev_xa0:
    /*000000a0*/ MOV         R0, R8 
    /*000000a4*/ BL          _ZdlPv
    /*000000a8*/ SUBS        R8, R9, #0 
    /*000000ac*/ BNE         _ZN4hirt11ProcManagerD1Ev_x6c
    _ZN4hirt11ProcManagerD1Ev_xb0:
    /*000000b0*/ MOV         R0, R7 
    /*000000b4*/ POP         {R4, R5, R6, R7, R8, R9, SL, PC} 
    /*000000b8*/ WORD_00b8: .word 0x00000090
FUNC_END _ZN4hirt11ProcManagerD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11ProcManagerD0Ev
@ Size: 0xc8
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11ProcManagerD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4064]             @ 0xfe0 
    /*00000010*/ LDR         R3, WORD_00c4               @ LDR         R3, [PC, #172]              @ 0x00000000000000c4 
    /*00000014*/ ADD         R9, R0, #64                 @ 0x40 
    /*00000018*/ MOV         R6, R0 
    /*0000001c*/ MOV         R7, R0 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ MOV         R5, R9 
    /*00000028*/ ADD         R8, R0, #76                 @ 0x4c 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ STR         R3, [R6], #28 
    _ZN4hirt11ProcManagerD0Ev_x34:
    /*00000034*/ LDR         R0, [R8, #-12]! 
    /*00000038*/ CMP         R0, R5 
    /*0000003c*/ BEQ         _ZN4hirt11ProcManagerD0Ev_x54
    _ZN4hirt11ProcManagerD0Ev_x40:
    /*00000040*/ LDR         R4, [R0] 
    /*00000044*/ BL          _ZdlPv
    /*00000048*/ CMP         R4, R5 
    /*0000004c*/ MOV         R0, R4 
    /*00000050*/ BNE         _ZN4hirt11ProcManagerD0Ev_x40
    _ZN4hirt11ProcManagerD0Ev_x54:
    /*00000054*/ CMP         R9, R8 
    /*00000058*/ SUB         R5, R5, #12 
    /*0000005c*/ BNE         _ZN4hirt11ProcManagerD0Ev_x34
    /*00000060*/ LDR         R8, [R7, #36]               @ 0x24 
    /*00000064*/ CMP         R8, #0 
    /*00000068*/ BEQ         _ZN4hirt11ProcManagerD0Ev_xb0
    _ZN4hirt11ProcManagerD0Ev_x6c:
    /*0000006c*/ LDR         R1, [R8, #12] 
    /*00000070*/ MOV         R5, R8 
    /*00000074*/ MOV         R0, R6 
    /*00000078*/ BL          _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E
    /*0000007c*/ LDR         R0, [R5, #24]! 
    /*00000080*/ LDR         R9, [R8, #8] 
    /*00000084*/ CMP         R0, R5 
    /*00000088*/ BEQ         _ZN4hirt11ProcManagerD0Ev_xa0
    _ZN4hirt11ProcManagerD0Ev_x8c:
    /*0000008c*/ LDR         R4, [R0] 
    /*00000090*/ BL          _ZdlPv
    /*00000094*/ CMP         R4, R5 
    /*00000098*/ MOV         R0, R4 
    /*0000009c*/ BNE         _ZN4hirt11ProcManagerD0Ev_x8c
    _ZN4hirt11ProcManagerD0Ev_xa0:
    /*000000a0*/ MOV         R0, R8 
    /*000000a4*/ BL          _ZdlPv
    /*000000a8*/ SUBS        R8, R9, #0 
    /*000000ac*/ BNE         _ZN4hirt11ProcManagerD0Ev_x6c
    _ZN4hirt11ProcManagerD0Ev_xb0:
    /*000000b0*/ MOV         R0, R7 
    /*000000b4*/ MOV         R1, #104                    @ 0x68 
    /*000000b8*/ BL          _ZdlPvj
    /*000000bc*/ MOV         R0, R7 
    /*000000c0*/ POP         {R4, R5, R6, R7, R8, R9, SL, PC} 
    /*000000c4*/ WORD_00c4: .word 0x0000009c
FUNC_END _ZN4hirt11ProcManagerD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11ProcManagerC2Ev
@ Size: 0x1a4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11ProcManagerC2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4064]             @ 0xfe0 
    /*00000010*/ LDR         R3, WORD_0184               @ LDR         R3, [PC, #364]              @ 0x0000000000000184 
    /*00000014*/ MOV         R2, R0 
    /*00000018*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ MOV         R4, R0 
    /*00000024*/ LDR         LR, WORD_0188               @ LDR         LR, [PC, #348]              @ 0x0000000000000188 
    /*00000028*/ ADD         R1, R0, #32 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ MOV         IP, #0 
    /*00000034*/ STR         R3, [R2], #4 
    /*00000038*/ ADD         R5, R0, #64                 @ 0x40 
    /*0000003c*/ ADD         LR, PC, LR 
    /*00000040*/ MOV         R3, #20 
    /*00000044*/ VST1.8      {D16-D17}, [R2] 
    /*00000048*/ VSTR        D16, [R2, #16] 
    /*0000004c*/ SUB         SP, SP, #8 
    /*00000050*/ MOV         R2, IP 
    /*00000054*/ VST1.8      {D16-D17}, [R1] 
    /*00000058*/ STR         R1, [R4, #40]               @ 0x28 
    /*0000005c*/ ADD         R0, R0, #80                 @ 0x50 
    /*00000060*/ STR         R1, [R4, #44]               @ 0x2c 
    /*00000064*/ MOV         R1, R3 
    /*00000068*/ STR         LR, [R4, #100]              @ 0x64 
    /*0000006c*/ STR         R5, [R4, #64]               @ 0x40 
    /*00000070*/ STR         R5, [R4, #68]               @ 0x44 
    /*00000074*/ STR         IP, [R4, #48]               @ 0x30 
    /*00000078*/ STR         IP, [R4, #72]               @ 0x48 
    /*0000007c*/ STR         IP, [R4, #76]               @ 0x4c 
    /*00000080*/ BL          memset_s
    /*00000084*/ CMP         R0, #0 
    /*00000088*/ BEQ         _ZN4hirt11ProcManagerC2Ev_xb0
    /*0000008c*/ STR         R0, [SP] 
    /*00000090*/ MOV         R1, #4 
    /*00000094*/ LDR         R3, WORD_018c               @ LDR         R3, [PC, #240]              @ 0x000000000000018c 
    /*00000098*/ LDR         R2, WORD_0190               @ LDR         R2, [PC, #240]              @ 0x0000000000000190 
    /*0000009c*/ LDR         R0, WORD_0194               @ LDR         R0, [PC, #240]              @ 0x0000000000000194 
    /*000000a0*/ ADD         R3, PC, R3 
    /*000000a4*/ ADD         R2, PC, R2 
    /*000000a8*/ ADD         R0, PC, R0 
    /*000000ac*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt11ProcManagerC2Ev_xb0:
    /*000000b0*/ MOV         R3, #12 
    /*000000b4*/ MOV         R2, #0 
    /*000000b8*/ MOV         R1, R3 
    /*000000bc*/ ADD         R0, R4, #52                 @ 0x34 
    /*000000c0*/ BL          memset_s
    /*000000c4*/ CMP         R0, #0 
    /*000000c8*/ BNE         _ZN4hirt11ProcManagerC2Ev_xd8
    /*000000cc*/ MOV         R0, R4 
    /*000000d0*/ ADD         SP, SP, #8 
    /*000000d4*/ POP         {R4, R5, R6, R7, R8, PC} 
    _ZN4hirt11ProcManagerC2Ev_xd8:
    /*000000d8*/ STR         R0, [SP] 
    /*000000dc*/ MOV         R1, #4 
    /*000000e0*/ LDR         R3, WORD_0198               @ LDR         R3, [PC, #176]              @ 0x0000000000000198 
    /*000000e4*/ LDR         R2, WORD_019c               @ LDR         R2, [PC, #176]              @ 0x000000000000019c 
    /*000000e8*/ LDR         R0, WORD_01a0               @ LDR         R0, [PC, #176]              @ 0x00000000000001a0 
    /*000000ec*/ ADD         R3, PC, R3 
    /*000000f0*/ ADD         R2, PC, R2 
    /*000000f4*/ ADD         R0, PC, R0 
    /*000000f8*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000000fc*/ MOV         R0, R4 
    /*00000100*/ ADD         SP, SP, #8 
    /*00000104*/ POP         {R4, R5, R6, R7, R8, PC} 
    /*00000108*/ ADD         R6, R4, #76                 @ 0x4c 
    _ZN4hirt11ProcManagerC2Ev_x10c:
    /*0000010c*/ CMP         R5, R6 
    /*00000110*/ BEQ         _ZN4hirt11ProcManagerC2Ev_x130
    /*00000114*/ LDR         R0, [R6, #-12]! 
    _ZN4hirt11ProcManagerC2Ev_x118:
    /*00000118*/ CMP         R6, R0 
    /*0000011c*/ BEQ         _ZN4hirt11ProcManagerC2Ev_x10c
    /*00000120*/ LDR         R7, [R0] 
    /*00000124*/ BL          _ZdlPv
    /*00000128*/ MOV         R0, R7 
    /*0000012c*/ B           _ZN4hirt11ProcManagerC2Ev_x118
    _ZN4hirt11ProcManagerC2Ev_x130:
    /*00000130*/ LDR         R5, [R4, #36]               @ 0x24 
    /*00000134*/ ADD         R4, R4, #28 
    _ZN4hirt11ProcManagerC2Ev_x138:
    /*00000138*/ CMP         R5, #0 
    /*0000013c*/ BEQ         _ZN4hirt11ProcManagerC2Ev_x170
    /*00000140*/ LDR         R1, [R5, #12] 
    /*00000144*/ MOV         R6, R5 
    /*00000148*/ MOV         R0, R4 
    /*0000014c*/ BL          _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E
    /*00000150*/ LDR         R0, [R6, #24]! 
    /*00000154*/ LDR         R7, [R5, #8] 
    _ZN4hirt11ProcManagerC2Ev_x158:
    /*00000158*/ CMP         R0, R6 
    /*0000015c*/ BEQ         _ZN4hirt11ProcManagerC2Ev_x174
    /*00000160*/ LDR         R8, [R0] 
    /*00000164*/ BL          _ZdlPv
    /*00000168*/ MOV         R0, R8 
    /*0000016c*/ B           _ZN4hirt11ProcManagerC2Ev_x158
    _ZN4hirt11ProcManagerC2Ev_x170:
    /*00000170*/ BL          __cxa_end_cleanup
    _ZN4hirt11ProcManagerC2Ev_x174:
    /*00000174*/ MOV         R0, R5 
    /*00000178*/ MOV         R5, R7 
    /*0000017c*/ BL          _ZdlPv
    /*00000180*/ B           _ZN4hirt11ProcManagerC2Ev_x138
    /*00000184*/ WORD_0184: .word 0x00000160
    /*00000188*/ WORD_0188: .word 0x00000144
    /*0000018c*/ WORD_018c: .word 0x000000e4
    /*00000190*/ WORD_0190: .word 0x000000e4
    /*00000194*/ WORD_0194: .word 0x000000e4
    /*00000198*/ WORD_0198: .word 0x000000a4
    /*0000019c*/ WORD_019c: .word 0x000000a4
    /*000001a0*/ WORD_01a0: .word 0x000000a4
FUNC_END _ZN4hirt11ProcManagerC2Ev


FUNC_BEGIN _ZN4hirt11ProcManagerC1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4064]             @ 0xfe0 
    /*00000010*/ LDR         R3, WORD_0184               @ LDR         R3, [PC, #364]              @ 0x0000000000000184 
    /*00000014*/ MOV         R2, R0 
    /*00000018*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ MOV         R4, R0 
    /*00000024*/ LDR         LR, WORD_0188               @ LDR         LR, [PC, #348]              @ 0x0000000000000188 
    /*00000028*/ ADD         R1, R0, #32 
    /*0000002c*/ ADD         R3, R3, #8 
    /*00000030*/ MOV         IP, #0 
    /*00000034*/ STR         R3, [R2], #4 
    /*00000038*/ ADD         R5, R0, #64                 @ 0x40 
    /*0000003c*/ ADD         LR, PC, LR 
    /*00000040*/ MOV         R3, #20 
    /*00000044*/ VST1.8      {D16-D17}, [R2] 
    /*00000048*/ VSTR        D16, [R2, #16] 
    /*0000004c*/ SUB         SP, SP, #8 
    /*00000050*/ MOV         R2, IP 
    /*00000054*/ VST1.8      {D16-D17}, [R1] 
    /*00000058*/ STR         R1, [R4, #40]               @ 0x28 
    /*0000005c*/ ADD         R0, R0, #80                 @ 0x50 
    /*00000060*/ STR         R1, [R4, #44]               @ 0x2c 
    /*00000064*/ MOV         R1, R3 
    /*00000068*/ STR         LR, [R4, #100]              @ 0x64 
    /*0000006c*/ STR         R5, [R4, #64]               @ 0x40 
    /*00000070*/ STR         R5, [R4, #68]               @ 0x44 
    /*00000074*/ STR         IP, [R4, #48]               @ 0x30 
    /*00000078*/ STR         IP, [R4, #72]               @ 0x48 
    /*0000007c*/ STR         IP, [R4, #76]               @ 0x4c 
    /*00000080*/ BL          memset_s
    /*00000084*/ CMP         R0, #0 
    /*00000088*/ BEQ         _ZN4hirt11ProcManagerC1Ev_xb0
    /*0000008c*/ STR         R0, [SP] 
    /*00000090*/ MOV         R1, #4 
    /*00000094*/ LDR         R3, WORD_018c               @ LDR         R3, [PC, #240]              @ 0x000000000000018c 
    /*00000098*/ LDR         R2, WORD_0190               @ LDR         R2, [PC, #240]              @ 0x0000000000000190 
    /*0000009c*/ LDR         R0, WORD_0194               @ LDR         R0, [PC, #240]              @ 0x0000000000000194 
    /*000000a0*/ ADD         R3, PC, R3 
    /*000000a4*/ ADD         R2, PC, R2 
    /*000000a8*/ ADD         R0, PC, R0 
    /*000000ac*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt11ProcManagerC1Ev_xb0:
    /*000000b0*/ MOV         R3, #12 
    /*000000b4*/ MOV         R2, #0 
    /*000000b8*/ MOV         R1, R3 
    /*000000bc*/ ADD         R0, R4, #52                 @ 0x34 
    /*000000c0*/ BL          memset_s
    /*000000c4*/ CMP         R0, #0 
    /*000000c8*/ BNE         _ZN4hirt11ProcManagerC1Ev_xd8
    /*000000cc*/ MOV         R0, R4 
    /*000000d0*/ ADD         SP, SP, #8 
    /*000000d4*/ POP         {R4, R5, R6, R7, R8, PC} 
    _ZN4hirt11ProcManagerC1Ev_xd8:
    /*000000d8*/ STR         R0, [SP] 
    /*000000dc*/ MOV         R1, #4 
    /*000000e0*/ LDR         R3, WORD_0198               @ LDR         R3, [PC, #176]              @ 0x0000000000000198 
    /*000000e4*/ LDR         R2, WORD_019c               @ LDR         R2, [PC, #176]              @ 0x000000000000019c 
    /*000000e8*/ LDR         R0, WORD_01a0               @ LDR         R0, [PC, #176]              @ 0x00000000000001a0 
    /*000000ec*/ ADD         R3, PC, R3 
    /*000000f0*/ ADD         R2, PC, R2 
    /*000000f4*/ ADD         R0, PC, R0 
    /*000000f8*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000000fc*/ MOV         R0, R4 
    /*00000100*/ ADD         SP, SP, #8 
    /*00000104*/ POP         {R4, R5, R6, R7, R8, PC} 
    /*00000108*/ ADD         R6, R4, #76                 @ 0x4c 
    _ZN4hirt11ProcManagerC1Ev_x10c:
    /*0000010c*/ CMP         R5, R6 
    /*00000110*/ BEQ         _ZN4hirt11ProcManagerC1Ev_x130
    /*00000114*/ LDR         R0, [R6, #-12]! 
    _ZN4hirt11ProcManagerC1Ev_x118:
    /*00000118*/ CMP         R6, R0 
    /*0000011c*/ BEQ         _ZN4hirt11ProcManagerC1Ev_x10c
    /*00000120*/ LDR         R7, [R0] 
    /*00000124*/ BL          _ZdlPv
    /*00000128*/ MOV         R0, R7 
    /*0000012c*/ B           _ZN4hirt11ProcManagerC1Ev_x118
    _ZN4hirt11ProcManagerC1Ev_x130:
    /*00000130*/ LDR         R5, [R4, #36]               @ 0x24 
    /*00000134*/ ADD         R4, R4, #28 
    _ZN4hirt11ProcManagerC1Ev_x138:
    /*00000138*/ CMP         R5, #0 
    /*0000013c*/ BEQ         _ZN4hirt11ProcManagerC1Ev_x170
    /*00000140*/ LDR         R1, [R5, #12] 
    /*00000144*/ MOV         R6, R5 
    /*00000148*/ MOV         R0, R4 
    /*0000014c*/ BL          _ZNSt8_Rb_treeIySt4pairIKyNSt7__cxx114listIN4hirt20tagPROC_SEGTASK_INFOESaIS5_EEEESt10_Select1stIS8_ESt4lessIyESaIS8_EE8_M_eraseEPSt13_Rb_tree_nodeIS8_E
    /*00000150*/ LDR         R0, [R6, #24]! 
    /*00000154*/ LDR         R7, [R5, #8] 
    _ZN4hirt11ProcManagerC1Ev_x158:
    /*00000158*/ CMP         R0, R6 
    /*0000015c*/ BEQ         _ZN4hirt11ProcManagerC1Ev_x174
    /*00000160*/ LDR         R8, [R0] 
    /*00000164*/ BL          _ZdlPv
    /*00000168*/ MOV         R0, R8 
    /*0000016c*/ B           _ZN4hirt11ProcManagerC1Ev_x158
    _ZN4hirt11ProcManagerC1Ev_x170:
    /*00000170*/ BL          __cxa_end_cleanup
    _ZN4hirt11ProcManagerC1Ev_x174:
    /*00000174*/ MOV         R0, R5 
    /*00000178*/ MOV         R5, R7 
    /*0000017c*/ BL          _ZdlPv
    /*00000180*/ B           _ZN4hirt11ProcManagerC1Ev_x138
    /*00000184*/ WORD_0184: .word 0x00000160
    /*00000188*/ WORD_0188: .word 0x00000144
    /*0000018c*/ WORD_018c: .word 0x000000e4
    /*00000190*/ WORD_0190: .word 0x000000e4
    /*00000194*/ WORD_0194: .word 0x000000e4
    /*00000198*/ WORD_0198: .word 0x000000a4
    /*0000019c*/ WORD_019c: .word 0x000000a4
    /*000001a0*/ WORD_01a0: .word 0x000000a4
FUNC_END _ZN4hirt11ProcManagerC1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt11ProcManagerC2Ev
@ Size: 0x17
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11ProcManager11getInstanceEv
@ Size: 0xa8
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11ProcManager11getInstanceEv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R0, WORD_0088               @ LDR         R0, [PC, #112]              @ 0x0000000000000088 
    /*00000014*/ ADD         R0, PC, R0 
    /*00000018*/ LDRB        R3, [R0] 
    /*0000001c*/ DMB         ISH 
    /*00000020*/ TST         R3, #1 
    /*00000024*/ BEQ         _ZN4hirt11ProcManager11getInstanceEv_x34
    _ZN4hirt11ProcManager11getInstanceEv_x28:
    /*00000028*/ LDR         R0, WORD_008c               @ LDR         R0, [PC, #92]               @ 0x000000000000008c 
    /*0000002c*/ ADD         R0, PC, R0 
    /*00000030*/ POP         {R4, PC} 
    _ZN4hirt11ProcManager11getInstanceEv_x34:
    /*00000034*/ BL          __cxa_guard_acquire
    /*00000038*/ CMP         R0, #0 
    /*0000003c*/ BEQ         _ZN4hirt11ProcManager11getInstanceEv_x28
    /*00000040*/ LDR         R0, WORD_0090               @ LDR         R0, [PC, #72]               @ 0x0000000000000090 
    /*00000044*/ ADD         R0, PC, R0 
    /*00000048*/ BL          _ZN4hirt11ProcManagerC1Ev
    /*0000004c*/ LDR         R0, WORD_0094               @ LDR         R0, [PC, #64]               @ 0x0000000000000094 
    /*00000050*/ ADD         R0, PC, R0 
    /*00000054*/ BL          __cxa_guard_release
    /*00000058*/ LDR         R2, WORD_0098               @ LDR         R2, [PC, #56]               @ 0x0000000000000098 
    /*0000005c*/ LDR         R1, WORD_009c               @ LDR         R1, [PC, #56]               @ 0x000000000000009c 
    /*00000060*/ LDR         R0, WORD_00a0               @ LDR         R0, [PC, #56]               @ 0x00000000000000a0 
    /*00000064*/ ADD         R2, PC, R2 
    /*00000068*/ ADD         R1, PC, R1 
    /*0000006c*/ ADD         R0, PC, R0 
    /*00000070*/ BL          __aeabi_atexit
    /*00000074*/ B           _ZN4hirt11ProcManager11getInstanceEv_x28
    /*00000078*/ LDR         R0, WORD_00a4               @ LDR         R0, [PC, #36]               @ 0x00000000000000a4 
    /*0000007c*/ ADD         R0, PC, R0 
    /*00000080*/ BL          __cxa_guard_abort
    /*00000084*/ BL          __cxa_end_cleanup
    /*00000088*/ WORD_0088: .word 0x0000006c
    /*0000008c*/ WORD_008c: .word 0x00000058
    /*00000090*/ WORD_0090: .word 0x00000044
    /*00000094*/ WORD_0094: .word 0x0000003c
    /*00000098*/ WORD_0098: .word 0x0000002c
    /*0000009c*/ WORD_009c: .word 0x0000002c
    /*000000a0*/ WORD_00a0: .word 0x0000002c
    /*000000a4*/ WORD_00a4: .word 0x00000020
FUNC_END _ZN4hirt11ProcManager11getInstanceEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt11ProcManager11getInstanceEv
@ Size: 0x15
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv
@ Size: 0x540
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4000]             @ 0xfa0 
    /*00000010*/ LDR         R4, WORD_04c4               @ LDR         R4, [PC, #1196]             @ 0x00000000000004c4 
    /*00000014*/ SUB         SP, SP, #60                 @ 0x3c 
    /*00000018*/ LDR         R7, WORD_04c8               @ LDR         R7, [PC, #1192]             @ 0x00000000000004c8 
    /*0000001c*/ MOV         R6, R1 
    /*00000020*/ STR         R1, [SP, #36]               @ 0x24 
    /*00000024*/ MOV         R5, R0 
    /*00000028*/ LDR         R1, WORD_04cc               @ LDR         R1, [PC, #1180]             @ 0x00000000000004cc 
    /*0000002c*/ ADD         R4, PC, R4 
    /*00000030*/ ADD         R1, PC, R1 
    /*00000034*/ ADD         R7, PC, R7 
    /*00000038*/ STR         R7, [SP, #40]               @ 0x28 
    /*0000003c*/ BL          HI_PROC_Printf
    /*00000040*/ MOV         R1, R4 
    /*00000044*/ MOV         R0, R5 
    /*00000048*/ BL          HI_PROC_Printf
    /*0000004c*/ LDR         R1, WORD_04d0               @ LDR         R1, [PC, #1148]             @ 0x00000000000004d0 
    /*00000050*/ MOV         R0, R5 
    /*00000054*/ LDR         R2, [R6, #24] 
    /*00000058*/ ADD         R1, PC, R1 
    /*0000005c*/ BL          HI_PROC_Printf
    /*00000060*/ LDR         R1, WORD_04d4               @ LDR         R1, [PC, #1132]             @ 0x00000000000004d4 
    /*00000064*/ MOV         R0, R5 
    /*00000068*/ LDR         R2, [R6, #28] 
    /*0000006c*/ ADD         R1, PC, R1 
    /*00000070*/ BL          HI_PROC_Printf
    /*00000074*/ LDR         R1, WORD_04d8               @ LDR         R1, [PC, #1116]             @ 0x00000000000004d8 
    /*00000078*/ MOV         R0, R5 
    /*0000007c*/ LDR         R2, [R6, #32] 
    /*00000080*/ ADD         R1, PC, R1 
    /*00000084*/ BL          HI_PROC_Printf
    /*00000088*/ LDR         R1, WORD_04dc               @ LDR         R1, [PC, #1100]             @ 0x00000000000004dc 
    /*0000008c*/ MOV         R2, #0 
    /*00000090*/ MOV         R0, R5 
    /*00000094*/ ADD         R1, PC, R1 
    /*00000098*/ BL          HI_PROC_Printf
    /*0000009c*/ MOV         R1, R4 
    /*000000a0*/ MOV         R4, R6 
    /*000000a4*/ MOV         R0, R5 
    /*000000a8*/ BL          HI_PROC_Printf
    /*000000ac*/ LDR         R8, [R4, #36]!              @ 0x24 
    /*000000b0*/ CMP         R8, R4 
    /*000000b4*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x47c
    /*000000b8*/ MOVW        R0, #19923                  @ 0x4dd3 
    /*000000bc*/ MOVW        IP, #16960                  @ 0x4240 
    /*000000c0*/ MOVT        R0, #4194                   @ 0x1062 
    /*000000c4*/ MOV         SL, #0 
    /*000000c8*/ MOVT        IP, #15 
    /*000000cc*/ MOV         FP, #0 
    /*000000d0*/ MOV         LR, R8 
    /*000000d4*/ MOV         R2, #0 
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_xd8:
    /*000000d8*/ LDR         R3, [LR, #20] 
    /*000000dc*/ LDR         R9, [LR, #12] 
    /*000000e0*/ LDR         R1, [LR, #16] 
    /*000000e4*/ SUB         R9, R3, R9 
    /*000000e8*/ SMULL       R6, R7, R9, R0 
    /*000000ec*/ ASR         R6, R9, #31 
    /*000000f0*/ RSB         R6, R6, R7, ASR #6 
    /*000000f4*/ LDR         R9, [LR, #8] 
    /*000000f8*/ ASR         R7, R6, #31 
    /*000000fc*/ SUB         R9, R1, R9 
    /*00000100*/ CMP         R8, LR 
    /*00000104*/ SMLAL       R6, R7, IP, R9 
    /*00000108*/ ADDEQ       R2, LR, #8 
    /*0000010c*/ LDR         LR, [LR] 
    /*00000110*/ ADDS        SL, SL, R6 
    /*00000114*/ ADC         FP, FP, R7 
    /*00000118*/ CMP         R4, LR 
    /*0000011c*/ BNE         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_xd8
    /*00000120*/ CMP         R2, #0 
    /*00000124*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x1a4
    /*00000128*/ ADDS        R6, SL, SL 
    /*0000012c*/ ADC         R7, FP, FP 
    /*00000130*/ ADDS        R8, R6, SL 
    /*00000134*/ ADC         R9, R7, FP 
    /*00000138*/ LDR         R4, [R2, #4] 
    /*0000013c*/ VMOV        D16, R8, R9 
    /*00000140*/ SUB         R4, R3, R4 
    /*00000144*/ LDR         LR, [R2] 
    /*00000148*/ SMULL       R2, R3, R4, R0 
    /*0000014c*/ VSHL.S64    D17, D16, #5 
    /*00000150*/ ASR         R6, R4, #31 
    /*00000154*/ RSB         R6, R6, R3, ASR #6 
    /*00000158*/ VADD.I64    D16, D16, D17 
    /*0000015c*/ SUB         R1, R1, LR 
    /*00000160*/ ASR         R7, R6, #31 
    /*00000164*/ SMLAL       R6, R7, IP, R1 
    /*00000168*/ VMOV        R0, R1, D16 
    /*0000016c*/ LDR         R4, WORD_04e0               @ LDR         R4, [PC, #876]              @ 0x00000000000004e0 
    /*00000170*/ MOV         R2, R6 
    /*00000174*/ ADDS        R0, R0, SL 
    /*00000178*/ MOV         R3, R7 
    /*0000017c*/ ADC         R1, R1, FP 
    /*00000180*/ ADD         R4, PC, R4 
    /*00000184*/ BL          __aeabi_uldivmod
    /*00000188*/ STRD        R0, [SP, #8] 
    /*0000018c*/ STRD        R6, [SP] 
    /*00000190*/ MOV         R2, SL 
    /*00000194*/ MOV         R3, FP 
    /*00000198*/ MOV         R1, R4 
    /*0000019c*/ MOV         R0, R5 
    /*000001a0*/ BL          HI_PROC_Printf
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x1a4:
    /*000001a4*/ LDR         R1, WORD_04e4               @ LDR         R1, [PC, #824]              @ 0x00000000000004e4 
    /*000001a8*/ MOV         R0, R5 
    /*000001ac*/ ADD         R1, PC, R1 
    /*000001b0*/ BL          HI_PROC_Printf
    /*000001b4*/ LDR         R1, WORD_04e8               @ LDR         R1, [PC, #812]              @ 0x00000000000004e8 
    /*000001b8*/ MOV         R0, R5 
    /*000001bc*/ ADD         R1, PC, R1 
    /*000001c0*/ BL          HI_PROC_Printf
    /*000001c4*/ LDR         R0, WORD_04ec               @ LDR         R0, [PC, #800]              @ 0x00000000000004ec 
    /*000001c8*/ ADD         R0, PC, R0 
    /*000001cc*/ LDRB        R3, [R0] 
    /*000001d0*/ DMB         ISH 
    /*000001d4*/ TST         R3, #1 
    /*000001d8*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x41c
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x1dc:
    /*000001dc*/ LDR         R3, WORD_04f0               @ LDR         R3, [PC, #780]              @ 0x00000000000004f0 
    /*000001e0*/ LDR         R2, [SP, #40]               @ 0x28 
    /*000001e4*/ LDR         R3, [R2, R3] 
    /*000001e8*/ STR         R3, [SP, #52]               @ 0x34 
    /*000001ec*/ CMP         R3, #0 
    /*000001f0*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x460
    /*000001f4*/ LDR         R0, WORD_04f4               @ LDR         R0, [PC, #760]              @ 0x00000000000004f4 
    /*000001f8*/ ADD         R0, PC, R0 
    /*000001fc*/ ADD         R0, R0, #4 
    /*00000200*/ BL          pthread_mutex_lock
    /*00000204*/ CMP         R0, #0 
    /*00000208*/ BNE         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x4c0
    /*0000020c*/ LDR         R3, [SP, #36]               @ 0x24 
    /*00000210*/ LDR         R6, [R3, #12] 
    /*00000214*/ ADD         R3, R3, #4 
    /*00000218*/ STR         R3, [SP, #44]               @ 0x2c 
    /*0000021c*/ CMP         R3, R6 
    /*00000220*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x400
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x224:
    /*00000224*/ LDR         R3, [R6, #32] 
    /*00000228*/ CMP         R3, #0 
    /*0000022c*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x3b0
    /*00000230*/ LDR         R3, WORD_04f8               @ LDR         R3, [PC, #704]              @ 0x00000000000004f8 
    /*00000234*/ MOVW        R9, #16960                  @ 0x4240 
    /*00000238*/ MOVT        R9, #15 
    /*0000023c*/ ADD         R3, PC, R3 
    /*00000240*/ STR         R3, [SP, #48]               @ 0x30 
    /*00000244*/ MOVW        R3, #19923                  @ 0x4dd3 
    /*00000248*/ MOVT        R3, #4194                   @ 0x1062 
    /*0000024c*/ STR         R3, [SP, #40]               @ 0x28 
    /*00000250*/ LDR         R3, WORD_04fc               @ LDR         R3, [PC, #676]              @ 0x00000000000004fc 
    /*00000254*/ ADD         R3, PC, R3 
    /*00000258*/ STR         R3, [SP, #36]               @ 0x24 
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x25c:
    /*0000025c*/ LDR         R0, [R6, #24] 
    /*00000260*/ MOV         R3, #24 
    /*00000264*/ LDR         R1, [SP, #48]               @ 0x30 
    /*00000268*/ MOV         R2, R3 
    /*0000026c*/ VLDR        D16, [R0, #80]              @ 0x50 
    /*00000270*/ ADD         R0, R0, #8 
    /*00000274*/ VSTR        D16, [SP, #24] 
    /*00000278*/ LDR         IP, [R0, #68]               @ 0x44 
    /*0000027c*/ STR         IP, [SP, #16] 
    /*00000280*/ VLDR        D16, [R6, #16] 
    /*00000284*/ STR         R0, [SP] 
    /*00000288*/ MOV         R0, R5 
    /*0000028c*/ VSTR        D16, [SP, #8] 
    /*00000290*/ BL          HI_PROC_Printf
    /*00000294*/ MOV         R7, R6 
    /*00000298*/ LDR         R4, [R7, #24]! 
    /*0000029c*/ CMP         R4, R7 
    /*000002a0*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x37c
    /*000002a4*/ LDR         R2, [R4, #160]              @ 0xa0 
    /*000002a8*/ LDR         R3, [R4, #168]              @ 0xa8 
    /*000002ac*/ LDR         IP, [R4, #164]              @ 0xa4 
    /*000002b0*/ SUB         R3, R3, R2 
    /*000002b4*/ LDR         R2, [SP, #40]               @ 0x28 
    /*000002b8*/ LDR         R8, WORD_0500               @ LDR         R8, [PC, #576]              @ 0x0000000000000500 
    /*000002bc*/ SMULL       R0, R1, R3, R2 
    /*000002c0*/ ASR         R2, R3, #31 
    /*000002c4*/ RSB         R2, R2, R1, ASR #6 
    /*000002c8*/ LDR         R1, [R4, #156]              @ 0x9c 
    /*000002cc*/ ASR         R3, R2, #31 
    /*000002d0*/ SUB         IP, IP, R1 
    /*000002d4*/ SMLAL       R2, R3, R9, IP 
    /*000002d8*/ ADD         R8, PC, R8 
    /*000002dc*/ MOV         SL, R2 
    /*000002e0*/ MOV         FP, R3 
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x2e4:
    /*000002e4*/ LDR         R3, [R4, #172]              @ 0xac 
    /*000002e8*/ ADD         R2, R4, #88                 @ 0x58 
    /*000002ec*/ LDR         R1, [R4, #176]              @ 0xb0 
    /*000002f0*/ MOV         R0, R5 
    /*000002f4*/ CMP         R3, #0 
    /*000002f8*/ STR         R1, [SP, #12] 
    /*000002fc*/ LDR         R3, [SP, #36]               @ 0x24 
    /*00000300*/ MOVEQ       R3, R8 
    /*00000304*/ LDR         R1, WORD_0504               @ LDR         R1, [PC, #504]              @ 0x0000000000000504 
    /*00000308*/ STRD        SL, [SP] 
    /*0000030c*/ ADD         R1, PC, R1 
    /*00000310*/ STR         R3, [SP, #8] 
    /*00000314*/ BL          HI_PROC_Printf
    /*00000318*/ LDR         R4, [R4] 
    /*0000031c*/ CMP         R4, R7 
    /*00000320*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x37c
    /*00000324*/ LDR         R3, [R4, #160]              @ 0xa0 
    /*00000328*/ LDR         R2, [R4, #168]              @ 0xa8 
    /*0000032c*/ LDR         IP, [R4, #164]              @ 0xa4 
    /*00000330*/ SUB         R2, R2, R3 
    /*00000334*/ LDR         R3, [SP, #40]               @ 0x28 
    /*00000338*/ SMULL       R0, R1, R2, R3 
    /*0000033c*/ ASR         R2, R2, #31 
    /*00000340*/ RSB         R2, R2, R1, ASR #6 
    /*00000344*/ LDR         R3, [R6, #24] 
    /*00000348*/ LDR         R1, [R4, #156]              @ 0x9c 
    /*0000034c*/ CMP         R3, R4 
    /*00000350*/ SUB         IP, IP, R1 
    /*00000354*/ ASR         R3, R2, #31 
    /*00000358*/ SMLAL       R2, R3, R9, IP 
    /*0000035c*/ MOV         SL, R2 
    /*00000360*/ MOV         FP, R3 
    /*00000364*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x2e4
    /*00000368*/ LDR         R1, WORD_0508               @ LDR         R1, [PC, #408]              @ 0x0000000000000508 
    /*0000036c*/ MOV         R0, R5 
    /*00000370*/ ADD         R1, PC, R1 
    /*00000374*/ BL          HI_PROC_Printf
    /*00000378*/ B           _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x2e4
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x37c:
    /*0000037c*/ LDR         R1, WORD_050c               @ LDR         R1, [PC, #392]              @ 0x000000000000050c 
    /*00000380*/ MOV         R0, R5 
    /*00000384*/ ADD         R1, PC, R1 
    /*00000388*/ BL          HI_PROC_Printf
    /*0000038c*/ MOV         R0, R6 
    /*00000390*/ BL          _ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base
    /*00000394*/ LDR         R3, [SP, #44]               @ 0x2c 
    /*00000398*/ CMP         R0, R3 
    /*0000039c*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x3f4
    /*000003a0*/ LDR         R3, [R0, #32] 
    /*000003a4*/ MOV         R6, R0 
    /*000003a8*/ CMP         R3, #0 
    /*000003ac*/ BNE         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x25c
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x3b0:
    /*000003b0*/ LDR         R2, WORD_0510               @ LDR         R2, [PC, #344]              @ 0x0000000000000510 
    /*000003b4*/ MOV         R1, #4 
    /*000003b8*/ LDR         R0, WORD_0514               @ LDR         R0, [PC, #340]              @ 0x0000000000000514 
    /*000003bc*/ ADD         R2, PC, R2 
    /*000003c0*/ ADD         R0, PC, R0 
    /*000003c4*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000003c8*/ LDR         R3, [SP, #52]               @ 0x34 
    /*000003cc*/ CMP         R3, #0 
    /*000003d0*/ MVNEQ       R0, #0 
    /*000003d4*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x3ec
    /*000003d8*/ LDR         R0, WORD_0518               @ LDR         R0, [PC, #312]              @ 0x0000000000000518 
    /*000003dc*/ ADD         R0, PC, R0 
    /*000003e0*/ ADD         R0, R0, #4 
    /*000003e4*/ BL          pthread_mutex_unlock
    /*000003e8*/ MVN         R0, #0 
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x3ec:
    /*000003ec*/ ADD         SP, SP, #60                 @ 0x3c 
    /*000003f0*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x3f4:
    /*000003f4*/ LDR         R3, [SP, #52]               @ 0x34 
    /*000003f8*/ CMP         R3, #0 
    /*000003fc*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x410
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x400:
    /*00000400*/ LDR         R0, WORD_051c               @ LDR         R0, [PC, #276]              @ 0x000000000000051c 
    /*00000404*/ ADD         R0, PC, R0 
    /*00000408*/ ADD         R0, R0, #4 
    /*0000040c*/ BL          pthread_mutex_unlock
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x410:
    /*00000410*/ MOV         R0, #0 
    /*00000414*/ ADD         SP, SP, #60                 @ 0x3c 
    /*00000418*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x41c:
    /*0000041c*/ BL          __cxa_guard_acquire
    /*00000420*/ CMP         R0, #0 
    /*00000424*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x1dc
    /*00000428*/ LDR         R0, WORD_0520               @ LDR         R0, [PC, #240]              @ 0x0000000000000520 
    /*0000042c*/ ADD         R0, PC, R0 
    /*00000430*/ BL          _ZN4hirt11ProcManagerC1Ev
    /*00000434*/ LDR         R0, WORD_0524               @ LDR         R0, [PC, #232]              @ 0x0000000000000524 
    /*00000438*/ ADD         R0, PC, R0 
    /*0000043c*/ BL          __cxa_guard_release
    /*00000440*/ LDR         R2, WORD_0528               @ LDR         R2, [PC, #224]              @ 0x0000000000000528 
    /*00000444*/ LDR         R1, WORD_052c               @ LDR         R1, [PC, #224]              @ 0x000000000000052c 
    /*00000448*/ LDR         R0, WORD_0530               @ LDR         R0, [PC, #224]              @ 0x0000000000000530 
    /*0000044c*/ ADD         R2, PC, R2 
    /*00000450*/ ADD         R1, PC, R1 
    /*00000454*/ ADD         R0, PC, R0 
    /*00000458*/ BL          __aeabi_atexit
    /*0000045c*/ B           _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x1dc
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x460:
    /*00000460*/ LDR         R3, [SP, #36]               @ 0x24 
    /*00000464*/ LDR         R6, [R3, #12] 
    /*00000468*/ ADD         R3, R3, #4 
    /*0000046c*/ STR         R3, [SP, #44]               @ 0x2c 
    /*00000470*/ CMP         R6, R3 
    /*00000474*/ BNE         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x224
    /*00000478*/ B           _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x410
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x47c:
    /*0000047c*/ LDR         R1, WORD_0534               @ LDR         R1, [PC, #176]              @ 0x0000000000000534 
    /*00000480*/ MOV         R0, R5 
    /*00000484*/ ADD         R1, PC, R1 
    /*00000488*/ BL          HI_PROC_Printf
    /*0000048c*/ B           _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x1a4
    /*00000490*/ LDR         R0, WORD_0538               @ LDR         R0, [PC, #160]              @ 0x0000000000000538 
    /*00000494*/ ADD         R0, PC, R0 
    /*00000498*/ BL          __cxa_guard_abort
    /*0000049c*/ BL          __cxa_end_cleanup
    /*000004a0*/ LDR         R3, [SP, #52]               @ 0x34 
    /*000004a4*/ CMP         R3, #0 
    /*000004a8*/ BEQ         _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x4bc
    /*000004ac*/ LDR         R0, WORD_053c               @ LDR         R0, [PC, #136]              @ 0x000000000000053c 
    /*000004b0*/ ADD         R0, PC, R0 
    /*000004b4*/ ADD         R0, R0, #4 
    /*000004b8*/ BL          pthread_mutex_unlock
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x4bc:
    /*000004bc*/ BL          __cxa_end_cleanup
    _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv_x4c0:
    /*000004c0*/ BL          _ZSt20__throw_system_errori
    /*000004c4*/ WORD_04c4: .word 0x00000490
    /*000004c8*/ WORD_04c8: .word 0x0000048c
    /*000004cc*/ WORD_04cc: .word 0x00000494
    /*000004d0*/ WORD_04d0: .word 0x00000470
    /*000004d4*/ WORD_04d4: .word 0x00000460
    /*000004d8*/ WORD_04d8: .word 0x00000450
    /*000004dc*/ WORD_04dc: .word 0x00000440
    /*000004e0*/ WORD_04e0: .word 0x00000358
    /*000004e4*/ WORD_04e4: .word 0x00000330
    /*000004e8*/ WORD_04e8: .word 0x00000324
    /*000004ec*/ WORD_04ec: .word 0x0000031c
    /*000004f0*/ WORD_04f0: .word 0x00000000
    /*000004f4*/ WORD_04f4: .word 0x000002f4
    /*000004f8*/ WORD_04f8: .word 0x000002b4
    /*000004fc*/ WORD_04fc: .word 0x000002a0
    /*00000500*/ WORD_0500: .word 0x00000220
    /*00000504*/ WORD_0504: .word 0x000001f0
    /*00000508*/ WORD_0508: .word 0x00000190
    /*0000050c*/ WORD_050c: .word 0x00000180
    /*00000510*/ WORD_0510: .word 0x0000014c
    /*00000514*/ WORD_0514: .word 0x0000014c
    /*00000518*/ WORD_0518: .word 0x00000134
    /*0000051c*/ WORD_051c: .word 0x00000110
    /*00000520*/ WORD_0520: .word 0x000000ec
    /*00000524*/ WORD_0524: .word 0x000000e4
    /*00000528*/ WORD_0528: .word 0x000000d4
    /*0000052c*/ WORD_052c: .word 0x000000d4
    /*00000530*/ WORD_0530: .word 0x000000d4
    /*00000534*/ WORD_0534: .word 0x000000a8
    /*00000538*/ WORD_0538: .word 0x0000009c
    /*0000053c*/ WORD_053c: .word 0x00000084
FUNC_END _ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZL12TaskShowInfoP20hiPROC_SHOW_BUFFER_SPv
@ Size: 0x23
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text.startup._GLOBAL__sub_I_ProcManager.cpp
@ Size: 0x54
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _GLOBAL__sub_I_ProcManager.cpp
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ LDR         R4, WORD_0044               @ LDR         R4, [PC, #44]               @ 0x0000000000000044 
    /*00000014*/ LDR         R5, WORD_0048               @ LDR         R5, [PC, #44]               @ 0x0000000000000048 
    /*00000018*/ ADD         R4, PC, R4 
    /*0000001c*/ ADD         R5, PC, R5 
    /*00000020*/ MOV         R0, R4 
    /*00000024*/ BL          _ZNSt8ios_base4InitC1Ev
    /*00000028*/ LDR         R3, WORD_004c               @ LDR         R3, [PC, #28]               @ 0x000000000000004c 
    /*0000002c*/ MOV         R0, R4 
    /*00000030*/ LDR         R2, WORD_0050               @ LDR         R2, [PC, #24]               @ 0x0000000000000050 
    /*00000034*/ LDR         R1, [R5, R3] 
    /*00000038*/ ADD         R2, PC, R2 
    /*0000003c*/ POP         {R4, R5, R6, LR} 
    _GLOBAL__sub_I_ProcManager.cpp_x40:
    /*00000040*/ B           _GLOBAL__sub_I_ProcManager.cpp_x40@ __aeabi_atexit [R_ARM_JUMP24: +0x0] 
    /*00000044*/ WORD_0044: .word 0x00000024
    /*00000048*/ WORD_0048: .word 0x00000024
    /*0000004c*/ WORD_004c: .word 0x00000000
    /*00000050*/ WORD_0050: .word 0x00000010
FUNC_END _GLOBAL__sub_I_ProcManager.cpp


