@
@ -- FILES --
@

@ SegTask.cpp


unsigned char data[0] = {
};

unsigned char bss[0];

_RODATA__ZTSN4HIRT7SEGTASKE_0000: .ascii "N4hirt7SegTaskE\0",
_RODATA__ZTSN4HIRT7SEGTASKE_0010: .ascii ""


unsigned char data.rel.ro._ZTIN4hirt7SegTaskE[8] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt7SegTaskE[16] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0x60, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0x5e, 0x01, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt7SegTaskE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt7SegTaskE[40] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0x5f, 0x01, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0x1e, 0x01, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0x26, 0x01, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0x30, 0x01, 0x00, 
    /*0020*/ 0x14, 0x00, 0x00, 0x00, 0x02, 0x18, 0x01, 0x00, 
};

unsigned char bss._ZStL8__ioinit[1];

unsigned char data.rel.ro._ZTIN4hirt10CpuSegTaskE[12] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt10CpuSegTaskE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0x6d, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0x61, 0x01, 0x00, 
    /*0010*/ 0x08, 0x00, 0x00, 0x00, 0x02, 0x5f, 0x01, 0x00, 
};

unsigned char data.rel.ro._ZTIN4hirt11NnieSegTaskE[12] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt11NnieSegTaskE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0x6d, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0x63, 0x01, 0x00, 
    /*0010*/ 0x08, 0x00, 0x00, 0x00, 0x02, 0x5f, 0x01, 0x00, 
};

unsigned char data.rel.ro._ZTIN4hirt16ConnectorSegTaskE[12] = {
    /*0000*/ 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro._ZTIN4hirt16ConnectorSegTaskE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x02, 0x6d, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00, 0x02, 0x65, 0x01, 0x00, 
    /*0010*/ 0x08, 0x00, 0x00, 0x00, 0x02, 0x5f, 0x01, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt10CpuSegTaskE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt10CpuSegTaskE[40] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0x62, 0x01, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0x2c, 0x01, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0x27, 0x01, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0x32, 0x01, 0x00, 
    /*0020*/ 0x14, 0x00, 0x00, 0x00, 0x02, 0x19, 0x01, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt11NnieSegTaskE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt11NnieSegTaskE[40] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0x64, 0x01, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0x2f, 0x01, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0x2d, 0x01, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0x1f, 0x01, 0x00, 
    /*0020*/ 0x14, 0x00, 0x00, 0x00, 0x02, 0x1a, 0x01, 0x00, 
};

unsigned char data.rel.ro.local._ZTVN4hirt16ConnectorSegTaskE[24] = {
    /*0000*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /*0010*/ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
};

unsigned char rel.data.rel.ro.local._ZTVN4hirt16ConnectorSegTaskE[40] = {
    /*0000*/ 0x04, 0x00, 0x00, 0x00, 0x02, 0x66, 0x01, 0x00, 0x08, 0x00, 0x00, 0x00, 0x02, 0x2a, 0x01, 0x00, 
    /*0010*/ 0x0c, 0x00, 0x00, 0x00, 0x02, 0x24, 0x01, 0x00, 0x10, 0x00, 0x00, 0x00, 0x02, 0x31, 0x01, 0x00, 
    /*0020*/ 0x14, 0x00, 0x00, 0x00, 0x02, 0x51, 0x01, 0x00, 
};

_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_0000: .ascii "%s:[%d], clear Hyper Param error\0\0\0\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_0024: .ascii "hirt\0\0\0\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_002c: .ascii "%s:[%d], clear cpu assist info error\0\0\0\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_0054: .ascii "%s:[%d], clear cpu src blob error\0\0\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_0078: .ascii "%s:[%d], clear cpu dst blob error\0\0\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_009c: .ascii "malloc cpu src blob fail\0\0\0\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_00b8: .ascii "%s:[%d], clear node plugin operand for src error\0\0\0\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_00ec: .ascii "malloc cpu dst blob fail\0\0\0\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_0108: .ascii "%s:[%d], clear node plugin operand for dst error\0\0\0\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_013c: .ascii "%s:[%d], copy Hyper param error\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_015c: .ascii "%s:[%d], clear node plugin for Training Param for dst error\0",
_RODATA__ZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOL_STR1_4_0198: .ascii ""


_RODATA__ZN4HIRT11NNIESEGTASK14GETSEGTASKNAMEB5CXX11EV_STR1_4_0000: .ascii "basic_string::_M_construct null not valid\0"


_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_0000: .ascii "%s:[%d], clear forward ctrl error\0\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_0024: .ascii "%s:[%d], clear forward withbbox ctrl error\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_0050: .ascii "%s:[%d], clear nnie assist info error\0\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_0078: .ascii "%s:[%d], clear nnie src blob error\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_009c: .ascii "%s:[%d], clear nnie dst blob error\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_00c0: .ascii "%s:[%d], clear nnie rpn src blob error\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_00e8: .ascii "malloc nnie src blob fail1\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_0104: .ascii "%s:[%d], clear svp nnie src blob error1\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_012c: .ascii "malloc nnie dst blob fail1\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_0148: .ascii "%s:[%d], clear svp nnie dst blob error1\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_S_STR1_4_0170: .ascii ""


_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJJPK18HISVP_NNIE_MODEL_S_STR1_4_0000: .ascii "%s:[%d], clear svp nnie forward ctrl error\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJJPK18HISVP_NNIE_MODEL_S_STR1_4_002c: .ascii "%s:[%d], clear svp nnie forward withbbox ctrl error\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJJPK18HISVP_NNIE_MODEL_S_STR1_4_0060: .ascii "malloc nnie src blob fail\0\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJJPK18HISVP_NNIE_MODEL_S_STR1_4_007c: .ascii "%s:[%d], clear svp nnie src blob error\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJJPK18HISVP_NNIE_MODEL_S_STR1_4_00a4: .ascii "malloc rpn blob fail\0\0\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJJPK18HISVP_NNIE_MODEL_S_STR1_4_00bc: .ascii "%s:[%d], clear svp nnie rpn src blob error\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJJPK18HISVP_NNIE_MODEL_S_STR1_4_00e8: .ascii "malloc nnie dst blob fail\0\0\0",
_RODATA__ZN4HIRT11NNIESEGTASK4INITEJJJPK18HISVP_NNIE_MODEL_S_STR1_4_0104: .ascii "%s:[%d], clear svp nnie dst blob error\0"


_RODATA__ZN4HIRT7SEGTASK12NOTIFYDEPENDEV_STR1_4_0000: .ascii "notifiers is null!\0"


_RODATA__ZTSN4HIRT10CPUSEGTASKE_0000: .ascii "N4hirt10CpuSegTaskE\0",
_RODATA__ZTSN4HIRT10CPUSEGTASKE_0014: .ascii ""


_RODATA__ZTSN4HIRT11NNIESEGTASKE_0000: .ascii "N4hirt11NnieSegTaskE\0"


_RODATA__ZTSN4HIRT16CONNECTORSEGTASKE_0000: .ascii "N4hirt16ConnectorSegTaskE\0"


_RODATA__ZZN4HIRT10CPUSEGTASK4INITEJJP11HINODEPARAM7HI_BOOLE12__FUNCTION___0000: .ascii "init\0"


_RODATA__ZZN4HIRT11NNIESEGTASK4INITEJJPK18HISVP_NNIE_MODEL_SE12__FUNCTION___0000: .ascii "init\0"


_RODATA__ZZN4HIRT11NNIESEGTASK4INITEJJJPK18HISVP_NNIE_MODEL_SE12__FUNCTION___0000: .ascii "init\0"


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt7SegTask16resetDstBlobsNumEv
@ Size: 0x4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt7SegTask16resetDstBlobsNumEv
    /*00000000*/ BX          LR 
FUNC_END _ZN4hirt7SegTask16resetDstBlobsNumEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10CpuSegTask16resetDstBlobsNumEv
@ Size: 0x30
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10CpuSegTask16resetDstBlobsNumEv
    /*00000000*/ LDR         R1, [R0, #108]              @ 0x6c 
    /*00000004*/ CMP         R1, #0 
    /*00000008*/ BXEQ        LR 
    /*0000000c*/ LDR         R2, [R0, #112]              @ 0x70 
    /*00000010*/ MOV         R3, #0 
    /*00000014*/ MOV         R0, R3 
    _ZN4hirt10CpuSegTask16resetDstBlobsNumEv_x18:
    /*00000018*/ STR         R0, [R2, #80]               @ 0x50 
    /*0000001c*/ ADD         R3, R3, #1 
    /*00000020*/ CMP         R3, R1 
    /*00000024*/ ADD         R2, R2, #104                @ 0x68 
    /*00000028*/ BNE         _ZN4hirt10CpuSegTask16resetDstBlobsNumEv_x18
    /*0000002c*/ BX          LR 
FUNC_END _ZN4hirt10CpuSegTask16resetDstBlobsNumEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11NnieSegTask16resetDstBlobsNumEv
@ Size: 0x30
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11NnieSegTask16resetDstBlobsNumEv
    /*00000000*/ LDR         R1, [R0, #112]              @ 0x70 
    /*00000004*/ CMP         R1, #0 
    /*00000008*/ BXEQ        LR 
    /*0000000c*/ LDR         R2, [R0, #116]              @ 0x74 
    /*00000010*/ MOV         R3, #0 
    /*00000014*/ MOV         R0, R3 
    _ZN4hirt11NnieSegTask16resetDstBlobsNumEv_x18:
    /*00000018*/ STR         R0, [R2, #24] 
    /*0000001c*/ ADD         R3, R3, #1 
    /*00000020*/ CMP         R3, R1 
    /*00000024*/ ADD         R2, R2, #48                 @ 0x30 
    /*00000028*/ BNE         _ZN4hirt11NnieSegTask16resetDstBlobsNumEv_x18
    /*0000002c*/ BX          LR 
FUNC_END _ZN4hirt11NnieSegTask16resetDstBlobsNumEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt7SegTaskD2Ev
@ Size: 0x50
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt7SegTaskD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_004c               @ LDR         R3, [PC, #52]               @ 0x000000000000004c 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #48]               @ 0x30 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ CMP         R0, #0 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R4] 
    /*0000002c*/ BEQ         _ZN4hirt7SegTaskD2Ev_x34
    /*00000030*/ BL          _ZdlPv
    _ZN4hirt7SegTaskD2Ev_x34:
    /*00000034*/ LDR         R0, [R4, #36]               @ 0x24 
    /*00000038*/ CMP         R0, #0 
    /*0000003c*/ BEQ         _ZN4hirt7SegTaskD2Ev_x44
    /*00000040*/ BL          _ZdlPv
    _ZN4hirt7SegTaskD2Ev_x44:
    /*00000044*/ MOV         R0, R4 
    /*00000048*/ POP         {R4, PC} 
    /*0000004c*/ WORD_004c: .word 0x00000028
FUNC_END _ZN4hirt7SegTaskD2Ev


FUNC_BEGIN _ZN4hirt7SegTaskD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_004c               @ LDR         R3, [PC, #52]               @ 0x000000000000004c 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #48]               @ 0x30 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ CMP         R0, #0 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R4] 
    /*0000002c*/ BEQ         _ZN4hirt7SegTaskD1Ev_x34
    /*00000030*/ BL          _ZdlPv
    _ZN4hirt7SegTaskD1Ev_x34:
    /*00000034*/ LDR         R0, [R4, #36]               @ 0x24 
    /*00000038*/ CMP         R0, #0 
    /*0000003c*/ BEQ         _ZN4hirt7SegTaskD1Ev_x44
    /*00000040*/ BL          _ZdlPv
    _ZN4hirt7SegTaskD1Ev_x44:
    /*00000044*/ MOV         R0, R4 
    /*00000048*/ POP         {R4, PC} 
    /*0000004c*/ WORD_004c: .word 0x00000028
FUNC_END _ZN4hirt7SegTaskD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev
@ Size: 0xc8
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4072]             @ 0xfe8 
    /*00000010*/ LDR         R2, [R1, #268]              @ 0x10c 
    /*00000014*/ ADD         R3, R0, #8 
    /*00000018*/ SUB         SP, SP, #8 
    /*0000001c*/ LDR         R4, [R2, #104]              @ 0x68 
    /*00000020*/ STR         R3, [R0] 
    /*00000024*/ LDR         R6, [R2, #100]              @ 0x64 
    /*00000028*/ RSB         R1, R4, #0 
    /*0000002c*/ CLZ         R2, R6 
    /*00000030*/ CMP         R6, R1 
    /*00000034*/ LSR         R2, R2, #5 
    /*00000038*/ MOVEQ       R2, #0 
    /*0000003c*/ CMP         R2, #0 
    /*00000040*/ BEQ         _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_x50
    /*00000044*/ LDR         R0, WORD_00c4               @ LDR         R0, [PC, #120]              @ 0x00000000000000c4 
    /*00000048*/ ADD         R0, PC, R0 
    /*0000004c*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_x50:
    /*00000050*/ STR         R4, [SP, #4] 
    /*00000054*/ CMP         R4, #15 
    /*00000058*/ MOV         R5, R0 
    /*0000005c*/ BHI         _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_x90
    /*00000060*/ CMP         R4, #1 
    /*00000064*/ LDRBEQ      R2, [R6] 
    /*00000068*/ STRBEQ      R2, [R5, #8] 
    /*0000006c*/ BEQ         _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_x78
    /*00000070*/ CMP         R4, #0 
    /*00000074*/ BNE         _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_xbc
    _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_x78:
    /*00000078*/ STR         R4, [R5, #4] 
    /*0000007c*/ MOV         R2, #0 
    /*00000080*/ STRB        R2, [R3, R4] 
    /*00000084*/ MOV         R0, R5 
    /*00000088*/ ADD         SP, SP, #8 
    /*0000008c*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_x90:
    /*00000090*/ ADD         R1, SP, #4 
    /*00000094*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*00000098*/ LDR         R3, [SP, #4] 
    /*0000009c*/ STR         R0, [R5] 
    /*000000a0*/ STR         R3, [R5, #8] 
    _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_xa4:
    /*000000a4*/ MOV         R2, R4 
    /*000000a8*/ MOV         R1, R6 
    /*000000ac*/ BL          memcpy
    /*000000b0*/ LDR         R4, [SP, #4] 
    /*000000b4*/ LDR         R3, [R5] 
    /*000000b8*/ B           _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_x78
    _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_xbc:
    /*000000bc*/ MOV         R0, R3 
    /*000000c0*/ B           _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev_xa4
    /*000000c4*/ WORD_00c4: .word 0x00000074
FUNC_END _ZN4hirt11NnieSegTask14getSegTaskNameB5cxx11Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt16ConnectorSegTaskD0Ev
@ Size: 0x84
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt16ConnectorSegTaskD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_007c               @ LDR         R3, [PC, #100]              @ 0x000000000000007c 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #120]              @ 0x78 
    /*0000001c*/ ADD         R2, R4, #128                @ 0x80 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ CMP         R0, R2 
    /*00000028*/ ADD         R3, R3, #8 
    /*0000002c*/ STR         R3, [R4] 
    /*00000030*/ BEQ         _ZN4hirt16ConnectorSegTaskD0Ev_x38
    /*00000034*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskD0Ev_x38:
    /*00000038*/ LDR         R0, [R4, #48]               @ 0x30 
    /*0000003c*/ LDR         R3, WORD_0080               @ LDR         R3, [PC, #60]               @ 0x0000000000000080 
    /*00000040*/ CMP         R0, #0 
    /*00000044*/ ADD         R3, PC, R3 
    /*00000048*/ ADD         R3, R3, #8 
    /*0000004c*/ STR         R3, [R4] 
    /*00000050*/ BEQ         _ZN4hirt16ConnectorSegTaskD0Ev_x58
    /*00000054*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskD0Ev_x58:
    /*00000058*/ LDR         R0, [R4, #36]               @ 0x24 
    /*0000005c*/ CMP         R0, #0 
    /*00000060*/ BEQ         _ZN4hirt16ConnectorSegTaskD0Ev_x68
    /*00000064*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskD0Ev_x68:
    /*00000068*/ MOV         R0, R4 
    /*0000006c*/ MOV         R1, #144                    @ 0x90 
    /*00000070*/ BL          _ZdlPvj
    /*00000074*/ MOV         R0, R4 
    /*00000078*/ POP         {R4, PC} 
    /*0000007c*/ WORD_007c: .word 0x00000054
    /*00000080*/ WORD_0080: .word 0x00000034
FUNC_END _ZN4hirt16ConnectorSegTaskD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt7SegTaskD0Ev
@ Size: 0x5c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt7SegTaskD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0058               @ LDR         R3, [PC, #64]               @ 0x0000000000000058 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #48]               @ 0x30 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ CMP         R0, #0 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R4] 
    /*0000002c*/ BEQ         _ZN4hirt7SegTaskD0Ev_x34
    /*00000030*/ BL          _ZdlPv
    _ZN4hirt7SegTaskD0Ev_x34:
    /*00000034*/ LDR         R0, [R4, #36]               @ 0x24 
    /*00000038*/ CMP         R0, #0 
    /*0000003c*/ BEQ         _ZN4hirt7SegTaskD0Ev_x44
    /*00000040*/ BL          _ZdlPv
    _ZN4hirt7SegTaskD0Ev_x44:
    /*00000044*/ MOV         R0, R4 
    /*00000048*/ MOV         R1, #96                     @ 0x60 
    /*0000004c*/ BL          _ZdlPvj
    /*00000050*/ MOV         R0, R4 
    /*00000054*/ POP         {R4, PC} 
    /*00000058*/ WORD_0058: .word 0x00000034
FUNC_END _ZN4hirt7SegTaskD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10CpuSegTaskD0Ev
@ Size: 0xa0
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10CpuSegTaskD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0098               @ LDR         R3, [PC, #128]              @ 0x0000000000000098 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #104]              @ 0x68 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ CMP         R0, #0 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R4] 
    /*0000002c*/ BEQ         _ZN4hirt10CpuSegTaskD0Ev_x3c
    /*00000030*/ BL          free
    /*00000034*/ MOV         R3, #0 
    /*00000038*/ STR         R3, [R4, #104]              @ 0x68 
    _ZN4hirt10CpuSegTaskD0Ev_x3c:
    /*0000003c*/ LDR         R0, [R4, #112]              @ 0x70 
    /*00000040*/ CMP         R0, #0 
    /*00000044*/ BEQ         _ZN4hirt10CpuSegTaskD0Ev_x54
    /*00000048*/ BL          free
    /*0000004c*/ MOV         R3, #0 
    /*00000050*/ STR         R3, [R4, #112]              @ 0x70 
    _ZN4hirt10CpuSegTaskD0Ev_x54:
    /*00000054*/ LDR         R0, [R4, #48]               @ 0x30 
    /*00000058*/ LDR         R3, WORD_009c               @ LDR         R3, [PC, #60]               @ 0x000000000000009c 
    /*0000005c*/ CMP         R0, #0 
    /*00000060*/ ADD         R3, PC, R3 
    /*00000064*/ ADD         R3, R3, #8 
    /*00000068*/ STR         R3, [R4] 
    /*0000006c*/ BEQ         _ZN4hirt10CpuSegTaskD0Ev_x74
    /*00000070*/ BL          _ZdlPv
    _ZN4hirt10CpuSegTaskD0Ev_x74:
    /*00000074*/ LDR         R0, [R4, #36]               @ 0x24 
    /*00000078*/ CMP         R0, #0 
    /*0000007c*/ BEQ         _ZN4hirt10CpuSegTaskD0Ev_x84
    /*00000080*/ BL          _ZdlPv
    _ZN4hirt10CpuSegTaskD0Ev_x84:
    /*00000084*/ MOV         R0, R4 
    /*00000088*/ MOV         R1, #192                    @ 0xc0 
    /*0000008c*/ BL          _ZdlPvj
    /*00000090*/ MOV         R0, R4 
    /*00000094*/ POP         {R4, PC} 
    /*00000098*/ WORD_0098: .word 0x00000074
    /*0000009c*/ WORD_009c: .word 0x00000034
FUNC_END _ZN4hirt10CpuSegTaskD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt16ConnectorSegTaskD2Ev
@ Size: 0x78
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt16ConnectorSegTaskD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0070               @ LDR         R3, [PC, #88]               @ 0x0000000000000070 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #120]              @ 0x78 
    /*0000001c*/ ADD         R2, R4, #128                @ 0x80 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ CMP         R0, R2 
    /*00000028*/ ADD         R3, R3, #8 
    /*0000002c*/ STR         R3, [R4] 
    /*00000030*/ BEQ         _ZN4hirt16ConnectorSegTaskD2Ev_x38
    /*00000034*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskD2Ev_x38:
    /*00000038*/ LDR         R0, [R4, #48]               @ 0x30 
    /*0000003c*/ LDR         R3, WORD_0074               @ LDR         R3, [PC, #48]               @ 0x0000000000000074 
    /*00000040*/ CMP         R0, #0 
    /*00000044*/ ADD         R3, PC, R3 
    /*00000048*/ ADD         R3, R3, #8 
    /*0000004c*/ STR         R3, [R4] 
    /*00000050*/ BEQ         _ZN4hirt16ConnectorSegTaskD2Ev_x58
    /*00000054*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskD2Ev_x58:
    /*00000058*/ LDR         R0, [R4, #36]               @ 0x24 
    /*0000005c*/ CMP         R0, #0 
    /*00000060*/ BEQ         _ZN4hirt16ConnectorSegTaskD2Ev_x68
    /*00000064*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskD2Ev_x68:
    /*00000068*/ MOV         R0, R4 
    /*0000006c*/ POP         {R4, PC} 
    /*00000070*/ WORD_0070: .word 0x00000048
    /*00000074*/ WORD_0074: .word 0x00000028
FUNC_END _ZN4hirt16ConnectorSegTaskD2Ev


FUNC_BEGIN _ZN4hirt16ConnectorSegTaskD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_0070               @ LDR         R3, [PC, #88]               @ 0x0000000000000070 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #120]              @ 0x78 
    /*0000001c*/ ADD         R2, R4, #128                @ 0x80 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ CMP         R0, R2 
    /*00000028*/ ADD         R3, R3, #8 
    /*0000002c*/ STR         R3, [R4] 
    /*00000030*/ BEQ         _ZN4hirt16ConnectorSegTaskD1Ev_x38
    /*00000034*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskD1Ev_x38:
    /*00000038*/ LDR         R0, [R4, #48]               @ 0x30 
    /*0000003c*/ LDR         R3, WORD_0074               @ LDR         R3, [PC, #48]               @ 0x0000000000000074 
    /*00000040*/ CMP         R0, #0 
    /*00000044*/ ADD         R3, PC, R3 
    /*00000048*/ ADD         R3, R3, #8 
    /*0000004c*/ STR         R3, [R4] 
    /*00000050*/ BEQ         _ZN4hirt16ConnectorSegTaskD1Ev_x58
    /*00000054*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskD1Ev_x58:
    /*00000058*/ LDR         R0, [R4, #36]               @ 0x24 
    /*0000005c*/ CMP         R0, #0 
    /*00000060*/ BEQ         _ZN4hirt16ConnectorSegTaskD1Ev_x68
    /*00000064*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskD1Ev_x68:
    /*00000068*/ MOV         R0, R4 
    /*0000006c*/ POP         {R4, PC} 
    /*00000070*/ WORD_0070: .word 0x00000048
    /*00000074*/ WORD_0074: .word 0x00000028
FUNC_END _ZN4hirt16ConnectorSegTaskD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10CpuSegTaskD2Ev
@ Size: 0x94
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10CpuSegTaskD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_008c               @ LDR         R3, [PC, #116]              @ 0x000000000000008c 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #104]              @ 0x68 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ CMP         R0, #0 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R4] 
    /*0000002c*/ BEQ         _ZN4hirt10CpuSegTaskD2Ev_x3c
    /*00000030*/ BL          free
    /*00000034*/ MOV         R3, #0 
    /*00000038*/ STR         R3, [R4, #104]              @ 0x68 
    _ZN4hirt10CpuSegTaskD2Ev_x3c:
    /*0000003c*/ LDR         R0, [R4, #112]              @ 0x70 
    /*00000040*/ CMP         R0, #0 
    /*00000044*/ BEQ         _ZN4hirt10CpuSegTaskD2Ev_x54
    /*00000048*/ BL          free
    /*0000004c*/ MOV         R3, #0 
    /*00000050*/ STR         R3, [R4, #112]              @ 0x70 
    _ZN4hirt10CpuSegTaskD2Ev_x54:
    /*00000054*/ LDR         R0, [R4, #48]               @ 0x30 
    /*00000058*/ LDR         R3, WORD_0090               @ LDR         R3, [PC, #48]               @ 0x0000000000000090 
    /*0000005c*/ CMP         R0, #0 
    /*00000060*/ ADD         R3, PC, R3 
    /*00000064*/ ADD         R3, R3, #8 
    /*00000068*/ STR         R3, [R4] 
    /*0000006c*/ BEQ         _ZN4hirt10CpuSegTaskD2Ev_x74
    /*00000070*/ BL          _ZdlPv
    _ZN4hirt10CpuSegTaskD2Ev_x74:
    /*00000074*/ LDR         R0, [R4, #36]               @ 0x24 
    /*00000078*/ CMP         R0, #0 
    /*0000007c*/ BEQ         _ZN4hirt10CpuSegTaskD2Ev_x84
    /*00000080*/ BL          _ZdlPv
    _ZN4hirt10CpuSegTaskD2Ev_x84:
    /*00000084*/ MOV         R0, R4 
    /*00000088*/ POP         {R4, PC} 
    /*0000008c*/ WORD_008c: .word 0x00000068
    /*00000090*/ WORD_0090: .word 0x00000028
FUNC_END _ZN4hirt10CpuSegTaskD2Ev


FUNC_BEGIN _ZN4hirt10CpuSegTaskD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_008c               @ LDR         R3, [PC, #116]              @ 0x000000000000008c 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #104]              @ 0x68 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ CMP         R0, #0 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R4] 
    /*0000002c*/ BEQ         _ZN4hirt10CpuSegTaskD1Ev_x3c
    /*00000030*/ BL          free
    /*00000034*/ MOV         R3, #0 
    /*00000038*/ STR         R3, [R4, #104]              @ 0x68 
    _ZN4hirt10CpuSegTaskD1Ev_x3c:
    /*0000003c*/ LDR         R0, [R4, #112]              @ 0x70 
    /*00000040*/ CMP         R0, #0 
    /*00000044*/ BEQ         _ZN4hirt10CpuSegTaskD1Ev_x54
    /*00000048*/ BL          free
    /*0000004c*/ MOV         R3, #0 
    /*00000050*/ STR         R3, [R4, #112]              @ 0x70 
    _ZN4hirt10CpuSegTaskD1Ev_x54:
    /*00000054*/ LDR         R0, [R4, #48]               @ 0x30 
    /*00000058*/ LDR         R3, WORD_0090               @ LDR         R3, [PC, #48]               @ 0x0000000000000090 
    /*0000005c*/ CMP         R0, #0 
    /*00000060*/ ADD         R3, PC, R3 
    /*00000064*/ ADD         R3, R3, #8 
    /*00000068*/ STR         R3, [R4] 
    /*0000006c*/ BEQ         _ZN4hirt10CpuSegTaskD1Ev_x74
    /*00000070*/ BL          _ZdlPv
    _ZN4hirt10CpuSegTaskD1Ev_x74:
    /*00000074*/ LDR         R0, [R4, #36]               @ 0x24 
    /*00000078*/ CMP         R0, #0 
    /*0000007c*/ BEQ         _ZN4hirt10CpuSegTaskD1Ev_x84
    /*00000080*/ BL          _ZdlPv
    _ZN4hirt10CpuSegTaskD1Ev_x84:
    /*00000084*/ MOV         R0, R4 
    /*00000088*/ POP         {R4, PC} 
    /*0000008c*/ WORD_008c: .word 0x00000068
    /*00000090*/ WORD_0090: .word 0x00000028
FUNC_END _ZN4hirt10CpuSegTaskD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11NnieSegTaskD0Ev
@ Size: 0xb8
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11NnieSegTaskD0Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_00b0               @ LDR         R3, [PC, #152]              @ 0x00000000000000b0 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #100]              @ 0x64 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ CMP         R0, #0 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R4] 
    /*0000002c*/ BEQ         _ZN4hirt11NnieSegTaskD0Ev_x3c
    /*00000030*/ BL          free
    /*00000034*/ MOV         R3, #0 
    /*00000038*/ STR         R3, [R4, #100]              @ 0x64 
    _ZN4hirt11NnieSegTaskD0Ev_x3c:
    /*0000003c*/ LDR         R0, [R4, #108]              @ 0x6c 
    /*00000040*/ CMP         R0, #0 
    /*00000044*/ BEQ         _ZN4hirt11NnieSegTaskD0Ev_x54
    /*00000048*/ BL          free
    /*0000004c*/ MOV         R3, #0 
    /*00000050*/ STR         R3, [R4, #108]              @ 0x6c 
    _ZN4hirt11NnieSegTaskD0Ev_x54:
    /*00000054*/ LDR         R0, [R4, #116]              @ 0x74 
    /*00000058*/ CMP         R0, #0 
    /*0000005c*/ BEQ         _ZN4hirt11NnieSegTaskD0Ev_x6c
    /*00000060*/ BL          free
    /*00000064*/ MOV         R3, #0 
    /*00000068*/ STR         R3, [R4, #116]              @ 0x74 
    _ZN4hirt11NnieSegTaskD0Ev_x6c:
    /*0000006c*/ LDR         R0, [R4, #48]               @ 0x30 
    /*00000070*/ LDR         R3, WORD_00b4               @ LDR         R3, [PC, #60]               @ 0x00000000000000b4 
    /*00000074*/ CMP         R0, #0 
    /*00000078*/ ADD         R3, PC, R3 
    /*0000007c*/ ADD         R3, R3, #8 
    /*00000080*/ STR         R3, [R4] 
    /*00000084*/ BEQ         _ZN4hirt11NnieSegTaskD0Ev_x8c
    /*00000088*/ BL          _ZdlPv
    _ZN4hirt11NnieSegTaskD0Ev_x8c:
    /*0000008c*/ LDR         R0, [R4, #36]               @ 0x24 
    /*00000090*/ CMP         R0, #0 
    /*00000094*/ BEQ         _ZN4hirt11NnieSegTaskD0Ev_x9c
    /*00000098*/ BL          _ZdlPv
    _ZN4hirt11NnieSegTaskD0Ev_x9c:
    /*0000009c*/ MOV         R0, R4 
    /*000000a0*/ MOV         R1, #448                    @ 0x1c0 
    /*000000a4*/ BL          _ZdlPvj
    /*000000a8*/ MOV         R0, R4 
    /*000000ac*/ POP         {R4, PC} 
    /*000000b0*/ WORD_00b0: .word 0x0000008c
    /*000000b4*/ WORD_00b4: .word 0x00000034
FUNC_END _ZN4hirt11NnieSegTaskD0Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11NnieSegTaskD2Ev
@ Size: 0xac
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11NnieSegTaskD2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_00a4               @ LDR         R3, [PC, #140]              @ 0x00000000000000a4 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #100]              @ 0x64 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ CMP         R0, #0 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R4] 
    /*0000002c*/ BEQ         _ZN4hirt11NnieSegTaskD2Ev_x3c
    /*00000030*/ BL          free
    /*00000034*/ MOV         R3, #0 
    /*00000038*/ STR         R3, [R4, #100]              @ 0x64 
    _ZN4hirt11NnieSegTaskD2Ev_x3c:
    /*0000003c*/ LDR         R0, [R4, #108]              @ 0x6c 
    /*00000040*/ CMP         R0, #0 
    /*00000044*/ BEQ         _ZN4hirt11NnieSegTaskD2Ev_x54
    /*00000048*/ BL          free
    /*0000004c*/ MOV         R3, #0 
    /*00000050*/ STR         R3, [R4, #108]              @ 0x6c 
    _ZN4hirt11NnieSegTaskD2Ev_x54:
    /*00000054*/ LDR         R0, [R4, #116]              @ 0x74 
    /*00000058*/ CMP         R0, #0 
    /*0000005c*/ BEQ         _ZN4hirt11NnieSegTaskD2Ev_x6c
    /*00000060*/ BL          free
    /*00000064*/ MOV         R3, #0 
    /*00000068*/ STR         R3, [R4, #116]              @ 0x74 
    _ZN4hirt11NnieSegTaskD2Ev_x6c:
    /*0000006c*/ LDR         R0, [R4, #48]               @ 0x30 
    /*00000070*/ LDR         R3, WORD_00a8               @ LDR         R3, [PC, #48]               @ 0x00000000000000a8 
    /*00000074*/ CMP         R0, #0 
    /*00000078*/ ADD         R3, PC, R3 
    /*0000007c*/ ADD         R3, R3, #8 
    /*00000080*/ STR         R3, [R4] 
    /*00000084*/ BEQ         _ZN4hirt11NnieSegTaskD2Ev_x8c
    /*00000088*/ BL          _ZdlPv
    _ZN4hirt11NnieSegTaskD2Ev_x8c:
    /*0000008c*/ LDR         R0, [R4, #36]               @ 0x24 
    /*00000090*/ CMP         R0, #0 
    /*00000094*/ BEQ         _ZN4hirt11NnieSegTaskD2Ev_x9c
    /*00000098*/ BL          _ZdlPv
    _ZN4hirt11NnieSegTaskD2Ev_x9c:
    /*0000009c*/ MOV         R0, R4 
    /*000000a0*/ POP         {R4, PC} 
    /*000000a4*/ WORD_00a4: .word 0x00000080
    /*000000a8*/ WORD_00a8: .word 0x00000028
FUNC_END _ZN4hirt11NnieSegTaskD2Ev


FUNC_BEGIN _ZN4hirt11NnieSegTaskD1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ LDR         R3, WORD_00a4               @ LDR         R3, [PC, #140]              @ 0x00000000000000a4 
    /*00000014*/ MOV         R4, R0 
    /*00000018*/ LDR         R0, [R0, #100]              @ 0x64 
    /*0000001c*/ ADD         R3, PC, R3 
    /*00000020*/ CMP         R0, #0 
    /*00000024*/ ADD         R3, R3, #8 
    /*00000028*/ STR         R3, [R4] 
    /*0000002c*/ BEQ         _ZN4hirt11NnieSegTaskD1Ev_x3c
    /*00000030*/ BL          free
    /*00000034*/ MOV         R3, #0 
    /*00000038*/ STR         R3, [R4, #100]              @ 0x64 
    _ZN4hirt11NnieSegTaskD1Ev_x3c:
    /*0000003c*/ LDR         R0, [R4, #108]              @ 0x6c 
    /*00000040*/ CMP         R0, #0 
    /*00000044*/ BEQ         _ZN4hirt11NnieSegTaskD1Ev_x54
    /*00000048*/ BL          free
    /*0000004c*/ MOV         R3, #0 
    /*00000050*/ STR         R3, [R4, #108]              @ 0x6c 
    _ZN4hirt11NnieSegTaskD1Ev_x54:
    /*00000054*/ LDR         R0, [R4, #116]              @ 0x74 
    /*00000058*/ CMP         R0, #0 
    /*0000005c*/ BEQ         _ZN4hirt11NnieSegTaskD1Ev_x6c
    /*00000060*/ BL          free
    /*00000064*/ MOV         R3, #0 
    /*00000068*/ STR         R3, [R4, #116]              @ 0x74 
    _ZN4hirt11NnieSegTaskD1Ev_x6c:
    /*0000006c*/ LDR         R0, [R4, #48]               @ 0x30 
    /*00000070*/ LDR         R3, WORD_00a8               @ LDR         R3, [PC, #48]               @ 0x00000000000000a8 
    /*00000074*/ CMP         R0, #0 
    /*00000078*/ ADD         R3, PC, R3 
    /*0000007c*/ ADD         R3, R3, #8 
    /*00000080*/ STR         R3, [R4] 
    /*00000084*/ BEQ         _ZN4hirt11NnieSegTaskD1Ev_x8c
    /*00000088*/ BL          _ZdlPv
    _ZN4hirt11NnieSegTaskD1Ev_x8c:
    /*0000008c*/ LDR         R0, [R4, #36]               @ 0x24 
    /*00000090*/ CMP         R0, #0 
    /*00000094*/ BEQ         _ZN4hirt11NnieSegTaskD1Ev_x9c
    /*00000098*/ BL          _ZdlPv
    _ZN4hirt11NnieSegTaskD1Ev_x9c:
    /*0000009c*/ MOV         R0, R4 
    /*000000a0*/ POP         {R4, PC} 
    /*000000a4*/ WORD_00a4: .word 0x00000080
    /*000000a8*/ WORD_00a8: .word 0x00000028
FUNC_END _ZN4hirt11NnieSegTaskD1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt7SegTask14getSegTaskNameB5cxx11Ev
@ Size: 0x18
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt7SegTask14getSegTaskNameB5cxx11Ev
    /*00000000*/ MOV         R2, #0 
    /*00000004*/ ADD         R1, R0, #8 
    /*00000008*/ STR         R2, [R0, #4] 
    /*0000000c*/ STR         R1, [R0] 
    /*00000010*/ STRB        R2, [R0, #8] 
    /*00000014*/ BX          LR 
FUNC_END _ZN4hirt7SegTask14getSegTaskNameB5cxx11Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev
@ Size: 0xc4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4072]             @ 0xfe8 
    /*00000010*/ LDR         R4, [R1, #124]              @ 0x7c 
    /*00000014*/ ADD         R3, R0, #8 
    /*00000018*/ STR         R3, [R0] 
    /*0000001c*/ SUB         SP, SP, #8 
    /*00000020*/ LDR         R6, [R1, #120]              @ 0x78 
    /*00000024*/ RSB         IP, R4, #0 
    /*00000028*/ CLZ         R2, R6 
    /*0000002c*/ CMP         R6, IP 
    /*00000030*/ LSR         R2, R2, #5 
    /*00000034*/ MOVEQ       R2, #0 
    /*00000038*/ CMP         R2, #0 
    /*0000003c*/ BEQ         _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_x4c
    /*00000040*/ LDR         R0, WORD_00c0               @ LDR         R0, [PC, #120]              @ 0x00000000000000c0 
    /*00000044*/ ADD         R0, PC, R0 
    /*00000048*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_x4c:
    /*0000004c*/ STR         R4, [SP, #4] 
    /*00000050*/ CMP         R4, #15 
    /*00000054*/ MOV         R5, R0 
    /*00000058*/ BHI         _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_x8c
    /*0000005c*/ CMP         R4, #1 
    /*00000060*/ LDRBEQ      R2, [R6] 
    /*00000064*/ STRBEQ      R2, [R5, #8] 
    /*00000068*/ BEQ         _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_x74
    /*0000006c*/ CMP         R4, #0 
    /*00000070*/ BNE         _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_xb8
    _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_x74:
    /*00000074*/ STR         R4, [R5, #4] 
    /*00000078*/ MOV         R2, #0 
    /*0000007c*/ STRB        R2, [R3, R4] 
    /*00000080*/ MOV         R0, R5 
    /*00000084*/ ADD         SP, SP, #8 
    /*00000088*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_x8c:
    /*0000008c*/ ADD         R1, SP, #4 
    /*00000090*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*00000094*/ LDR         R3, [SP, #4] 
    /*00000098*/ STR         R0, [R5] 
    /*0000009c*/ STR         R3, [R5, #8] 
    _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_xa0:
    /*000000a0*/ MOV         R2, R4 
    /*000000a4*/ MOV         R1, R6 
    /*000000a8*/ BL          memcpy
    /*000000ac*/ LDR         R4, [SP, #4] 
    /*000000b0*/ LDR         R3, [R5] 
    /*000000b4*/ B           _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_x74
    _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_xb8:
    /*000000b8*/ MOV         R0, R3 
    /*000000bc*/ B           _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev_xa0
    /*000000c0*/ WORD_00c0: .word 0x00000074
FUNC_END _ZN4hirt16ConnectorSegTask14getSegTaskNameB5cxx11Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev
@ Size: 0xc8
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4072]             @ 0xfe8 
    /*00000010*/ LDR         R2, [R1, #140]              @ 0x8c 
    /*00000014*/ ADD         R3, R0, #8 
    /*00000018*/ SUB         SP, SP, #8 
    /*0000001c*/ LDR         R4, [R2, #104]              @ 0x68 
    /*00000020*/ STR         R3, [R0] 
    /*00000024*/ LDR         R6, [R2, #100]              @ 0x64 
    /*00000028*/ RSB         R1, R4, #0 
    /*0000002c*/ CLZ         R2, R6 
    /*00000030*/ CMP         R6, R1 
    /*00000034*/ LSR         R2, R2, #5 
    /*00000038*/ MOVEQ       R2, #0 
    /*0000003c*/ CMP         R2, #0 
    /*00000040*/ BEQ         _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_x50
    /*00000044*/ LDR         R0, WORD_00c4               @ LDR         R0, [PC, #120]              @ 0x00000000000000c4 
    /*00000048*/ ADD         R0, PC, R0 
    /*0000004c*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_x50:
    /*00000050*/ STR         R4, [SP, #4] 
    /*00000054*/ CMP         R4, #15 
    /*00000058*/ MOV         R5, R0 
    /*0000005c*/ BHI         _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_x90
    /*00000060*/ CMP         R4, #1 
    /*00000064*/ LDRBEQ      R2, [R6] 
    /*00000068*/ STRBEQ      R2, [R5, #8] 
    /*0000006c*/ BEQ         _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_x78
    /*00000070*/ CMP         R4, #0 
    /*00000074*/ BNE         _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_xbc
    _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_x78:
    /*00000078*/ STR         R4, [R5, #4] 
    /*0000007c*/ MOV         R2, #0 
    /*00000080*/ STRB        R2, [R3, R4] 
    /*00000084*/ MOV         R0, R5 
    /*00000088*/ ADD         SP, SP, #8 
    /*0000008c*/ POP         {R4, R5, R6, PC} 
    _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_x90:
    /*00000090*/ ADD         R1, SP, #4 
    /*00000094*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*00000098*/ LDR         R3, [SP, #4] 
    /*0000009c*/ STR         R0, [R5] 
    /*000000a0*/ STR         R3, [R5, #8] 
    _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_xa4:
    /*000000a4*/ MOV         R2, R4 
    /*000000a8*/ MOV         R1, R6 
    /*000000ac*/ BL          memcpy
    /*000000b0*/ LDR         R4, [SP, #4] 
    /*000000b4*/ LDR         R3, [R5] 
    /*000000b8*/ B           _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_x78
    _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_xbc:
    /*000000bc*/ MOV         R0, R3 
    /*000000c0*/ B           _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev_xa4
    /*000000c4*/ WORD_00c4: .word 0x00000074
FUNC_END _ZN4hirt10CpuSegTask14getSegTaskNameB5cxx11Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL
@ Size: 0x3b4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4048]             @ 0xfd0 
    /*00000010*/ SUB         SP, SP, #12 
    /*00000014*/ MOV         R9, R3 
    /*00000018*/ ADD         R6, R0, #116                @ 0x74 
    /*0000001c*/ MOV         R3, #8 
    /*00000020*/ LDR         IP, [SP, #48]               @ 0x30 
    /*00000024*/ MOV         R5, R0 
    /*00000028*/ MOV         R7, R1 
    /*0000002c*/ MOV         R8, R2 
    /*00000030*/ STR         IP, [R0, #96]               @ 0x60 
    /*00000034*/ MOV         R1, R3 
    /*00000038*/ MOV         R0, R6 
    /*0000003c*/ MOV         R2, #0 
    /*00000040*/ BL          memset_s
    /*00000044*/ SUBS        R4, R0, #0 
    /*00000048*/ BNE         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x160
    /*0000004c*/ MOV         R3, #56                     @ 0x38 
    /*00000050*/ MOV         R2, R4 
    /*00000054*/ MOV         R1, R3 
    /*00000058*/ ADD         R0, R5, #136                @ 0x88 
    /*0000005c*/ BL          memset_s
    /*00000060*/ SUBS        SL, R0, #0 
    /*00000064*/ BNE         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x130
    /*00000068*/ MOV         R3, #8 
    /*0000006c*/ MOV         R2, SL 
    /*00000070*/ MOV         R1, R3 
    /*00000074*/ ADD         R0, R5, #100                @ 0x64 
    /*00000078*/ BL          memset_s
    /*0000007c*/ SUBS        R4, R0, #0 
    /*00000080*/ BNE         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x190
    /*00000084*/ MOV         R3, #8 
    /*00000088*/ MOV         R2, R4 
    /*0000008c*/ MOV         R1, R3 
    /*00000090*/ ADD         R0, R5, #108                @ 0x6c 
    /*00000094*/ BL          memset_s
    /*00000098*/ SUBS        SL, R0, #0 
    /*0000009c*/ BNE         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x23c
    /*000000a0*/ CMP         R7, #0 
    /*000000a4*/ BNE         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x1c0
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_xa8:
    /*000000a8*/ CMP         R8, #0 
    /*000000ac*/ BNE         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x288
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_xb0:
    /*000000b0*/ CMP         R9, #0 
    /*000000b4*/ BEQ         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_xd4
    /*000000b8*/ MOV         R3, #8 
    /*000000bc*/ MOV         R2, R9 
    /*000000c0*/ MOV         R0, R6 
    /*000000c4*/ MOV         R1, R3 
    /*000000c8*/ BL          memcpy_s
    /*000000cc*/ CMP         R0, #0 
    /*000000d0*/ BNE         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x300
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_xd4:
    /*000000d4*/ MOV         R3, #8 
    /*000000d8*/ MOV         R2, #0 
    /*000000dc*/ MOV         R1, R3 
    /*000000e0*/ ADD         R0, R5, #124                @ 0x7c 
    /*000000e4*/ BL          memset_s
    /*000000e8*/ CMP         R0, #0 
    /*000000ec*/ MOVEQ       R0, #1 
    /*000000f0*/ BEQ         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x158
    /*000000f4*/ STR         R0, [SP] 
    /*000000f8*/ MOV         R1, #4 
    /*000000fc*/ LDR         R3, WORD_0344               @ LDR         R3, [PC, #576]              @ 0x0000000000000344 
    /*00000100*/ LDR         R2, WORD_0348               @ LDR         R2, [PC, #576]              @ 0x0000000000000348 
    /*00000104*/ LDR         R0, WORD_034c               @ LDR         R0, [PC, #576]              @ 0x000000000000034c 
    /*00000108*/ ADD         R3, PC, R3 
    /*0000010c*/ ADD         R2, PC, R2 
    /*00000110*/ ADD         R0, PC, R0 
    /*00000114*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x118:
    /*00000118*/ CMP         R8, #0 
    /*0000011c*/ BNE         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x2e4
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x120:
    /*00000120*/ CMP         R7, #0 
    /*00000124*/ BNE         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x220
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x128:
    /*00000128*/ MOV         R0, #0 
    /*0000012c*/ B           _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x158
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x130:
    /*00000130*/ LDR         R3, WORD_0350               @ LDR         R3, [PC, #536]              @ 0x0000000000000350 
    /*00000134*/ MOV         R1, #4 
    /*00000138*/ LDR         R2, WORD_0354               @ LDR         R2, [PC, #532]              @ 0x0000000000000354 
    /*0000013c*/ LDR         R0, WORD_0358               @ LDR         R0, [PC, #532]              @ 0x0000000000000358 
    /*00000140*/ STR         SL, [SP] 
    /*00000144*/ ADD         R3, PC, R3 
    /*00000148*/ ADD         R2, PC, R2 
    /*0000014c*/ ADD         R0, PC, R0 
    /*00000150*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000154*/ MOV         R0, R4 
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x158:
    /*00000158*/ ADD         SP, SP, #12 
    /*0000015c*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x160:
    /*00000160*/ LDR         R3, WORD_035c               @ LDR         R3, [PC, #500]              @ 0x000000000000035c 
    /*00000164*/ MOV         R1, #4 
    /*00000168*/ LDR         R2, WORD_0360               @ LDR         R2, [PC, #496]              @ 0x0000000000000360 
    /*0000016c*/ LDR         R0, WORD_0364               @ LDR         R0, [PC, #496]              @ 0x0000000000000364 
    /*00000170*/ STR         R4, [SP] 
    /*00000174*/ ADD         R3, PC, R3 
    /*00000178*/ ADD         R2, PC, R2 
    /*0000017c*/ ADD         R0, PC, R0 
    /*00000180*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000184*/ MOV         R0, #0 
    /*00000188*/ ADD         SP, SP, #12 
    /*0000018c*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x190:
    /*00000190*/ LDR         R3, WORD_0368               @ LDR         R3, [PC, #464]              @ 0x0000000000000368 
    /*00000194*/ MOV         R1, #4 
    /*00000198*/ LDR         R2, WORD_036c               @ LDR         R2, [PC, #460]              @ 0x000000000000036c 
    /*0000019c*/ LDR         R0, WORD_0370               @ LDR         R0, [PC, #460]              @ 0x0000000000000370 
    /*000001a0*/ STR         R4, [SP] 
    /*000001a4*/ ADD         R3, PC, R3 
    /*000001a8*/ ADD         R2, PC, R2 
    /*000001ac*/ ADD         R0, PC, R0 
    /*000001b0*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000001b4*/ MOV         R0, SL 
    /*000001b8*/ ADD         SP, SP, #12 
    /*000001bc*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x1c0:
    /*000001c0*/ MOV         FP, #104                    @ 0x68 
    /*000001c4*/ MUL         FP, FP, R7 
    /*000001c8*/ MOV         R0, FP 
    /*000001cc*/ BL          malloc
    /*000001d0*/ STR         R0, [R5, #104]              @ 0x68 
    /*000001d4*/ CMP         R0, #0 
    /*000001d8*/ MOV         R4, R0 
    /*000001dc*/ BEQ         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x268
    /*000001e0*/ MOV         R2, SL 
    /*000001e4*/ MOV         R3, FP 
    /*000001e8*/ MOV         R1, FP 
    /*000001ec*/ BL          memset_s
    /*000001f0*/ CMP         R0, #0 
    /*000001f4*/ STREQ       R7, [R5, #100]              @ 0x64 
    /*000001f8*/ BEQ         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_xa8
    /*000001fc*/ STR         R0, [SP] 
    /*00000200*/ MOV         R1, #4 
    /*00000204*/ LDR         R3, WORD_0374               @ LDR         R3, [PC, #360]              @ 0x0000000000000374 
    /*00000208*/ LDR         R2, WORD_0378               @ LDR         R2, [PC, #360]              @ 0x0000000000000378 
    /*0000020c*/ LDR         R0, WORD_037c               @ LDR         R0, [PC, #360]              @ 0x000000000000037c 
    /*00000210*/ ADD         R3, PC, R3 
    /*00000214*/ ADD         R2, PC, R2 
    /*00000218*/ ADD         R0, PC, R0 
    /*0000021c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x220:
    /*00000220*/ LDR         R0, [R5, #112]              @ 0x70 
    /*00000224*/ CMP         R0, #0 
    /*00000228*/ BEQ         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x128
    /*0000022c*/ BL          free
    /*00000230*/ MOV         R0, #0 
    /*00000234*/ STR         R0, [R5, #112]              @ 0x70 
    /*00000238*/ B           _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x158
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x23c:
    /*0000023c*/ LDR         R3, WORD_0380               @ LDR         R3, [PC, #316]              @ 0x0000000000000380 
    /*00000240*/ MOV         R1, #4 
    /*00000244*/ LDR         R2, WORD_0384               @ LDR         R2, [PC, #312]              @ 0x0000000000000384 
    /*00000248*/ LDR         R0, WORD_0388               @ LDR         R0, [PC, #312]              @ 0x0000000000000388 
    /*0000024c*/ STR         SL, [SP] 
    /*00000250*/ ADD         R3, PC, R3 
    /*00000254*/ ADD         R2, PC, R2 
    /*00000258*/ ADD         R0, PC, R0 
    /*0000025c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000260*/ MOV         R0, R4 
    /*00000264*/ B           _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x158
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x268:
    /*00000268*/ LDR         R2, WORD_038c               @ LDR         R2, [PC, #284]              @ 0x000000000000038c 
    /*0000026c*/ MOV         R1, #4 
    /*00000270*/ LDR         R0, WORD_0390               @ LDR         R0, [PC, #280]              @ 0x0000000000000390 
    /*00000274*/ ADD         R2, PC, R2 
    /*00000278*/ ADD         R0, PC, R0 
    /*0000027c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000280*/ MOV         R0, R4 
    /*00000284*/ B           _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x158
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x288:
    /*00000288*/ MOV         R4, #104                    @ 0x68 
    /*0000028c*/ MUL         R4, R4, R8 
    /*00000290*/ MOV         R0, R4 
    /*00000294*/ BL          malloc
    /*00000298*/ STR         R0, [R5, #112]              @ 0x70 
    /*0000029c*/ CMP         R0, #0 
    /*000002a0*/ BEQ         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x328
    /*000002a4*/ MOV         R3, R4 
    /*000002a8*/ MOV         R1, R4 
    /*000002ac*/ MOV         R2, #0 
    /*000002b0*/ BL          memset_s
    /*000002b4*/ CMP         R0, #0 
    /*000002b8*/ STREQ       R8, [R5, #108]              @ 0x6c 
    /*000002bc*/ BEQ         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_xb0
    /*000002c0*/ STR         R0, [SP] 
    /*000002c4*/ MOV         R1, #4 
    /*000002c8*/ LDR         R3, WORD_0394               @ LDR         R3, [PC, #196]              @ 0x0000000000000394 
    /*000002cc*/ LDR         R2, WORD_0398               @ LDR         R2, [PC, #196]              @ 0x0000000000000398 
    /*000002d0*/ LDR         R0, WORD_039c               @ LDR         R0, [PC, #196]              @ 0x000000000000039c 
    /*000002d4*/ ADD         R3, PC, R3 
    /*000002d8*/ ADD         R2, PC, R2 
    /*000002dc*/ ADD         R0, PC, R0 
    /*000002e0*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x2e4:
    /*000002e4*/ LDR         R0, [R5, #112]              @ 0x70 
    /*000002e8*/ CMP         R0, #0 
    /*000002ec*/ BEQ         _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x120
    /*000002f0*/ BL          free
    /*000002f4*/ MOV         R3, #0 
    /*000002f8*/ STR         R3, [R5, #112]              @ 0x70 
    /*000002fc*/ B           _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x120
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x300:
    /*00000300*/ STR         R0, [SP] 
    /*00000304*/ MOV         R1, #4 
    /*00000308*/ LDR         R3, WORD_03a0               @ LDR         R3, [PC, #144]              @ 0x00000000000003a0 
    /*0000030c*/ LDR         R2, WORD_03a4               @ LDR         R2, [PC, #144]              @ 0x00000000000003a4 
    /*00000310*/ LDR         R0, WORD_03a8               @ LDR         R0, [PC, #144]              @ 0x00000000000003a8 
    /*00000314*/ ADD         R3, PC, R3 
    /*00000318*/ ADD         R2, PC, R2 
    /*0000031c*/ ADD         R0, PC, R0 
    /*00000320*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000324*/ B           _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x118
    _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x328:
    /*00000328*/ LDR         R2, WORD_03ac               @ LDR         R2, [PC, #124]              @ 0x00000000000003ac 
    /*0000032c*/ MOV         R1, #4 
    /*00000330*/ LDR         R0, WORD_03b0               @ LDR         R0, [PC, #120]              @ 0x00000000000003b0 
    /*00000334*/ ADD         R2, PC, R2 
    /*00000338*/ ADD         R0, PC, R0 
    /*0000033c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000340*/ B           _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL_x120
    /*00000344*/ WORD_0344: .word 0x00000234
    /*00000348*/ WORD_0348: .word 0x00000234
    /*0000034c*/ WORD_034c: .word 0x00000234
    /*00000350*/ WORD_0350: .word 0x00000204
    /*00000354*/ WORD_0354: .word 0x00000204
    /*00000358*/ WORD_0358: .word 0x00000204
    /*0000035c*/ WORD_035c: .word 0x000001e0
    /*00000360*/ WORD_0360: .word 0x000001e0
    /*00000364*/ WORD_0364: .word 0x000001e0
    /*00000368*/ WORD_0368: .word 0x000001bc
    /*0000036c*/ WORD_036c: .word 0x000001bc
    /*00000370*/ WORD_0370: .word 0x000001bc
    /*00000374*/ WORD_0374: .word 0x0000015c
    /*00000378*/ WORD_0378: .word 0x0000015c
    /*0000037c*/ WORD_037c: .word 0x0000015c
    /*00000380*/ WORD_0380: .word 0x00000128
    /*00000384*/ WORD_0384: .word 0x00000128
    /*00000388*/ WORD_0388: .word 0x00000128
    /*0000038c*/ WORD_038c: .word 0x00000110
    /*00000390*/ WORD_0390: .word 0x00000110
    /*00000394*/ WORD_0394: .word 0x000000b8
    /*00000398*/ WORD_0398: .word 0x000000b8
    /*0000039c*/ WORD_039c: .word 0x000000b8
    /*000003a0*/ WORD_03a0: .word 0x00000084
    /*000003a4*/ WORD_03a4: .word 0x00000084
    /*000003a8*/ WORD_03a8: .word 0x00000084
    /*000003ac*/ WORD_03ac: .word 0x00000070
    /*000003b0*/ WORD_03b0: .word 0x00000070
FUNC_END _ZN4hirt10CpuSegTask4initEjjP11HiNodeParam7HI_BOOL


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10CpuSegTaskC2Ev
@ Size: 0x12c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10CpuSegTaskC2Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*00000014*/ VLDR        D18, [PC, #260]             @ 0x0000000000000120 
    /*00000018*/ LDR         LR, WORD_0128               @ LDR         LR, [PC, #264]              @ 0x0000000000000128 
    /*0000001c*/ MOV         R4, R0 
    /*00000020*/ ADD         R1, R4, #64                 @ 0x40 
    /*00000024*/ ADD         R0, R0, #12 
    /*00000028*/ ADD         LR, PC, LR 
    /*0000002c*/ MOV         R5, R4 
    /*00000030*/ MOV         IP, #0 
    /*00000034*/ ADD         LR, LR, #8 
    /*00000038*/ ADD         R6, R4, #136                @ 0x88 
    /*0000003c*/ MOV         R3, #56                     @ 0x38 
    /*00000040*/ VST1.8      {D16-D17}, [R0] 
    /*00000044*/ STR         IP, [R4, #36]               @ 0x24 
    /*00000048*/ MOV         R2, IP 
    /*0000004c*/ VSTR        D16, [R4, #28] 
    /*00000050*/ STR         IP, [R4, #40]               @ 0x28 
    /*00000054*/ MOV         R0, R6 
    /*00000058*/ STR         IP, [R4, #44]               @ 0x2c 
    /*0000005c*/ STR         IP, [R4, #48]               @ 0x30 
    /*00000060*/ STR         IP, [R4, #52]               @ 0x34 
    /*00000064*/ STR         IP, [R4, #56]               @ 0x38 
    /*00000068*/ VST1.8      {D16-D17}, [R1] 
    /*0000006c*/ VSTR        D16, [R4, #80]              @ 0x50 
    /*00000070*/ STR         IP, [R4, #60]               @ 0x3c 
    /*00000074*/ MOV         R1, R3 
    /*00000078*/ STR         IP, [R4, #92]               @ 0x5c 
    /*0000007c*/ STR         IP, [R4, #88]               @ 0x58 
    /*00000080*/ STR         LR, [R5], #4 
    /*00000084*/ VST1.32     {D18}, [R5] 
    /*00000088*/ BL          memset_s
    /*0000008c*/ MOV         R2, #0 
    /*00000090*/ ADD         R5, R4, #116                @ 0x74 
    /*00000094*/ STR         R2, [R4, #96]               @ 0x60 
    /*00000098*/ MOV         R3, #8 
    /*0000009c*/ MOV         R0, R5 
    /*000000a0*/ MOV         R1, R3 
    /*000000a4*/ BL          memset_s
    /*000000a8*/ MOV         R3, #56                     @ 0x38 
    /*000000ac*/ MOV         R0, R6 
    /*000000b0*/ MOV         R1, R3 
    /*000000b4*/ MOV         R2, #0 
    /*000000b8*/ BL          memset_s
    /*000000bc*/ MOV         R3, #8 
    /*000000c0*/ MOV         R2, #0 
    /*000000c4*/ MOV         R1, R3 
    /*000000c8*/ ADD         R0, R4, #100                @ 0x64 
    /*000000cc*/ BL          memset_s
    /*000000d0*/ MOV         R3, #8 
    /*000000d4*/ MOV         R2, #0 
    /*000000d8*/ MOV         R1, R3 
    /*000000dc*/ ADD         R0, R4, #108                @ 0x6c 
    /*000000e0*/ BL          memset_s
    /*000000e4*/ MOV         R3, #8 
    /*000000e8*/ MOV         R0, R5 
    /*000000ec*/ MOV         R1, R3 
    /*000000f0*/ MOV         R2, #0 
    /*000000f4*/ BL          memset_s
    /*000000f8*/ MOV         R3, #8 
    /*000000fc*/ MOV         R2, #0 
    /*00000100*/ MOV         R1, R3 
    /*00000104*/ ADD         R0, R4, #124                @ 0x7c 
    /*00000108*/ BL          memset_s
    /*0000010c*/ MOV         R0, R4 
    /*00000110*/ POP         {R4, R5, R6, PC} 
    /*00000114*/ MOV         R0, R4 
    /*00000118*/ BL          _ZN4hirt7SegTaskD2Ev
    /*0000011c*/ BL          __cxa_end_cleanup
    /*00000120*/ ANDEQ       R0, R0, R0 
    /*00000124*/ ANDEQ       R0, R0, R1 
    /*00000128*/ WORD_0128: .word 0x000000f8
FUNC_END _ZN4hirt10CpuSegTaskC2Ev


FUNC_BEGIN _ZN4hirt10CpuSegTaskC1Ev
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*00000014*/ VLDR        D18, [PC, #260]             @ 0x0000000000000120 
    /*00000018*/ LDR         LR, WORD_0128               @ LDR         LR, [PC, #264]              @ 0x0000000000000128 
    /*0000001c*/ MOV         R4, R0 
    /*00000020*/ ADD         R1, R4, #64                 @ 0x40 
    /*00000024*/ ADD         R0, R0, #12 
    /*00000028*/ ADD         LR, PC, LR 
    /*0000002c*/ MOV         R5, R4 
    /*00000030*/ MOV         IP, #0 
    /*00000034*/ ADD         LR, LR, #8 
    /*00000038*/ ADD         R6, R4, #136                @ 0x88 
    /*0000003c*/ MOV         R3, #56                     @ 0x38 
    /*00000040*/ VST1.8      {D16-D17}, [R0] 
    /*00000044*/ STR         IP, [R4, #36]               @ 0x24 
    /*00000048*/ MOV         R2, IP 
    /*0000004c*/ VSTR        D16, [R4, #28] 
    /*00000050*/ STR         IP, [R4, #40]               @ 0x28 
    /*00000054*/ MOV         R0, R6 
    /*00000058*/ STR         IP, [R4, #44]               @ 0x2c 
    /*0000005c*/ STR         IP, [R4, #48]               @ 0x30 
    /*00000060*/ STR         IP, [R4, #52]               @ 0x34 
    /*00000064*/ STR         IP, [R4, #56]               @ 0x38 
    /*00000068*/ VST1.8      {D16-D17}, [R1] 
    /*0000006c*/ VSTR        D16, [R4, #80]              @ 0x50 
    /*00000070*/ STR         IP, [R4, #60]               @ 0x3c 
    /*00000074*/ MOV         R1, R3 
    /*00000078*/ STR         IP, [R4, #92]               @ 0x5c 
    /*0000007c*/ STR         IP, [R4, #88]               @ 0x58 
    /*00000080*/ STR         LR, [R5], #4 
    /*00000084*/ VST1.32     {D18}, [R5] 
    /*00000088*/ BL          memset_s
    /*0000008c*/ MOV         R2, #0 
    /*00000090*/ ADD         R5, R4, #116                @ 0x74 
    /*00000094*/ STR         R2, [R4, #96]               @ 0x60 
    /*00000098*/ MOV         R3, #8 
    /*0000009c*/ MOV         R0, R5 
    /*000000a0*/ MOV         R1, R3 
    /*000000a4*/ BL          memset_s
    /*000000a8*/ MOV         R3, #56                     @ 0x38 
    /*000000ac*/ MOV         R0, R6 
    /*000000b0*/ MOV         R1, R3 
    /*000000b4*/ MOV         R2, #0 
    /*000000b8*/ BL          memset_s
    /*000000bc*/ MOV         R3, #8 
    /*000000c0*/ MOV         R2, #0 
    /*000000c4*/ MOV         R1, R3 
    /*000000c8*/ ADD         R0, R4, #100                @ 0x64 
    /*000000cc*/ BL          memset_s
    /*000000d0*/ MOV         R3, #8 
    /*000000d4*/ MOV         R2, #0 
    /*000000d8*/ MOV         R1, R3 
    /*000000dc*/ ADD         R0, R4, #108                @ 0x6c 
    /*000000e0*/ BL          memset_s
    /*000000e4*/ MOV         R3, #8 
    /*000000e8*/ MOV         R0, R5 
    /*000000ec*/ MOV         R1, R3 
    /*000000f0*/ MOV         R2, #0 
    /*000000f4*/ BL          memset_s
    /*000000f8*/ MOV         R3, #8 
    /*000000fc*/ MOV         R2, #0 
    /*00000100*/ MOV         R1, R3 
    /*00000104*/ ADD         R0, R4, #124                @ 0x7c 
    /*00000108*/ BL          memset_s
    /*0000010c*/ MOV         R0, R4 
    /*00000110*/ POP         {R4, R5, R6, PC} 
    /*00000114*/ MOV         R0, R4 
    /*00000118*/ BL          _ZN4hirt7SegTaskD2Ev
    /*0000011c*/ BL          __cxa_end_cleanup
    /*00000120*/ ANDEQ       R0, R0, R0 
    /*00000124*/ ANDEQ       R0, R0, R1 
    /*00000128*/ WORD_0128: .word 0x000000f8
FUNC_END _ZN4hirt10CpuSegTaskC1Ev


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt10CpuSegTaskC2Ev
@ Size: 0x18
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt10CpuSegTask13setAssistInfoEPNS_18_CPU_ASSIST_INFO_SE
@ Size: 0x34
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt10CpuSegTask13setAssistInfoEPNS_18_CPU_ASSIST_INFO_SE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ MOV         R3, #56                     @ 0x38 
    /*00000014*/ MOV         R2, R1 
    /*00000018*/ ADD         R0, R0, #136                @ 0x88 
    /*0000001c*/ MOV         R1, R3 
    /*00000020*/ BL          memcpy_s
    /*00000024*/ ADDS        R0, R0, #0 
    /*00000028*/ MOVNE       R0, #1 
    /*0000002c*/ RSB         R0, R0, #0 
    /*00000030*/ POP         {R4, PC} 
FUNC_END _ZN4hirt10CpuSegTask13setAssistInfoEPNS_18_CPU_ASSIST_INFO_SE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt7SegTask21decreaseDependCounterEv
@ Size: 0xe4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt7SegTask21decreaseDependCounterEv
    /*00000000*/ LDR         R3, WORD_00dc               @ LDR         R3, [PC, #212]              @ 0x00000000000000dc 
    /*00000004*/ LDR         R2, WORD_00e0               @ LDR         R2, [PC, #212]              @ 0x00000000000000e0 
    /*00000008*/ ADD         R3, PC, R3 
    /*0000000c*/ LDR         R3, [R3, R2] 
    /*00000010*/ CMP         R3, #0 
    /*00000014*/ BEQ         _ZN4hirt7SegTask21decreaseDependCounterEv_x9c
    /*00000018*/ MOV         IP, #16384                  @ 0x4000 
    /*0000001c*/ PUSH        {R4, R5, R6, LR} 
    /*00000020*/ SUB         IP, SP, IP 
    /*00000024*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000028*/ ADD         R5, R0, #64                 @ 0x40 
    /*0000002c*/ MOV         R4, R0 
    /*00000030*/ MOV         R0, R5 
    /*00000034*/ BL          pthread_mutex_lock
    /*00000038*/ CMP         R0, #0 
    /*0000003c*/ BNE         _ZN4hirt7SegTask21decreaseDependCounterEv_xc8
    /*00000040*/ LDR         R3, [R4, #60]               @ 0x3c 
    /*00000044*/ SUB         R3, R3, #1 
    /*00000048*/ STR         R3, [R4, #60]               @ 0x3c 
    /*0000004c*/ CMP         R3, #0 
    /*00000050*/ BEQ         _ZN4hirt7SegTask21decreaseDependCounterEv_x60
    /*00000054*/ MOV         R0, R5 
    /*00000058*/ POP         {R4, R5, R6, LR} 
    _ZN4hirt7SegTask21decreaseDependCounterEv_x5c:
    /*0000005c*/ B           _ZN4hirt7SegTask21decreaseDependCounterEv_x5c@ pthread_mutex_unlock [R_ARM_JUMP24: +0x0] 
    _ZN4hirt7SegTask21decreaseDependCounterEv_x60:
    /*00000060*/ LDR         R3, [R4, #88]               @ 0x58 
    /*00000064*/ LDR         R4, [R3, #28] 
    /*00000068*/ ADD         R6, R4, #212                @ 0xd4 
    /*0000006c*/ MOV         R0, R6 
    /*00000070*/ BL          pthread_mutex_lock
    /*00000074*/ CMP         R0, #0 
    /*00000078*/ BNE         _ZN4hirt7SegTask21decreaseDependCounterEv_xcc
    /*0000007c*/ LDR         R3, [R4, #40]               @ 0x28 
    /*00000080*/ MOV         R0, R6 
    /*00000084*/ ADD         R3, R3, #1 
    /*00000088*/ STR         R3, [R4, #40]               @ 0x28 
    /*0000008c*/ BL          pthread_mutex_unlock
    /*00000090*/ MOV         R0, R5 
    /*00000094*/ POP         {R4, R5, R6, LR} 
    _ZN4hirt7SegTask21decreaseDependCounterEv_x98:
    /*00000098*/ B           _ZN4hirt7SegTask21decreaseDependCounterEv_x98@ pthread_mutex_unlock [R_ARM_JUMP24: +0x0] 
    _ZN4hirt7SegTask21decreaseDependCounterEv_x9c:
    /*0000009c*/ LDR         R3, [R0, #60]               @ 0x3c 
    /*000000a0*/ SUB         R3, R3, #1 
    /*000000a4*/ STR         R3, [R0, #60]               @ 0x3c 
    /*000000a8*/ CMP         R3, #0 
    /*000000ac*/ BXNE        LR 
    /*000000b0*/ LDR         R3, [R0, #88]               @ 0x58 
    /*000000b4*/ LDR         R2, [R3, #28] 
    /*000000b8*/ LDR         R3, [R2, #40]               @ 0x28 
    /*000000bc*/ ADD         R3, R3, #1 
    /*000000c0*/ STR         R3, [R2, #40]               @ 0x28 
    /*000000c4*/ BX          LR 
    _ZN4hirt7SegTask21decreaseDependCounterEv_xc8:
    /*000000c8*/ BL          _ZSt20__throw_system_errori
    _ZN4hirt7SegTask21decreaseDependCounterEv_xcc:
    /*000000cc*/ BL          _ZSt20__throw_system_errori
    /*000000d0*/ MOV         R0, R5 
    /*000000d4*/ BL          pthread_mutex_unlock
    /*000000d8*/ BL          __cxa_end_cleanup
    /*000000dc*/ WORD_00dc: .word 0x000000cc
    /*000000e0*/ WORD_00e0: .word 0x00000000
FUNC_END _ZN4hirt7SegTask21decreaseDependCounterEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt7SegTask21decreaseDependCounterEv
@ Size: 0x1c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv
@ Size: 0xd4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv
    /*00000000*/ LDR         R3, WORD_00cc               @ LDR         R3, [PC, #196]              @ 0x00000000000000cc 
    /*00000004*/ LDR         R2, WORD_00d0               @ LDR         R2, [PC, #196]              @ 0x00000000000000d0 
    /*00000008*/ ADD         R3, PC, R3 
    /*0000000c*/ LDR         R3, [R3, R2] 
    /*00000010*/ CMP         R3, #0 
    /*00000014*/ BEQ         _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_x94
    /*00000018*/ MOV         IP, #16384                  @ 0x4000 
    /*0000001c*/ PUSH        {R4, R5, R6, LR} 
    /*00000020*/ SUB         IP, SP, IP 
    /*00000024*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000028*/ ADD         R5, R0, #64                 @ 0x40 
    /*0000002c*/ MOV         R4, R0 
    /*00000030*/ MOV         R0, R5 
    /*00000034*/ BL          pthread_mutex_lock
    /*00000038*/ CMP         R0, #0 
    /*0000003c*/ BNE         _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_xb8
    /*00000040*/ LDR         R3, [R4, #60]               @ 0x3c 
    /*00000044*/ CMP         R3, #0 
    /*00000048*/ BEQ         _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_x58
    /*0000004c*/ MOV         R0, R5 
    /*00000050*/ POP         {R4, R5, R6, LR} 
    _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_x54:
    /*00000054*/ B           _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_x54@ pthread_mutex_unlock [R_ARM_JUMP24: +0x0] 
    _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_x58:
    /*00000058*/ LDR         R3, [R4, #88]               @ 0x58 
    /*0000005c*/ LDR         R4, [R3, #28] 
    /*00000060*/ ADD         R6, R4, #212                @ 0xd4 
    /*00000064*/ MOV         R0, R6 
    /*00000068*/ BL          pthread_mutex_lock
    /*0000006c*/ CMP         R0, #0 
    /*00000070*/ BNE         _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_xbc
    /*00000074*/ LDR         R3, [R4, #40]               @ 0x28 
    /*00000078*/ MOV         R0, R6 
    /*0000007c*/ ADD         R3, R3, #1 
    /*00000080*/ STR         R3, [R4, #40]               @ 0x28 
    /*00000084*/ BL          pthread_mutex_unlock
    /*00000088*/ MOV         R0, R5 
    /*0000008c*/ POP         {R4, R5, R6, LR} 
    _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_x90:
    /*00000090*/ B           _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_x90@ pthread_mutex_unlock [R_ARM_JUMP24: +0x0] 
    _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_x94:
    /*00000094*/ LDR         R3, [R0, #60]               @ 0x3c 
    /*00000098*/ CMP         R3, #0 
    /*0000009c*/ BXNE        LR 
    /*000000a0*/ LDR         R3, [R0, #88]               @ 0x58 
    /*000000a4*/ LDR         R2, [R3, #28] 
    /*000000a8*/ LDR         R3, [R2, #40]               @ 0x28 
    /*000000ac*/ ADD         R3, R3, #1 
    /*000000b0*/ STR         R3, [R2, #40]               @ 0x28 
    /*000000b4*/ BX          LR 
    _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_xb8:
    /*000000b8*/ BL          _ZSt20__throw_system_errori
    _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv_xbc:
    /*000000bc*/ BL          _ZSt20__throw_system_errori
    /*000000c0*/ MOV         R0, R5 
    /*000000c4*/ BL          pthread_mutex_unlock
    /*000000c8*/ BL          __cxa_end_cleanup
    /*000000cc*/ WORD_00cc: .word 0x000000bc
    /*000000d0*/ WORD_00d0: .word 0x00000000
FUNC_END _ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt7SegTask28updateModelGroupTaskReadyNumEv
@ Size: 0x1c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt7SegTask12notifyDependEv
@ Size: 0x14c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt7SegTask12notifyDependEv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4072]             @ 0xfe8 
    /*00000010*/ LDR         R5, [R0, #36]               @ 0x24 
    /*00000014*/ LDR         R7, [R0, #40]               @ 0x28 
    /*00000018*/ LDR         R3, WORD_013c               @ LDR         R3, [PC, #284]              @ 0x000000000000013c 
    /*0000001c*/ CMP         R5, R7 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ POPEQ       {R4, R5, R6, R7, R8, PC} 
    /*00000028*/ LDR         R4, [R5] 
    /*0000002c*/ CMP         R4, #0 
    /*00000030*/ BEQ         _ZN4hirt7SegTask12notifyDependEv_x10c
    /*00000034*/ LDR         R2, WORD_0140               @ LDR         R2, [PC, #260]              @ 0x0000000000000140 
    /*00000038*/ ADD         R5, R5, #4 
    /*0000003c*/ LDR         R3, [R3, R2] 
    /*00000040*/ CMP         R3, #0 
    /*00000044*/ BNE         _ZN4hirt7SegTask12notifyDependEv_x68
    /*00000048*/ B           _ZN4hirt7SegTask12notifyDependEv_xd4
    _ZN4hirt7SegTask12notifyDependEv_x4c:
    /*0000004c*/ MOV         R0, R6 
    /*00000050*/ BL          pthread_mutex_unlock
    /*00000054*/ CMP         R5, R7 
    /*00000058*/ BEQ         _ZN4hirt7SegTask12notifyDependEv_xd0
    _ZN4hirt7SegTask12notifyDependEv_x5c:
    /*0000005c*/ LDR         R4, [R5], #4 
    /*00000060*/ CMP         R4, #0 
    /*00000064*/ BEQ         _ZN4hirt7SegTask12notifyDependEv_x10c
    _ZN4hirt7SegTask12notifyDependEv_x68:
    /*00000068*/ ADD         R6, R4, #64                 @ 0x40 
    /*0000006c*/ MOV         R0, R6 
    /*00000070*/ BL          pthread_mutex_lock
    /*00000074*/ CMP         R0, #0 
    /*00000078*/ BNE         _ZN4hirt7SegTask12notifyDependEv_x128
    /*0000007c*/ LDR         R3, [R4, #60]               @ 0x3c 
    /*00000080*/ SUB         R3, R3, #1 
    /*00000084*/ STR         R3, [R4, #60]               @ 0x3c 
    /*00000088*/ CMP         R3, #0 
    /*0000008c*/ BNE         _ZN4hirt7SegTask12notifyDependEv_x4c
    /*00000090*/ LDR         R3, [R4, #88]               @ 0x58 
    /*00000094*/ LDR         R4, [R3, #28] 
    /*00000098*/ ADD         R8, R4, #212                @ 0xd4 
    /*0000009c*/ MOV         R0, R8 
    /*000000a0*/ BL          pthread_mutex_lock
    /*000000a4*/ CMP         R0, #0 
    /*000000a8*/ BNE         _ZN4hirt7SegTask12notifyDependEv_x12c
    /*000000ac*/ LDR         R3, [R4, #40]               @ 0x28 
    /*000000b0*/ MOV         R0, R8 
    /*000000b4*/ ADD         R3, R3, #1 
    /*000000b8*/ STR         R3, [R4, #40]               @ 0x28 
    /*000000bc*/ BL          pthread_mutex_unlock
    /*000000c0*/ MOV         R0, R6 
    /*000000c4*/ BL          pthread_mutex_unlock
    /*000000c8*/ CMP         R5, R7 
    /*000000cc*/ BNE         _ZN4hirt7SegTask12notifyDependEv_x5c
    _ZN4hirt7SegTask12notifyDependEv_xd0:
    /*000000d0*/ POP         {R4, R5, R6, R7, R8, PC} 
    _ZN4hirt7SegTask12notifyDependEv_xd4:
    /*000000d4*/ LDR         R3, [R4, #60]               @ 0x3c 
    /*000000d8*/ SUB         R3, R3, #1 
    /*000000dc*/ STR         R3, [R4, #60]               @ 0x3c 
    /*000000e0*/ CMP         R3, #0 
    /*000000e4*/ LDREQ       R3, [R4, #88]               @ 0x58 
    /*000000e8*/ LDREQ       R2, [R3, #28] 
    /*000000ec*/ LDREQ       R3, [R2, #40]               @ 0x28 
    /*000000f0*/ ADDEQ       R3, R3, #1 
    /*000000f4*/ STREQ       R3, [R2, #40]               @ 0x28 
    /*000000f8*/ CMP         R7, R5 
    /*000000fc*/ POPEQ       {R4, R5, R6, R7, R8, PC} 
    /*00000100*/ LDR         R4, [R5], #4 
    /*00000104*/ CMP         R4, #0 
    /*00000108*/ BNE         _ZN4hirt7SegTask12notifyDependEv_xd4
    _ZN4hirt7SegTask12notifyDependEv_x10c:
    /*0000010c*/ LDR         R2, WORD_0144               @ LDR         R2, [PC, #48]               @ 0x0000000000000144 
    /*00000110*/ MOV         R1, #4 
    /*00000114*/ LDR         R0, WORD_0148               @ LDR         R0, [PC, #44]               @ 0x0000000000000148 
    /*00000118*/ ADD         R2, PC, R2 
    /*0000011c*/ ADD         R0, PC, R0 
    /*00000120*/ POP         {R4, R5, R6, R7, R8, LR} 
    _ZN4hirt7SegTask12notifyDependEv_x124:
    /*00000124*/ B           _ZN4hirt7SegTask12notifyDependEv_x124@ _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z [R_ARM_JUMP24: +0x0] 
    _ZN4hirt7SegTask12notifyDependEv_x128:
    /*00000128*/ BL          _ZSt20__throw_system_errori
    _ZN4hirt7SegTask12notifyDependEv_x12c:
    /*0000012c*/ BL          _ZSt20__throw_system_errori
    /*00000130*/ MOV         R0, R6 
    /*00000134*/ BL          pthread_mutex_unlock
    /*00000138*/ BL          __cxa_end_cleanup
    /*0000013c*/ WORD_013c: .word 0x00000114
    /*00000140*/ WORD_0140: .word 0x00000000
    /*00000144*/ WORD_0144: .word 0x00000024
    /*00000148*/ WORD_0148: .word 0x00000024
FUNC_END _ZN4hirt7SegTask12notifyDependEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt7SegTask12notifyDependEv
@ Size: 0x1c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt7SegTask17notifyAfterFinishEv
@ Size: 0x2b4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt7SegTask17notifyAfterFinishEv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4040]             @ 0xfc8 
    /*00000010*/ LDR         R5, [R0, #36]               @ 0x24 
    /*00000014*/ SUB         SP, SP, #20 
    /*00000018*/ LDR         R7, [R0, #40]               @ 0x28 
    /*0000001c*/ MOV         R8, R0 
    /*00000020*/ LDR         R9, WORD_02a0               @ LDR         R9, [PC, #632]              @ 0x00000000000002a0 
    /*00000024*/ CMP         R5, R7 
    /*00000028*/ ADD         R9, PC, R9 
    /*0000002c*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x26c
    /*00000030*/ LDR         R4, [R5] 
    /*00000034*/ LDR         R3, WORD_02a4               @ LDR         R3, [PC, #616]              @ 0x00000000000002a4 
    /*00000038*/ CMP         R4, #0 
    /*0000003c*/ LDR         SL, [R9, R3] 
    /*00000040*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x128
    /*00000044*/ CMP         SL, #0 
    /*00000048*/ ADD         R5, R5, #4 
    /*0000004c*/ BNE         _ZN4hirt7SegTask17notifyAfterFinishEv_x70
    /*00000050*/ B           _ZN4hirt7SegTask17notifyAfterFinishEv_xf0
    _ZN4hirt7SegTask17notifyAfterFinishEv_x54:
    /*00000054*/ MOV         R0, R6 
    /*00000058*/ BL          pthread_mutex_unlock
    /*0000005c*/ CMP         R7, R5 
    /*00000060*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_xd8
    _ZN4hirt7SegTask17notifyAfterFinishEv_x64:
    /*00000064*/ LDR         R4, [R5], #4 
    /*00000068*/ CMP         R4, #0 
    /*0000006c*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x128
    _ZN4hirt7SegTask17notifyAfterFinishEv_x70:
    /*00000070*/ ADD         R6, R4, #64                 @ 0x40 
    /*00000074*/ MOV         R0, R6 
    /*00000078*/ BL          pthread_mutex_lock
    /*0000007c*/ CMP         R0, #0 
    /*00000080*/ BNE         _ZN4hirt7SegTask17notifyAfterFinishEv_x278
    /*00000084*/ LDR         R3, [R4, #60]               @ 0x3c 
    /*00000088*/ SUB         R3, R3, #1 
    /*0000008c*/ STR         R3, [R4, #60]               @ 0x3c 
    /*00000090*/ CMP         R3, #0 
    /*00000094*/ BNE         _ZN4hirt7SegTask17notifyAfterFinishEv_x54
    /*00000098*/ LDR         R3, [R4, #88]               @ 0x58 
    /*0000009c*/ LDR         R4, [R3, #28] 
    /*000000a0*/ ADD         FP, R4, #212                @ 0xd4 
    /*000000a4*/ MOV         R0, FP 
    /*000000a8*/ BL          pthread_mutex_lock
    /*000000ac*/ CMP         R0, #0 
    /*000000b0*/ BNE         _ZN4hirt7SegTask17notifyAfterFinishEv_x27c
    /*000000b4*/ LDR         R3, [R4, #40]               @ 0x28 
    /*000000b8*/ MOV         R0, FP 
    /*000000bc*/ ADD         R3, R3, #1 
    /*000000c0*/ STR         R3, [R4, #40]               @ 0x28 
    /*000000c4*/ BL          pthread_mutex_unlock
    /*000000c8*/ MOV         R0, R6 
    /*000000cc*/ BL          pthread_mutex_unlock
    /*000000d0*/ CMP         R7, R5 
    /*000000d4*/ BNE         _ZN4hirt7SegTask17notifyAfterFinishEv_x64
    _ZN4hirt7SegTask17notifyAfterFinishEv_xd8:
    /*000000d8*/ BL          _ZN4hirt16TaskGroupManager11getInstanceEv
    /*000000dc*/ ADD         R5, R0, #40                 @ 0x28 
    /*000000e0*/ B           _ZN4hirt7SegTask17notifyAfterFinishEv_x150
    _ZN4hirt7SegTask17notifyAfterFinishEv_xe4:
    /*000000e4*/ LDR         R4, [R5], #4 
    /*000000e8*/ CMP         R4, #0 
    /*000000ec*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x128
    _ZN4hirt7SegTask17notifyAfterFinishEv_xf0:
    /*000000f0*/ LDR         R3, [R4, #60]               @ 0x3c 
    /*000000f4*/ SUB         R3, R3, #1 
    /*000000f8*/ STR         R3, [R4, #60]               @ 0x3c 
    /*000000fc*/ CMP         R3, #0 
    /*00000100*/ LDREQ       R3, [R4, #88]               @ 0x58 
    /*00000104*/ LDREQ       R2, [R3, #28] 
    /*00000108*/ LDREQ       R3, [R2, #40]               @ 0x28 
    /*0000010c*/ ADDEQ       R3, R3, #1 
    /*00000110*/ STREQ       R3, [R2, #40]               @ 0x28 
    /*00000114*/ CMP         R7, R5 
    /*00000118*/ BNE         _ZN4hirt7SegTask17notifyAfterFinishEv_xe4
    /*0000011c*/ BL          _ZN4hirt16TaskGroupManager11getInstanceEv
    /*00000120*/ ADD         R5, R0, #40                 @ 0x28 
    /*00000124*/ B           _ZN4hirt7SegTask17notifyAfterFinishEv_x160
    _ZN4hirt7SegTask17notifyAfterFinishEv_x128:
    /*00000128*/ LDR         R2, WORD_02a8               @ LDR         R2, [PC, #376]              @ 0x00000000000002a8 
    /*0000012c*/ MOV         R1, #4 
    /*00000130*/ LDR         R0, WORD_02ac               @ LDR         R0, [PC, #372]              @ 0x00000000000002ac 
    /*00000134*/ ADD         R2, PC, R2 
    /*00000138*/ ADD         R0, PC, R0 
    /*0000013c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt7SegTask17notifyAfterFinishEv_x140:
    /*00000140*/ BL          _ZN4hirt16TaskGroupManager11getInstanceEv
    /*00000144*/ CMP         SL, #0 
    /*00000148*/ ADD         R5, R0, #40                 @ 0x28 
    /*0000014c*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x160
    _ZN4hirt7SegTask17notifyAfterFinishEv_x150:
    /*00000150*/ MOV         R0, R5 
    /*00000154*/ BL          pthread_mutex_lock
    /*00000158*/ CMP         R0, #0 
    /*0000015c*/ BNE         _ZN4hirt7SegTask17notifyAfterFinishEv_x278
    _ZN4hirt7SegTask17notifyAfterFinishEv_x160:
    /*00000160*/ LDR         R3, WORD_02b0               @ LDR         R3, [PC, #328]              @ 0x00000000000002b0 
    /*00000164*/ LDR         R4, [R9, R3] 
    /*00000168*/ LDR         R3, [R4] 
    /*0000016c*/ SUB         R3, R3, #1 
    /*00000170*/ STR         R3, [R4] 
    /*00000174*/ BL          _ZN4hirt11ProcManager11getInstanceEv
    /*00000178*/ LDR         R3, [R4] 
    /*0000017c*/ CMP         SL, #0 
    /*00000180*/ STR         R3, [R0, #52]               @ 0x34 
    /*00000184*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x1d0
    /*00000188*/ MOV         R0, R5 
    /*0000018c*/ BL          pthread_mutex_unlock
    /*00000190*/ LDR         R3, [R8, #88]               @ 0x58 
    /*00000194*/ LDR         R4, [R3, #28] 
    /*00000198*/ ADD         R5, R4, #188                @ 0xbc 
    /*0000019c*/ MOV         R0, R5 
    /*000001a0*/ BL          pthread_mutex_lock
    /*000001a4*/ CMP         R0, #0 
    /*000001a8*/ BNE         _ZN4hirt7SegTask17notifyAfterFinishEv_x278
    /*000001ac*/ LDR         R3, [R4, #36]               @ 0x24 
    /*000001b0*/ CMP         R3, #1 
    /*000001b4*/ SUBNE       R3, R3, #1 
    /*000001b8*/ STRNE       R3, [R4, #36]               @ 0x24 
    /*000001bc*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x1f8
    /*000001c0*/ MOV         R0, R5 
    /*000001c4*/ ADD         SP, SP, #20 
    /*000001c8*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    _ZN4hirt7SegTask17notifyAfterFinishEv_x1cc:
    /*000001cc*/ B           _ZN4hirt7SegTask17notifyAfterFinishEv_x1cc@ pthread_mutex_unlock [R_ARM_JUMP24: +0x0] 
    _ZN4hirt7SegTask17notifyAfterFinishEv_x1d0:
    /*000001d0*/ LDR         R3, [R8, #88]               @ 0x58 
    /*000001d4*/ LDR         R4, [R3, #28] 
    /*000001d8*/ LDR         R3, [R4, #36]               @ 0x24 
    /*000001dc*/ ADD         R5, R4, #188                @ 0xbc 
    /*000001e0*/ CMP         R3, #1 
    /*000001e4*/ SUBNE       R3, R3, #1 
    /*000001e8*/ STRNE       R3, [R4, #36]               @ 0x24 
    /*000001ec*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x1f8
    _ZN4hirt7SegTask17notifyAfterFinishEv_x1f0:
    /*000001f0*/ ADD         SP, SP, #20 
    /*000001f4*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZN4hirt7SegTask17notifyAfterFinishEv_x1f8:
    /*000001f8*/ LDR         R0, [R4, #44]               @ 0x2c 
    /*000001fc*/ MOV         R3, R4 
    /*00000200*/ LDR         IP, [R4, #264]              @ 0x108 
    /*00000204*/ LDR         R1, [R0] 
    /*00000208*/ LDR         R2, [R4, #268]              @ 0x10c 
    /*0000020c*/ STR         IP, [SP, #8] 
    /*00000210*/ LDRD        R6, [R4, #240]              @ 0xf0 
    /*00000214*/ STRD        R6, [SP] 
    /*00000218*/ LDR         R6, [R1] 
    /*0000021c*/ MOV         R1, #0 
    /*00000220*/ BLX         R6 
    /*00000224*/ LDR         R0, [R4, #44]               @ 0x2c 
    /*00000228*/ CMP         R0, #0 
    /*0000022c*/ LDREQ       R3, [R4, #36]               @ 0x24 
    /*00000230*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x24c
    /*00000234*/ LDR         R3, [R0] 
    /*00000238*/ LDR         R3, [R3, #8] 
    /*0000023c*/ BLX         R3 
    /*00000240*/ LDR         R3, [R4, #36]               @ 0x24 
    /*00000244*/ MOV         R2, #0 
    /*00000248*/ STR         R2, [R4, #44]               @ 0x2c 
    _ZN4hirt7SegTask17notifyAfterFinishEv_x24c:
    /*0000024c*/ CMP         SL, #0 
    /*00000250*/ SUB         R3, R3, #1 
    /*00000254*/ STR         R3, [R4, #36]               @ 0x24 
    /*00000258*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x1f0
    /*0000025c*/ MOV         R0, R5 
    /*00000260*/ ADD         SP, SP, #20 
    /*00000264*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    _ZN4hirt7SegTask17notifyAfterFinishEv_x268:
    /*00000268*/ B           _ZN4hirt7SegTask17notifyAfterFinishEv_x268@ pthread_mutex_unlock [R_ARM_JUMP24: +0x0] 
    _ZN4hirt7SegTask17notifyAfterFinishEv_x26c:
    /*0000026c*/ LDR         R3, WORD_02a4               @ LDR         R3, [PC, #48]               @ 0x00000000000002a4 
    /*00000270*/ LDR         SL, [R9, R3] 
    /*00000274*/ B           _ZN4hirt7SegTask17notifyAfterFinishEv_x140
    _ZN4hirt7SegTask17notifyAfterFinishEv_x278:
    /*00000278*/ BL          _ZSt20__throw_system_errori
    _ZN4hirt7SegTask17notifyAfterFinishEv_x27c:
    /*0000027c*/ BL          _ZSt20__throw_system_errori
    /*00000280*/ MOV         R0, R6 
    /*00000284*/ BL          pthread_mutex_unlock
    /*00000288*/ BL          __cxa_end_cleanup
    /*0000028c*/ CMP         SL, #0 
    /*00000290*/ BEQ         _ZN4hirt7SegTask17notifyAfterFinishEv_x29c
    /*00000294*/ MOV         R0, R5 
    /*00000298*/ BL          pthread_mutex_unlock
    _ZN4hirt7SegTask17notifyAfterFinishEv_x29c:
    /*0000029c*/ BL          __cxa_end_cleanup
    /*000002a0*/ WORD_02a0: .word 0x00000270
    /*000002a4*/ WORD_02a4: .word 0x00000000
    /*000002a8*/ WORD_02a8: .word 0x0000016c
    /*000002ac*/ WORD_02ac: .word 0x0000016c
    /*000002b0*/ WORD_02b0: .word 0x00000000
FUNC_END _ZN4hirt7SegTask17notifyAfterFinishEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt7SegTask17notifyAfterFinishEv
@ Size: 0x27
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S
@ Size: 0x3a4
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4056]             @ 0xfd8 
    /*00000010*/ STR         R3, [R0, #120]              @ 0x78 
    /*00000014*/ MOV         R3, #64                     @ 0x40 
    /*00000018*/ SUB         SP, SP, #12 
    /*0000001c*/ MOV         R5, R0 
    /*00000020*/ MOV         R7, R1 
    /*00000024*/ MOV         R8, R2 
    /*00000028*/ ADD         R0, R0, #128                @ 0x80 
    /*0000002c*/ MOV         R1, R3 
    /*00000030*/ MOV         R2, #0 
    /*00000034*/ BL          memset_s
    /*00000038*/ SUBS        R4, R0, #0 
    /*0000003c*/ BNE         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x198
    /*00000040*/ MOV         R3, #72                     @ 0x48 
    /*00000044*/ MOV         R2, R4 
    /*00000048*/ MOV         R1, R3 
    /*0000004c*/ ADD         R0, R5, #192                @ 0xc0 
    /*00000050*/ BL          memset_s
    /*00000054*/ SUBS        R6, R0, #0 
    /*00000058*/ BNE         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x168
    /*0000005c*/ MOV         R3, #176                    @ 0xb0 
    /*00000060*/ MOV         R2, R6 
    /*00000064*/ MOV         R1, R3 
    /*00000068*/ ADD         R0, R5, #264                @ 0x108 
    /*0000006c*/ BL          memset_s
    /*00000070*/ SUBS        R4, R0, #0 
    /*00000074*/ BNE         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x1f4
    /*00000078*/ MOV         R3, #8 
    /*0000007c*/ MOV         R2, R4 
    /*00000080*/ MOV         R1, R3 
    /*00000084*/ ADD         R0, R5, #96                 @ 0x60 
    /*00000088*/ BL          memset_s
    /*0000008c*/ SUBS        R6, R0, #0 
    /*00000090*/ BNE         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x1c8
    /*00000094*/ MOV         R3, #8 
    /*00000098*/ MOV         R2, R6 
    /*0000009c*/ MOV         R1, R3 
    /*000000a0*/ ADD         R0, R5, #112                @ 0x70 
    /*000000a4*/ BL          memset_s
    /*000000a8*/ SUBS        R4, R0, #0 
    /*000000ac*/ BNE         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x224
    /*000000b0*/ MOV         R3, #8 
    /*000000b4*/ MOV         R2, R4 
    /*000000b8*/ MOV         R1, R3 
    /*000000bc*/ ADD         R0, R5, #104                @ 0x68 
    /*000000c0*/ BL          memset_s
    /*000000c4*/ SUBS        R6, R0, #0 
    /*000000c8*/ BNE         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x2cc
    /*000000cc*/ CMP         R7, #0 
    /*000000d0*/ BNE         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x250
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_xd4:
    /*000000d4*/ CMP         R8, #0 
    /*000000d8*/ MOVEQ       R0, #1 
    /*000000dc*/ BEQ         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x190
    /*000000e0*/ MOV         R4, #48                     @ 0x30 
    /*000000e4*/ MUL         R4, R4, R8 
    /*000000e8*/ MOV         R0, R4 
    /*000000ec*/ BL          malloc
    /*000000f0*/ STR         R0, [R5, #116]              @ 0x74 
    /*000000f4*/ CMP         R0, #0 
    /*000000f8*/ BEQ         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x2f8
    /*000000fc*/ MOV         R3, R4 
    /*00000100*/ MOV         R1, R4 
    /*00000104*/ MOV         R2, #0 
    /*00000108*/ BL          memset_s
    /*0000010c*/ CMP         R0, #0 
    /*00000110*/ STREQ       R8, [R5, #112]              @ 0x70 
    /*00000114*/ MOVEQ       R0, #1 
    /*00000118*/ BEQ         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x190
    /*0000011c*/ STR         R0, [SP] 
    /*00000120*/ MOV         R1, #4 
    /*00000124*/ LDR         R3, WORD_0334               @ LDR         R3, [PC, #520]              @ 0x0000000000000334 
    /*00000128*/ LDR         R2, WORD_0338               @ LDR         R2, [PC, #520]              @ 0x0000000000000338 
    /*0000012c*/ LDR         R0, WORD_033c               @ LDR         R0, [PC, #520]              @ 0x000000000000033c 
    /*00000130*/ ADD         R3, PC, R3 
    /*00000134*/ ADD         R2, PC, R2 
    /*00000138*/ ADD         R0, PC, R0 
    /*0000013c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000140*/ LDR         R0, [R5, #116]              @ 0x74 
    /*00000144*/ CMP         R0, #0 
    /*00000148*/ BEQ         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x158
    /*0000014c*/ BL          free
    /*00000150*/ MOV         R3, #0 
    /*00000154*/ STR         R3, [R5, #116]              @ 0x74 
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x158:
    /*00000158*/ CMP         R7, #0 
    /*0000015c*/ BNE         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x2b0
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x160:
    /*00000160*/ MOV         R0, #0 
    /*00000164*/ B           _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x190
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x168:
    /*00000168*/ LDR         R3, WORD_0340               @ LDR         R3, [PC, #464]              @ 0x0000000000000340 
    /*0000016c*/ MOV         R1, #4 
    /*00000170*/ LDR         R2, WORD_0344               @ LDR         R2, [PC, #460]              @ 0x0000000000000344 
    /*00000174*/ LDR         R0, WORD_0348               @ LDR         R0, [PC, #460]              @ 0x0000000000000348 
    /*00000178*/ STR         R6, [SP] 
    /*0000017c*/ ADD         R3, PC, R3 
    /*00000180*/ ADD         R2, PC, R2 
    /*00000184*/ ADD         R0, PC, R0 
    /*00000188*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*0000018c*/ MOV         R0, R4 
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x190:
    /*00000190*/ ADD         SP, SP, #12 
    /*00000194*/ POP         {R4, R5, R6, R7, R8, R9, PC} 
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x198:
    /*00000198*/ LDR         R3, WORD_034c               @ LDR         R3, [PC, #428]              @ 0x000000000000034c 
    /*0000019c*/ MOV         R1, #4 
    /*000001a0*/ LDR         R2, WORD_0350               @ LDR         R2, [PC, #424]              @ 0x0000000000000350 
    /*000001a4*/ LDR         R0, WORD_0354               @ LDR         R0, [PC, #424]              @ 0x0000000000000354 
    /*000001a8*/ STR         R4, [SP] 
    /*000001ac*/ ADD         R3, PC, R3 
    /*000001b0*/ ADD         R2, PC, R2 
    /*000001b4*/ ADD         R0, PC, R0 
    /*000001b8*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000001bc*/ MOV         R0, #0 
    /*000001c0*/ ADD         SP, SP, #12 
    /*000001c4*/ POP         {R4, R5, R6, R7, R8, R9, PC} 
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x1c8:
    /*000001c8*/ LDR         R3, WORD_0358               @ LDR         R3, [PC, #392]              @ 0x0000000000000358 
    /*000001cc*/ MOV         R1, #4 
    /*000001d0*/ LDR         R2, WORD_035c               @ LDR         R2, [PC, #388]              @ 0x000000000000035c 
    /*000001d4*/ LDR         R0, WORD_0360               @ LDR         R0, [PC, #388]              @ 0x0000000000000360 
    /*000001d8*/ STR         R6, [SP] 
    /*000001dc*/ ADD         R3, PC, R3 
    /*000001e0*/ ADD         R2, PC, R2 
    /*000001e4*/ ADD         R0, PC, R0 
    /*000001e8*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000001ec*/ MOV         R0, R4 
    /*000001f0*/ B           _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x190
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x1f4:
    /*000001f4*/ LDR         R3, WORD_0364               @ LDR         R3, [PC, #360]              @ 0x0000000000000364 
    /*000001f8*/ MOV         R1, #4 
    /*000001fc*/ LDR         R2, WORD_0368               @ LDR         R2, [PC, #356]              @ 0x0000000000000368 
    /*00000200*/ LDR         R0, WORD_036c               @ LDR         R0, [PC, #356]              @ 0x000000000000036c 
    /*00000204*/ STR         R4, [SP] 
    /*00000208*/ ADD         R3, PC, R3 
    /*0000020c*/ ADD         R2, PC, R2 
    /*00000210*/ ADD         R0, PC, R0 
    /*00000214*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000218*/ MOV         R0, R6 
    /*0000021c*/ ADD         SP, SP, #12 
    /*00000220*/ POP         {R4, R5, R6, R7, R8, R9, PC} 
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x224:
    /*00000224*/ LDR         R3, WORD_0370               @ LDR         R3, [PC, #324]              @ 0x0000000000000370 
    /*00000228*/ MOV         R1, #4 
    /*0000022c*/ LDR         R2, WORD_0374               @ LDR         R2, [PC, #320]              @ 0x0000000000000374 
    /*00000230*/ LDR         R0, WORD_0378               @ LDR         R0, [PC, #320]              @ 0x0000000000000378 
    /*00000234*/ STR         R4, [SP] 
    /*00000238*/ ADD         R3, PC, R3 
    /*0000023c*/ ADD         R2, PC, R2 
    /*00000240*/ ADD         R0, PC, R0 
    /*00000244*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000248*/ MOV         R0, R6 
    /*0000024c*/ B           _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x190
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x250:
    /*00000250*/ MOV         R9, #48                     @ 0x30 
    /*00000254*/ MUL         R9, R9, R7 
    /*00000258*/ MOV         R0, R9 
    /*0000025c*/ BL          malloc
    /*00000260*/ STR         R0, [R5, #100]              @ 0x64 
    /*00000264*/ CMP         R0, #0 
    /*00000268*/ MOV         R4, R0 
    /*0000026c*/ BEQ         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x314
    /*00000270*/ MOV         R2, R6 
    /*00000274*/ MOV         R3, R9 
    /*00000278*/ MOV         R1, R9 
    /*0000027c*/ BL          memset_s
    /*00000280*/ CMP         R0, #0 
    /*00000284*/ STREQ       R7, [R5, #96]               @ 0x60 
    /*00000288*/ BEQ         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_xd4
    /*0000028c*/ STR         R0, [SP] 
    /*00000290*/ MOV         R1, #4 
    /*00000294*/ LDR         R3, WORD_037c               @ LDR         R3, [PC, #224]              @ 0x000000000000037c 
    /*00000298*/ LDR         R2, WORD_0380               @ LDR         R2, [PC, #224]              @ 0x0000000000000380 
    /*0000029c*/ LDR         R0, WORD_0384               @ LDR         R0, [PC, #224]              @ 0x0000000000000384 
    /*000002a0*/ ADD         R3, PC, R3 
    /*000002a4*/ ADD         R2, PC, R2 
    /*000002a8*/ ADD         R0, PC, R0 
    /*000002ac*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x2b0:
    /*000002b0*/ LDR         R0, [R5, #100]              @ 0x64 
    /*000002b4*/ CMP         R0, #0 
    /*000002b8*/ BEQ         _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x160
    /*000002bc*/ BL          free
    /*000002c0*/ MOV         R0, #0 
    /*000002c4*/ STR         R0, [R5, #100]              @ 0x64 
    /*000002c8*/ B           _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x190
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x2cc:
    /*000002cc*/ LDR         R3, WORD_0388               @ LDR         R3, [PC, #180]              @ 0x0000000000000388 
    /*000002d0*/ MOV         R1, #4 
    /*000002d4*/ LDR         R2, WORD_038c               @ LDR         R2, [PC, #176]              @ 0x000000000000038c 
    /*000002d8*/ LDR         R0, WORD_0390               @ LDR         R0, [PC, #176]              @ 0x0000000000000390 
    /*000002dc*/ STR         R6, [SP] 
    /*000002e0*/ ADD         R3, PC, R3 
    /*000002e4*/ ADD         R2, PC, R2 
    /*000002e8*/ ADD         R0, PC, R0 
    /*000002ec*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000002f0*/ MOV         R0, R4 
    /*000002f4*/ B           _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x190
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x2f8:
    /*000002f8*/ LDR         R2, WORD_0394               @ LDR         R2, [PC, #148]              @ 0x0000000000000394 
    /*000002fc*/ MOV         R1, #4 
    /*00000300*/ LDR         R0, WORD_0398               @ LDR         R0, [PC, #144]              @ 0x0000000000000398 
    /*00000304*/ ADD         R2, PC, R2 
    /*00000308*/ ADD         R0, PC, R0 
    /*0000030c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000310*/ B           _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x158
    _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x314:
    /*00000314*/ LDR         R2, WORD_039c               @ LDR         R2, [PC, #128]              @ 0x000000000000039c 
    /*00000318*/ MOV         R1, #4 
    /*0000031c*/ LDR         R0, WORD_03a0               @ LDR         R0, [PC, #124]              @ 0x00000000000003a0 
    /*00000320*/ ADD         R2, PC, R2 
    /*00000324*/ ADD         R0, PC, R0 
    /*00000328*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*0000032c*/ MOV         R0, R4 
    /*00000330*/ B           _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S_x190
    /*00000334*/ WORD_0334: .word 0x000001fc
    /*00000338*/ WORD_0338: .word 0x000001fc
    /*0000033c*/ WORD_033c: .word 0x000001fc
    /*00000340*/ WORD_0340: .word 0x000001bc
    /*00000344*/ WORD_0344: .word 0x000001bc
    /*00000348*/ WORD_0348: .word 0x000001bc
    /*0000034c*/ WORD_034c: .word 0x00000198
    /*00000350*/ WORD_0350: .word 0x00000198
    /*00000354*/ WORD_0354: .word 0x00000198
    /*00000358*/ WORD_0358: .word 0x00000174
    /*0000035c*/ WORD_035c: .word 0x00000174
    /*00000360*/ WORD_0360: .word 0x00000174
    /*00000364*/ WORD_0364: .word 0x00000154
    /*00000368*/ WORD_0368: .word 0x00000154
    /*0000036c*/ WORD_036c: .word 0x00000154
    /*00000370*/ WORD_0370: .word 0x00000130
    /*00000374*/ WORD_0374: .word 0x00000130
    /*00000378*/ WORD_0378: .word 0x00000130
    /*0000037c*/ WORD_037c: .word 0x000000d4
    /*00000380*/ WORD_0380: .word 0x000000d4
    /*00000384*/ WORD_0384: .word 0x000000d4
    /*00000388*/ WORD_0388: .word 0x000000a0
    /*0000038c*/ WORD_038c: .word 0x000000a0
    /*00000390*/ WORD_0390: .word 0x000000a0
    /*00000394*/ WORD_0394: .word 0x00000088
    /*00000398*/ WORD_0398: .word 0x00000088
    /*0000039c*/ WORD_039c: .word 0x00000074
    /*000003a0*/ WORD_03a0: .word 0x00000074
FUNC_END _ZN4hirt11NnieSegTask4initEjjPK18hiSVP_NNIE_MODEL_S


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11NnieSegTaskC2E7HI_BOOL
@ Size: 0x128
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11NnieSegTaskC2E7HI_BOOL
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*00000014*/ VMOV.I32    D18, #1                     @ 0x00000001 
    /*00000018*/ LDR         IP, WORD_0124               @ LDR         IP, [PC, #260]              @ 0x0000000000000124 
    /*0000001c*/ ADD         R3, R0, #12 
    /*00000020*/ MOV         R4, R0 
    /*00000024*/ ADD         LR, R0, #64                 @ 0x40 
    /*00000028*/ ADD         IP, PC, IP 
    /*0000002c*/ ADD         R6, R0, #4 
    /*00000030*/ VST1.8      {D16-D17}, [R3] 
    /*00000034*/ MOV         R0, #0 
    /*00000038*/ ADD         IP, IP, #8 
    /*0000003c*/ STR         R0, [R4, #36]               @ 0x24 
    /*00000040*/ ADD         R5, R4, #264                @ 0x108 
    /*00000044*/ STR         R0, [R4, #40]               @ 0x28 
    /*00000048*/ MOV         R3, #176                    @ 0xb0 
    /*0000004c*/ STR         R0, [R4, #44]               @ 0x2c 
    /*00000050*/ MOV         R2, R0 
    /*00000054*/ STR         R0, [R4, #48]               @ 0x30 
    /*00000058*/ STR         R0, [R4, #52]               @ 0x34 
    /*0000005c*/ STR         R0, [R4, #56]               @ 0x38 
    /*00000060*/ VSTR        D16, [R4, #28] 
    /*00000064*/ VST1.8      {D16-D17}, [LR] 
    /*00000068*/ STR         R0, [R4, #60]               @ 0x3c 
    /*0000006c*/ STR         R0, [R4, #92]               @ 0x5c 
    /*00000070*/ STR         R0, [R4, #88]               @ 0x58 
    /*00000074*/ MOV         R0, R5 
    /*00000078*/ STR         R1, [R4, #440]              @ 0x1b8 
    /*0000007c*/ MOV         R1, R3 
    /*00000080*/ VSTR        D16, [R4, #80]              @ 0x50 
    /*00000084*/ STR         IP, [R4] 
    /*00000088*/ VST1.32     {D18}, [R6] 
    /*0000008c*/ BL          memset_s
    /*00000090*/ MOV         R3, #64                     @ 0x40 
    /*00000094*/ MOV         R2, #0 
    /*00000098*/ MOV         R1, R3 
    /*0000009c*/ ADD         R0, R4, #128                @ 0x80 
    /*000000a0*/ BL          memset_s
    /*000000a4*/ MOV         R3, #72                     @ 0x48 
    /*000000a8*/ MOV         R2, #0 
    /*000000ac*/ MOV         R1, R3 
    /*000000b0*/ ADD         R0, R4, #192                @ 0xc0 
    /*000000b4*/ BL          memset_s
    /*000000b8*/ MOV         R3, #176                    @ 0xb0 
    /*000000bc*/ MOV         R0, R5 
    /*000000c0*/ MOV         R1, R3 
    /*000000c4*/ MOV         R2, #0 
    /*000000c8*/ BL          memset_s
    /*000000cc*/ MOV         R3, #8 
    /*000000d0*/ MOV         R2, #0 
    /*000000d4*/ MOV         R1, R3 
    /*000000d8*/ ADD         R0, R4, #96                 @ 0x60 
    /*000000dc*/ BL          memset_s
    /*000000e0*/ MOV         R3, #8 
    /*000000e4*/ MOV         R2, #0 
    /*000000e8*/ MOV         R1, R3 
    /*000000ec*/ ADD         R0, R4, #112                @ 0x70 
    /*000000f0*/ BL          memset_s
    /*000000f4*/ MOV         R3, #8 
    /*000000f8*/ MOV         R2, #0 
    /*000000fc*/ MOV         R1, R3 
    /*00000100*/ ADD         R0, R4, #104                @ 0x68 
    /*00000104*/ BL          memset_s
    /*00000108*/ MOV         R3, #0 
    /*0000010c*/ MOV         R0, R4 
    /*00000110*/ STR         R3, [R4, #120]              @ 0x78 
    /*00000114*/ POP         {R4, R5, R6, PC} 
    /*00000118*/ MOV         R0, R4 
    /*0000011c*/ BL          _ZN4hirt7SegTaskD2Ev
    /*00000120*/ BL          __cxa_end_cleanup
    /*00000124*/ WORD_0124: .word 0x000000f4
FUNC_END _ZN4hirt11NnieSegTaskC2E7HI_BOOL


FUNC_BEGIN _ZN4hirt11NnieSegTaskC1E7HI_BOOL
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*00000014*/ VMOV.I32    D18, #1                     @ 0x00000001 
    /*00000018*/ LDR         IP, WORD_0124               @ LDR         IP, [PC, #260]              @ 0x0000000000000124 
    /*0000001c*/ ADD         R3, R0, #12 
    /*00000020*/ MOV         R4, R0 
    /*00000024*/ ADD         LR, R0, #64                 @ 0x40 
    /*00000028*/ ADD         IP, PC, IP 
    /*0000002c*/ ADD         R6, R0, #4 
    /*00000030*/ VST1.8      {D16-D17}, [R3] 
    /*00000034*/ MOV         R0, #0 
    /*00000038*/ ADD         IP, IP, #8 
    /*0000003c*/ STR         R0, [R4, #36]               @ 0x24 
    /*00000040*/ ADD         R5, R4, #264                @ 0x108 
    /*00000044*/ STR         R0, [R4, #40]               @ 0x28 
    /*00000048*/ MOV         R3, #176                    @ 0xb0 
    /*0000004c*/ STR         R0, [R4, #44]               @ 0x2c 
    /*00000050*/ MOV         R2, R0 
    /*00000054*/ STR         R0, [R4, #48]               @ 0x30 
    /*00000058*/ STR         R0, [R4, #52]               @ 0x34 
    /*0000005c*/ STR         R0, [R4, #56]               @ 0x38 
    /*00000060*/ VSTR        D16, [R4, #28] 
    /*00000064*/ VST1.8      {D16-D17}, [LR] 
    /*00000068*/ STR         R0, [R4, #60]               @ 0x3c 
    /*0000006c*/ STR         R0, [R4, #92]               @ 0x5c 
    /*00000070*/ STR         R0, [R4, #88]               @ 0x58 
    /*00000074*/ MOV         R0, R5 
    /*00000078*/ STR         R1, [R4, #440]              @ 0x1b8 
    /*0000007c*/ MOV         R1, R3 
    /*00000080*/ VSTR        D16, [R4, #80]              @ 0x50 
    /*00000084*/ STR         IP, [R4] 
    /*00000088*/ VST1.32     {D18}, [R6] 
    /*0000008c*/ BL          memset_s
    /*00000090*/ MOV         R3, #64                     @ 0x40 
    /*00000094*/ MOV         R2, #0 
    /*00000098*/ MOV         R1, R3 
    /*0000009c*/ ADD         R0, R4, #128                @ 0x80 
    /*000000a0*/ BL          memset_s
    /*000000a4*/ MOV         R3, #72                     @ 0x48 
    /*000000a8*/ MOV         R2, #0 
    /*000000ac*/ MOV         R1, R3 
    /*000000b0*/ ADD         R0, R4, #192                @ 0xc0 
    /*000000b4*/ BL          memset_s
    /*000000b8*/ MOV         R3, #176                    @ 0xb0 
    /*000000bc*/ MOV         R0, R5 
    /*000000c0*/ MOV         R1, R3 
    /*000000c4*/ MOV         R2, #0 
    /*000000c8*/ BL          memset_s
    /*000000cc*/ MOV         R3, #8 
    /*000000d0*/ MOV         R2, #0 
    /*000000d4*/ MOV         R1, R3 
    /*000000d8*/ ADD         R0, R4, #96                 @ 0x60 
    /*000000dc*/ BL          memset_s
    /*000000e0*/ MOV         R3, #8 
    /*000000e4*/ MOV         R2, #0 
    /*000000e8*/ MOV         R1, R3 
    /*000000ec*/ ADD         R0, R4, #112                @ 0x70 
    /*000000f0*/ BL          memset_s
    /*000000f4*/ MOV         R3, #8 
    /*000000f8*/ MOV         R2, #0 
    /*000000fc*/ MOV         R1, R3 
    /*00000100*/ ADD         R0, R4, #104                @ 0x68 
    /*00000104*/ BL          memset_s
    /*00000108*/ MOV         R3, #0 
    /*0000010c*/ MOV         R0, R4 
    /*00000110*/ STR         R3, [R4, #120]              @ 0x78 
    /*00000114*/ POP         {R4, R5, R6, PC} 
    /*00000118*/ MOV         R0, R4 
    /*0000011c*/ BL          _ZN4hirt7SegTaskD2Ev
    /*00000120*/ BL          __cxa_end_cleanup
    /*00000124*/ WORD_0124: .word 0x000000f4
FUNC_END _ZN4hirt11NnieSegTaskC1E7HI_BOOL


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt11NnieSegTaskC2E7HI_BOOL
@ Size: 0x17
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S
@ Size: 0x464
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4056]             @ 0xfd8 
    /*00000010*/ SUB         SP, SP, #8 
    /*00000014*/ MOV         R8, R3 
    /*00000018*/ MOV         R3, #64                     @ 0x40 
    /*0000001c*/ MOV         R5, R0 
    /*00000020*/ LDR         IP, [SP, #40]               @ 0x28 
    /*00000024*/ MOV         R6, R1 
    /*00000028*/ MOV         R7, R2 
    /*0000002c*/ ADD         R0, R0, #128                @ 0x80 
    /*00000030*/ STR         IP, [R0, #-8] 
    /*00000034*/ MOV         R1, R3 
    /*00000038*/ MOV         R2, #0 
    /*0000003c*/ BL          memset_s
    /*00000040*/ SUBS        R4, R0, #0 
    /*00000044*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1b0
    /*00000048*/ MOV         R3, #72                     @ 0x48 
    /*0000004c*/ MOV         R2, R4 
    /*00000050*/ MOV         R1, R3 
    /*00000054*/ ADD         R0, R5, #192                @ 0xc0 
    /*00000058*/ BL          memset_s
    /*0000005c*/ SUBS        R9, R0, #0 
    /*00000060*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x180
    /*00000064*/ MOV         R3, #176                    @ 0xb0 
    /*00000068*/ MOV         R2, R9 
    /*0000006c*/ MOV         R1, R3 
    /*00000070*/ ADD         R0, R5, #264                @ 0x108 
    /*00000074*/ BL          memset_s
    /*00000078*/ SUBS        R4, R0, #0 
    /*0000007c*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x20c
    /*00000080*/ MOV         R3, #8 
    /*00000084*/ MOV         R2, R4 
    /*00000088*/ MOV         R1, R3 
    /*0000008c*/ ADD         R0, R5, #96                 @ 0x60 
    /*00000090*/ BL          memset_s
    /*00000094*/ SUBS        R9, R0, #0 
    /*00000098*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1e0
    /*0000009c*/ MOV         R3, #8 
    /*000000a0*/ MOV         R2, R9 
    /*000000a4*/ MOV         R1, R3 
    /*000000a8*/ ADD         R0, R5, #112                @ 0x70 
    /*000000ac*/ BL          memset_s
    /*000000b0*/ SUBS        R4, R0, #0 
    /*000000b4*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x23c
    /*000000b8*/ MOV         R3, #8 
    /*000000bc*/ MOV         R2, R4 
    /*000000c0*/ MOV         R1, R3 
    /*000000c4*/ ADD         R0, R5, #104                @ 0x68 
    /*000000c8*/ BL          memset_s
    /*000000cc*/ SUBS        R9, R0, #0 
    /*000000d0*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x35c
    /*000000d4*/ CMP         R6, #0 
    /*000000d8*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x268
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_xdc:
    /*000000dc*/ CMP         R7, #0 
    /*000000e0*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x2e4
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_xe4:
    /*000000e4*/ CMP         R8, #0 
    /*000000e8*/ MOVEQ       R0, #1 
    /*000000ec*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1a8
    /*000000f0*/ MOV         R4, #48                     @ 0x30 
    /*000000f4*/ MUL         R4, R4, R8 
    /*000000f8*/ MOV         R0, R4 
    /*000000fc*/ BL          malloc
    /*00000100*/ STR         R0, [R5, #116]              @ 0x74 
    /*00000104*/ CMP         R0, #0 
    /*00000108*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x388
    /*0000010c*/ MOV         R3, R4 
    /*00000110*/ MOV         R1, R4 
    /*00000114*/ MOV         R2, #0 
    /*00000118*/ BL          memset_s
    /*0000011c*/ CMP         R0, #0 
    /*00000120*/ STREQ       R8, [R5, #112]              @ 0x70 
    /*00000124*/ MOVEQ       R0, #1 
    /*00000128*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1a8
    /*0000012c*/ STR         R0, [SP] 
    /*00000130*/ MOV         R1, #4 
    /*00000134*/ LDR         R3, WORD_03e0               @ LDR         R3, [PC, #676]              @ 0x00000000000003e0 
    /*00000138*/ LDR         R2, WORD_03e4               @ LDR         R2, [PC, #676]              @ 0x00000000000003e4 
    /*0000013c*/ LDR         R0, WORD_03e8               @ LDR         R0, [PC, #676]              @ 0x00000000000003e8 
    /*00000140*/ ADD         R3, PC, R3 
    /*00000144*/ ADD         R2, PC, R2 
    /*00000148*/ ADD         R0, PC, R0 
    /*0000014c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000150*/ LDR         R0, [R5, #116]              @ 0x74 
    /*00000154*/ CMP         R0, #0 
    /*00000158*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x168
    /*0000015c*/ BL          free
    /*00000160*/ MOV         R3, #0 
    /*00000164*/ STR         R3, [R5, #116]              @ 0x74 
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x168:
    /*00000168*/ CMP         R7, #0 
    /*0000016c*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x340
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x170:
    /*00000170*/ CMP         R6, #0 
    /*00000174*/ BNE         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x2c8
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x178:
    /*00000178*/ MOV         R0, #0 
    /*0000017c*/ B           _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1a8
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x180:
    /*00000180*/ LDR         R3, WORD_03ec               @ LDR         R3, [PC, #612]              @ 0x00000000000003ec 
    /*00000184*/ MOV         R1, #4 
    /*00000188*/ LDR         R2, WORD_03f0               @ LDR         R2, [PC, #608]              @ 0x00000000000003f0 
    /*0000018c*/ LDR         R0, WORD_03f4               @ LDR         R0, [PC, #608]              @ 0x00000000000003f4 
    /*00000190*/ STR         R9, [SP] 
    /*00000194*/ ADD         R3, PC, R3 
    /*00000198*/ ADD         R2, PC, R2 
    /*0000019c*/ ADD         R0, PC, R0 
    /*000001a0*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000001a4*/ MOV         R0, R4 
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1a8:
    /*000001a8*/ ADD         SP, SP, #8 
    /*000001ac*/ POP         {R4, R5, R6, R7, R8, R9, SL, PC} 
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1b0:
    /*000001b0*/ LDR         R3, WORD_03f8               @ LDR         R3, [PC, #576]              @ 0x00000000000003f8 
    /*000001b4*/ MOV         R1, #4 
    /*000001b8*/ LDR         R2, WORD_03fc               @ LDR         R2, [PC, #572]              @ 0x00000000000003fc 
    /*000001bc*/ LDR         R0, WORD_0400               @ LDR         R0, [PC, #572]              @ 0x0000000000000400 
    /*000001c0*/ STR         R4, [SP] 
    /*000001c4*/ ADD         R3, PC, R3 
    /*000001c8*/ ADD         R2, PC, R2 
    /*000001cc*/ ADD         R0, PC, R0 
    /*000001d0*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000001d4*/ MOV         R0, #0 
    /*000001d8*/ ADD         SP, SP, #8 
    /*000001dc*/ POP         {R4, R5, R6, R7, R8, R9, SL, PC} 
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1e0:
    /*000001e0*/ LDR         R3, WORD_0404               @ LDR         R3, [PC, #540]              @ 0x0000000000000404 
    /*000001e4*/ MOV         R1, #4 
    /*000001e8*/ LDR         R2, WORD_0408               @ LDR         R2, [PC, #536]              @ 0x0000000000000408 
    /*000001ec*/ LDR         R0, WORD_040c               @ LDR         R0, [PC, #536]              @ 0x000000000000040c 
    /*000001f0*/ STR         R9, [SP] 
    /*000001f4*/ ADD         R3, PC, R3 
    /*000001f8*/ ADD         R2, PC, R2 
    /*000001fc*/ ADD         R0, PC, R0 
    /*00000200*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000204*/ MOV         R0, R4 
    /*00000208*/ B           _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1a8
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x20c:
    /*0000020c*/ LDR         R3, WORD_0410               @ LDR         R3, [PC, #508]              @ 0x0000000000000410 
    /*00000210*/ MOV         R1, #4 
    /*00000214*/ LDR         R2, WORD_0414               @ LDR         R2, [PC, #504]              @ 0x0000000000000414 
    /*00000218*/ LDR         R0, WORD_0418               @ LDR         R0, [PC, #504]              @ 0x0000000000000418 
    /*0000021c*/ STR         R4, [SP] 
    /*00000220*/ ADD         R3, PC, R3 
    /*00000224*/ ADD         R2, PC, R2 
    /*00000228*/ ADD         R0, PC, R0 
    /*0000022c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000230*/ MOV         R0, R9 
    /*00000234*/ ADD         SP, SP, #8 
    /*00000238*/ POP         {R4, R5, R6, R7, R8, R9, SL, PC} 
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x23c:
    /*0000023c*/ LDR         R3, WORD_041c               @ LDR         R3, [PC, #472]              @ 0x000000000000041c 
    /*00000240*/ MOV         R1, #4 
    /*00000244*/ LDR         R2, WORD_0420               @ LDR         R2, [PC, #468]              @ 0x0000000000000420 
    /*00000248*/ LDR         R0, WORD_0424               @ LDR         R0, [PC, #468]              @ 0x0000000000000424 
    /*0000024c*/ STR         R4, [SP] 
    /*00000250*/ ADD         R3, PC, R3 
    /*00000254*/ ADD         R2, PC, R2 
    /*00000258*/ ADD         R0, PC, R0 
    /*0000025c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000260*/ MOV         R0, R9 
    /*00000264*/ B           _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1a8
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x268:
    /*00000268*/ MOV         SL, #48                     @ 0x30 
    /*0000026c*/ MUL         SL, SL, R6 
    /*00000270*/ MOV         R0, SL 
    /*00000274*/ BL          malloc
    /*00000278*/ STR         R0, [R5, #100]              @ 0x64 
    /*0000027c*/ CMP         R0, #0 
    /*00000280*/ MOV         R4, R0 
    /*00000284*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x3c0
    /*00000288*/ MOV         R2, R9 
    /*0000028c*/ MOV         R3, SL 
    /*00000290*/ MOV         R1, SL 
    /*00000294*/ BL          memset_s
    /*00000298*/ CMP         R0, #0 
    /*0000029c*/ STREQ       R6, [R5, #96]               @ 0x60 
    /*000002a0*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_xdc
    /*000002a4*/ STR         R0, [SP] 
    /*000002a8*/ MOV         R1, #4 
    /*000002ac*/ LDR         R3, WORD_0428               @ LDR         R3, [PC, #372]              @ 0x0000000000000428 
    /*000002b0*/ LDR         R2, WORD_042c               @ LDR         R2, [PC, #372]              @ 0x000000000000042c 
    /*000002b4*/ LDR         R0, WORD_0430               @ LDR         R0, [PC, #372]              @ 0x0000000000000430 
    /*000002b8*/ ADD         R3, PC, R3 
    /*000002bc*/ ADD         R2, PC, R2 
    /*000002c0*/ ADD         R0, PC, R0 
    /*000002c4*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x2c8:
    /*000002c8*/ LDR         R0, [R5, #100]              @ 0x64 
    /*000002cc*/ CMP         R0, #0 
    /*000002d0*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x178
    /*000002d4*/ BL          free
    /*000002d8*/ MOV         R0, #0 
    /*000002dc*/ STR         R0, [R5, #100]              @ 0x64 
    /*000002e0*/ B           _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1a8
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x2e4:
    /*000002e4*/ MOV         R4, #48                     @ 0x30 
    /*000002e8*/ MUL         R4, R4, R7 
    /*000002ec*/ MOV         R0, R4 
    /*000002f0*/ BL          malloc
    /*000002f4*/ STR         R0, [R5, #108]              @ 0x6c 
    /*000002f8*/ CMP         R0, #0 
    /*000002fc*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x3a4
    /*00000300*/ MOV         R3, R4 
    /*00000304*/ MOV         R1, R4 
    /*00000308*/ MOV         R2, #0 
    /*0000030c*/ BL          memset_s
    /*00000310*/ CMP         R0, #0 
    /*00000314*/ STREQ       R0, [R5, #104]              @ 0x68 
    /*00000318*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_xe4
    /*0000031c*/ STR         R0, [SP] 
    /*00000320*/ MOV         R1, #4 
    /*00000324*/ LDR         R3, WORD_0434               @ LDR         R3, [PC, #264]              @ 0x0000000000000434 
    /*00000328*/ LDR         R2, WORD_0438               @ LDR         R2, [PC, #264]              @ 0x0000000000000438 
    /*0000032c*/ LDR         R0, WORD_043c               @ LDR         R0, [PC, #264]              @ 0x000000000000043c 
    /*00000330*/ ADD         R3, PC, R3 
    /*00000334*/ ADD         R2, PC, R2 
    /*00000338*/ ADD         R0, PC, R0 
    /*0000033c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x340:
    /*00000340*/ LDR         R0, [R5, #108]              @ 0x6c 
    /*00000344*/ CMP         R0, #0 
    /*00000348*/ BEQ         _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x170
    /*0000034c*/ BL          free
    /*00000350*/ MOV         R3, #0 
    /*00000354*/ STR         R3, [R5, #108]              @ 0x6c 
    /*00000358*/ B           _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x170
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x35c:
    /*0000035c*/ LDR         R3, WORD_0440               @ LDR         R3, [PC, #220]              @ 0x0000000000000440 
    /*00000360*/ MOV         R1, #4 
    /*00000364*/ LDR         R2, WORD_0444               @ LDR         R2, [PC, #216]              @ 0x0000000000000444 
    /*00000368*/ LDR         R0, WORD_0448               @ LDR         R0, [PC, #216]              @ 0x0000000000000448 
    /*0000036c*/ STR         R9, [SP] 
    /*00000370*/ ADD         R3, PC, R3 
    /*00000374*/ ADD         R2, PC, R2 
    /*00000378*/ ADD         R0, PC, R0 
    /*0000037c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*00000380*/ MOV         R0, R4 
    /*00000384*/ B           _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1a8
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x388:
    /*00000388*/ LDR         R2, WORD_044c               @ LDR         R2, [PC, #188]              @ 0x000000000000044c 
    /*0000038c*/ MOV         R1, #4 
    /*00000390*/ LDR         R0, WORD_0450               @ LDR         R0, [PC, #184]              @ 0x0000000000000450 
    /*00000394*/ ADD         R2, PC, R2 
    /*00000398*/ ADD         R0, PC, R0 
    /*0000039c*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000003a0*/ B           _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x168
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x3a4:
    /*000003a4*/ LDR         R2, WORD_0454               @ LDR         R2, [PC, #168]              @ 0x0000000000000454 
    /*000003a8*/ MOV         R1, #4 
    /*000003ac*/ LDR         R0, WORD_0458               @ LDR         R0, [PC, #164]              @ 0x0000000000000458 
    /*000003b0*/ ADD         R2, PC, R2 
    /*000003b4*/ ADD         R0, PC, R0 
    /*000003b8*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000003bc*/ B           _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x170
    _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x3c0:
    /*000003c0*/ LDR         R2, WORD_045c               @ LDR         R2, [PC, #148]              @ 0x000000000000045c 
    /*000003c4*/ MOV         R1, #4 
    /*000003c8*/ LDR         R0, WORD_0460               @ LDR         R0, [PC, #144]              @ 0x0000000000000460 
    /*000003cc*/ ADD         R2, PC, R2 
    /*000003d0*/ ADD         R0, PC, R0 
    /*000003d4*/ BL          _Z15HIRT_LOG_PrintfPKc19tagHIRT_LOG_LEVEL_ES0_z
    /*000003d8*/ MOV         R0, R4 
    /*000003dc*/ B           _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S_x1a8
    /*000003e0*/ WORD_03e0: .word 0x00000298
    /*000003e4*/ WORD_03e4: .word 0x00000298
    /*000003e8*/ WORD_03e8: .word 0x00000298
    /*000003ec*/ WORD_03ec: .word 0x00000250
    /*000003f0*/ WORD_03f0: .word 0x00000250
    /*000003f4*/ WORD_03f4: .word 0x00000250
    /*000003f8*/ WORD_03f8: .word 0x0000022c
    /*000003fc*/ WORD_03fc: .word 0x0000022c
    /*00000400*/ WORD_0400: .word 0x0000022c
    /*00000404*/ WORD_0404: .word 0x00000208
    /*00000408*/ WORD_0408: .word 0x00000208
    /*0000040c*/ WORD_040c: .word 0x00000208
    /*00000410*/ WORD_0410: .word 0x000001e8
    /*00000414*/ WORD_0414: .word 0x000001e8
    /*00000418*/ WORD_0418: .word 0x000001e8
    /*0000041c*/ WORD_041c: .word 0x000001c4
    /*00000420*/ WORD_0420: .word 0x000001c4
    /*00000424*/ WORD_0424: .word 0x000001c4
    /*00000428*/ WORD_0428: .word 0x00000168
    /*0000042c*/ WORD_042c: .word 0x00000168
    /*00000430*/ WORD_0430: .word 0x00000168
    /*00000434*/ WORD_0434: .word 0x000000fc
    /*00000438*/ WORD_0438: .word 0x000000fc
    /*0000043c*/ WORD_043c: .word 0x000000fc
    /*00000440*/ WORD_0440: .word 0x000000c8
    /*00000444*/ WORD_0444: .word 0x000000c8
    /*00000448*/ WORD_0448: .word 0x000000c8
    /*0000044c*/ WORD_044c: .word 0x000000b0
    /*00000450*/ WORD_0450: .word 0x000000b0
    /*00000454*/ WORD_0454: .word 0x0000009c
    /*00000458*/ WORD_0458: .word 0x0000009c
    /*0000045c*/ WORD_045c: .word 0x00000088
    /*00000460*/ WORD_0460: .word 0x00000088
FUNC_END _ZN4hirt11NnieSegTask4initEjjjPK18hiSVP_NNIE_MODEL_S


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt11NnieSegTask13setAssistInfoEPNS_19_NNIE_ASSIST_INFO_SE
@ Size: 0x34
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt11NnieSegTask13setAssistInfoEPNS_19_NNIE_ASSIST_INFO_SE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4088]             @ 0xff8 
    /*00000010*/ MOV         R3, #176                    @ 0xb0 
    /*00000014*/ MOV         R2, R1 
    /*00000018*/ ADD         R0, R0, #264                @ 0x108 
    /*0000001c*/ MOV         R1, R3 
    /*00000020*/ BL          memcpy_s
    /*00000024*/ ADDS        R0, R0, #0 
    /*00000028*/ MOVNE       R0, #1 
    /*0000002c*/ RSB         R0, R0, #0 
    /*00000030*/ POP         {R4, PC} 
FUNC_END _ZN4hirt11NnieSegTask13setAssistInfoEPNS_19_NNIE_ASSIST_INFO_SE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt16ConnectorSegTaskC2EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
@ Size: 0xec
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt16ConnectorSegTaskC2EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4072]             @ 0xfe8 
    /*00000010*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*00000014*/ LDR         IP, WORD_00e8               @ LDR         IP, [PC, #204]              @ 0x00000000000000e8 
    /*00000018*/ MOV         R4, R0 
    /*0000001c*/ LDR         R7, [SP, #24] 
    /*00000020*/ MOV         R5, R1 
    /*00000024*/ ADD         IP, PC, IP 
    /*00000028*/ ADD         R8, R0, #12 
    /*0000002c*/ LDR         R1, [SP, #28] 
    /*00000030*/ ADD         R6, R0, #64                 @ 0x40 
    /*00000034*/ ADD         LR, IP, #8 
    /*00000038*/ MOV         IP, #0 
    /*0000003c*/ VST1.8      {D16-D17}, [R8] 
    /*00000040*/ VLDR        D18, [PC, #152]             @ 0x00000000000000e0 
    /*00000044*/ STR         IP, [R0, #36]               @ 0x24 
    /*00000048*/ STR         IP, [R0, #40]               @ 0x28 
    /*0000004c*/ STR         IP, [R0, #44]               @ 0x2c 
    /*00000050*/ STR         IP, [R0, #48]               @ 0x30 
    /*00000054*/ STR         IP, [R0, #52]               @ 0x34 
    /*00000058*/ STR         IP, [R0, #56]               @ 0x38 
    /*0000005c*/ VSTR        D16, [R0, #28] 
    /*00000060*/ VST1.8      {D16-D17}, [R6] 
    /*00000064*/ STR         IP, [R0, #60]               @ 0x3c 
    /*00000068*/ STR         IP, [R0, #92]               @ 0x5c 
    /*0000006c*/ STR         IP, [R0, #88]               @ 0x58 
    /*00000070*/ VSTR        D16, [R0, #80]              @ 0x50 
    /*00000074*/ STR         LR, [R0], #120              @ 0x78 
    /*00000078*/ STRB        IP, [R4, #128]              @ 0x80 
    /*0000007c*/ STR         IP, [R4, #124]              @ 0x7c 
    /*00000080*/ LDM         R5, {IP, LR} 
    /*00000084*/ ADD         R5, R4, #128                @ 0x80 
    /*00000088*/ STR         IP, [R4, #96]               @ 0x60 
    /*0000008c*/ ADD         IP, R4, #4 
    /*00000090*/ STR         LR, [R4, #100]              @ 0x64 
    /*00000094*/ LDR         LR, [R2] 
    /*00000098*/ LDR         R2, [R2, #4] 
    /*0000009c*/ STR         LR, [R4, #104]              @ 0x68 
    /*000000a0*/ STR         R2, [R4, #108]              @ 0x6c 
    /*000000a4*/ STR         R3, [R4, #112]              @ 0x70 
    /*000000a8*/ STR         R7, [R4, #116]              @ 0x74 
    /*000000ac*/ STR         R5, [R4, #120]              @ 0x78 
    /*000000b0*/ VST1.32     {D18}, [IP] 
    /*000000b4*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
    /*000000b8*/ MOV         R0, R4 
    /*000000bc*/ POP         {R4, R5, R6, R7, R8, PC} 
    /*000000c0*/ LDR         R0, [R4, #120]              @ 0x78 
    /*000000c4*/ CMP         R5, R0 
    /*000000c8*/ BEQ         _ZN4hirt16ConnectorSegTaskC2EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xd0
    /*000000cc*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskC2EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xd0:
    /*000000d0*/ MOV         R0, R4 
    /*000000d4*/ BL          _ZN4hirt7SegTaskD2Ev
    /*000000d8*/ BL          __cxa_end_cleanup
    /*000000dc*/ NOP         {0} 
    /*000000e0*/ ANDEQ       R0, R0, R2 
    /*000000e4*/ ANDEQ       R0, R0, R1 
    /*000000e8*/ WORD_00e8: .word 0x000000bc
FUNC_END _ZN4hirt16ConnectorSegTaskC2EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE


FUNC_BEGIN _ZN4hirt16ConnectorSegTaskC1EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4072]             @ 0xfe8 
    /*00000010*/ VMOV.I32    Q8, #0                      @ 0x00000000 
    /*00000014*/ LDR         IP, WORD_00e8               @ LDR         IP, [PC, #204]              @ 0x00000000000000e8 
    /*00000018*/ MOV         R4, R0 
    /*0000001c*/ LDR         R7, [SP, #24] 
    /*00000020*/ MOV         R5, R1 
    /*00000024*/ ADD         IP, PC, IP 
    /*00000028*/ ADD         R8, R0, #12 
    /*0000002c*/ LDR         R1, [SP, #28] 
    /*00000030*/ ADD         R6, R0, #64                 @ 0x40 
    /*00000034*/ ADD         LR, IP, #8 
    /*00000038*/ MOV         IP, #0 
    /*0000003c*/ VST1.8      {D16-D17}, [R8] 
    /*00000040*/ VLDR        D18, [PC, #152]             @ 0x00000000000000e0 
    /*00000044*/ STR         IP, [R0, #36]               @ 0x24 
    /*00000048*/ STR         IP, [R0, #40]               @ 0x28 
    /*0000004c*/ STR         IP, [R0, #44]               @ 0x2c 
    /*00000050*/ STR         IP, [R0, #48]               @ 0x30 
    /*00000054*/ STR         IP, [R0, #52]               @ 0x34 
    /*00000058*/ STR         IP, [R0, #56]               @ 0x38 
    /*0000005c*/ VSTR        D16, [R0, #28] 
    /*00000060*/ VST1.8      {D16-D17}, [R6] 
    /*00000064*/ STR         IP, [R0, #60]               @ 0x3c 
    /*00000068*/ STR         IP, [R0, #92]               @ 0x5c 
    /*0000006c*/ STR         IP, [R0, #88]               @ 0x58 
    /*00000070*/ VSTR        D16, [R0, #80]              @ 0x50 
    /*00000074*/ STR         LR, [R0], #120              @ 0x78 
    /*00000078*/ STRB        IP, [R4, #128]              @ 0x80 
    /*0000007c*/ STR         IP, [R4, #124]              @ 0x7c 
    /*00000080*/ LDM         R5, {IP, LR} 
    /*00000084*/ ADD         R5, R4, #128                @ 0x80 
    /*00000088*/ STR         IP, [R4, #96]               @ 0x60 
    /*0000008c*/ ADD         IP, R4, #4 
    /*00000090*/ STR         LR, [R4, #100]              @ 0x64 
    /*00000094*/ LDR         LR, [R2] 
    /*00000098*/ LDR         R2, [R2, #4] 
    /*0000009c*/ STR         LR, [R4, #104]              @ 0x68 
    /*000000a0*/ STR         R2, [R4, #108]              @ 0x6c 
    /*000000a4*/ STR         R3, [R4, #112]              @ 0x70 
    /*000000a8*/ STR         R7, [R4, #116]              @ 0x74 
    /*000000ac*/ STR         R5, [R4, #120]              @ 0x78 
    /*000000b0*/ VST1.32     {D18}, [IP] 
    /*000000b4*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
    /*000000b8*/ MOV         R0, R4 
    /*000000bc*/ POP         {R4, R5, R6, R7, R8, PC} 
    /*000000c0*/ LDR         R0, [R4, #120]              @ 0x78 
    /*000000c4*/ CMP         R5, R0 
    /*000000c8*/ BEQ         _ZN4hirt16ConnectorSegTaskC1EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xd0
    /*000000cc*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTaskC1EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_xd0:
    /*000000d0*/ MOV         R0, R4 
    /*000000d4*/ BL          _ZN4hirt7SegTaskD2Ev
    /*000000d8*/ BL          __cxa_end_cleanup
    /*000000dc*/ NOP         {0} 
    /*000000e0*/ ANDEQ       R0, R0, R2 
    /*000000e4*/ ANDEQ       R0, R0, R1 
    /*000000e8*/ WORD_00e8: .word 0x000000bc
FUNC_END _ZN4hirt16ConnectorSegTaskC1EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt16ConnectorSegTaskC2EP26hiRUNTIME_SRC_BLOB_ARRAY_SS2_PFiS2_S2_yPvES3_NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
@ Size: 0x17
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7_
@ Size: 0x144
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7_
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4048]             @ 0xfd0 
    /*00000010*/ LDR         R4, [R1, #8] 
    /*00000014*/ SUB         SP, SP, #12 
    /*00000018*/ MOV         R9, R0 
    /*0000001c*/ MOV         SL, R2 
    /*00000020*/ STR         R1, [SP, #4] 
    /*00000024*/ CMP         R4, #0 
    /*00000028*/ MOVEQ       R3, R1 
    /*0000002c*/ ADDEQ       R4, R3, #4 
    /*00000030*/ BEQ         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__xd4
    /*00000034*/ LDR         R7, [R2, #4] 
    /*00000038*/ LDR         FP, [R2] 
    /*0000003c*/ B           _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x6c
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x40:
    /*00000040*/ BL          memcmp
    /*00000044*/ CMP         R0, #0 
    /*00000048*/ BEQ         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x90
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x4c:
    /*0000004c*/ CMP         R0, #0 
    /*00000050*/ MOV         R1, #0 
    /*00000054*/ MOVLT       R1, #1 
    /*00000058*/ LDRLT       R2, [R4, #8] 
    /*0000005c*/ LDRGE       R2, [R4, #12] 
    /*00000060*/ CMP         R2, #0 
    /*00000064*/ BEQ         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x98
    /*00000068*/ MOV         R4, R2 
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x6c:
    /*0000006c*/ LDR         R5, [R4, #20] 
    /*00000070*/ MOV         R0, FP 
    /*00000074*/ LDR         R8, [R4, #16] 
    /*00000078*/ CMP         R5, R7 
    /*0000007c*/ MOVCC       R6, R5 
    /*00000080*/ MOVCS       R6, R7 
    /*00000084*/ SUBS        R2, R6, #0 
    /*00000088*/ MOV         R1, R8 
    /*0000008c*/ BNE         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x40
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x90:
    /*00000090*/ SUB         R0, R7, R5 
    /*00000094*/ B           _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x4c
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x98:
    /*00000098*/ CMP         R1, #0 
    /*0000009c*/ MOVEQ       R2, R6 
    /*000000a0*/ MOVEQ       R6, R4 
    /*000000a4*/ BNE         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__xd4
    /*000000a8*/ CMP         R2, #0 
    /*000000ac*/ BNE         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x114
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__xb0:
    /*000000b0*/ SUB         R0, R5, R7 
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__xb4:
    /*000000b4*/ CMP         R0, #0 
    /*000000b8*/ STRGE       R6, [R9] 
    /*000000bc*/ MOVGE       R3, #0 
    /*000000c0*/ STRGE       R3, [R9, #4] 
    /*000000c4*/ BLT         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x12c
    /*000000c8*/ MOV         R0, R9 
    /*000000cc*/ ADD         SP, SP, #12 
    /*000000d0*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__xd4:
    /*000000d4*/ LDR         R3, [SP, #4] 
    /*000000d8*/ LDR         R3, [R3, #12] 
    /*000000dc*/ CMP         R3, R4 
    /*000000e0*/ BEQ         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x12c
    /*000000e4*/ MOV         R0, R4 
    /*000000e8*/ BL          _ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base
    /*000000ec*/ LDR         R5, [R0, #20] 
    /*000000f0*/ MOV         R6, R0 
    /*000000f4*/ LDR         R7, [SL, #4] 
    /*000000f8*/ LDR         FP, [SL] 
    /*000000fc*/ CMP         R5, R7 
    /*00000100*/ LDR         R8, [R0, #16] 
    /*00000104*/ MOVCC       R2, R5 
    /*00000108*/ MOVCS       R2, R7 
    /*0000010c*/ CMP         R2, #0 
    /*00000110*/ BEQ         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__xb0
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x114:
    /*00000114*/ MOV         R1, FP 
    /*00000118*/ MOV         R0, R8 
    /*0000011c*/ BL          memcmp
    /*00000120*/ CMP         R0, #0 
    /*00000124*/ BNE         _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__xb4
    /*00000128*/ B           _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__xb0
    _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7__x12c:
    /*0000012c*/ STR         R4, [R9, #4] 
    /*00000130*/ MOV         R3, #0 
    /*00000134*/ STR         R3, [R9] 
    /*00000138*/ MOV         R0, R9 
    /*0000013c*/ ADD         SP, SP, #12 
    /*00000140*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
FUNC_END _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7_


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text._ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv
@ Size: 0x82c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, R7, R8, R9, SL, FP, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #3984]             @ 0xf90 
    /*00000010*/ LDR         R3, WORD_0820               @ LDR         R3, [PC, #2056]             @ 0x0000000000000820 
    /*00000014*/ SUB         SP, SP, #76                 @ 0x4c 
    /*00000018*/ LDR         R1, WORD_0824               @ LDR         R1, [PC, #2052]             @ 0x0000000000000824 
    /*0000001c*/ ADD         R2, SP, #52                 @ 0x34 
    /*00000020*/ ADD         R3, PC, R3 
    /*00000024*/ MOV         R9, R0 
    /*00000028*/ STR         R2, [SP, #24] 
    /*0000002c*/ MOV         IP, R2 
    /*00000030*/ LDR         R1, [R3, R1] 
    /*00000034*/ MOV         R2, #0 
    /*00000038*/ LDR         R0, [R0, #104]              @ 0x68 
    /*0000003c*/ LDR         R3, [R1] 
    /*00000040*/ CMP         R0, R2 
    /*00000044*/ STR         R1, [SP, #28] 
    /*00000048*/ STR         IP, [SP, #44]               @ 0x2c 
    /*0000004c*/ STR         R2, [SP, #48]               @ 0x30 
    /*00000050*/ STR         R3, [SP, #68]               @ 0x44 
    /*00000054*/ STRB        R2, [SP, #52]               @ 0x34 
    /*00000058*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x28c
    /*0000005c*/ STR         R2, [SP] 
    /*00000060*/ MOV         R5, R2 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x64:
    /*00000064*/ LDR         R3, [R9, #88]               @ 0x58 
    /*00000068*/ MOV         R2, #48                     @ 0x30 
    /*0000006c*/ LDR         R4, [R9, #108]              @ 0x6c 
    /*00000070*/ LDR         R8, [R3, #28] 
    /*00000074*/ LDR         R3, [SP] 
    /*00000078*/ ADD         SL, R8, #124                @ 0x7c 
    /*0000007c*/ MLA         R4, R2, R3, R4 
    /*00000080*/ LDR         R3, [R8, #128]              @ 0x80 
    /*00000084*/ MOV         R6, SL 
    /*00000088*/ STR         R5, [R4, #24] 
    /*0000008c*/ CMP         R3, #0 
    /*00000090*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_xc4
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x94:
    /*00000094*/ LDR         R2, [R3, #16] 
    /*00000098*/ CMP         R4, R2 
    /*0000009c*/ MOVLS       R6, R3 
    /*000000a0*/ LDRHI       R3, [R3, #12] 
    /*000000a4*/ LDRLS       R3, [R3, #8] 
    /*000000a8*/ CMP         R3, #0 
    /*000000ac*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x94
    /*000000b0*/ CMP         SL, R6 
    /*000000b4*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_xc4
    /*000000b8*/ LDR         R3, [R6, #16] 
    /*000000bc*/ CMP         R4, R3 
    /*000000c0*/ BCS         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x178
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_xc4:
    /*000000c4*/ MOV         R0, #44                     @ 0x2c 
    /*000000c8*/ BL          _Znwj
    /*000000cc*/ CMP         SL, R6 
    /*000000d0*/ ADD         R3, R0, #28 
    /*000000d4*/ STR         R4, [R0, #16] 
    /*000000d8*/ MOV         R7, R0 
    /*000000dc*/ STR         R5, [R0, #24] 
    /*000000e0*/ STRB        R5, [R0, #28] 
    /*000000e4*/ STR         R3, [R0, #20] 
    /*000000e8*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6b0
    /*000000ec*/ LDR         FP, [R6, #16] 
    /*000000f0*/ CMP         R4, FP 
    /*000000f4*/ BCS         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x3f0
    /*000000f8*/ LDR         FP, [R8, #132]              @ 0x84 
    /*000000fc*/ CMP         FP, R6 
    /*00000100*/ MOVEQ       R2, R6 
    /*00000104*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x130
    /*00000108*/ MOV         R0, R6 
    /*0000010c*/ BL          _ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base
    /*00000110*/ LDR         R3, [R0, #16] 
    /*00000114*/ MOV         R2, R0 
    /*00000118*/ CMP         R4, R3 
    /*0000011c*/ BLS         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6ec
    /*00000120*/ LDR         R3, [R0, #12] 
    /*00000124*/ CMP         R3, #0 
    /*00000128*/ MOVEQ       R6, #0 
    /*0000012c*/ MOVNE       R2, R6 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x130:
    /*00000130*/ SUB         R0, SL, R2 
    /*00000134*/ CLZ         R0, R0 
    /*00000138*/ LSR         R0, R0, #5 
    /*0000013c*/ CMP         R6, #0 
    /*00000140*/ ORRNE       R0, R0, #1 
    /*00000144*/ CMP         R0, #0 
    /*00000148*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x15c
    /*0000014c*/ LDR         FP, [R2, #16] 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x150:
    /*00000150*/ CMP         R4, FP 
    /*00000154*/ MOVCS       R0, #0 
    /*00000158*/ MOVCC       R0, #1 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x15c:
    /*0000015c*/ MOV         R3, SL 
    /*00000160*/ MOV         R1, R7 
    /*00000164*/ MOV         R6, R7 
    /*00000168*/ BL          _ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_
    /*0000016c*/ LDR         R3, [R8, #140]              @ 0x8c 
    /*00000170*/ ADD         R3, R3, #1 
    /*00000174*/ STR         R3, [R8, #140]              @ 0x8c 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x178:
    /*00000178*/ ADD         R1, R6, #20 
    /*0000017c*/ ADD         R0, SP, #44                 @ 0x2c 
    /*00000180*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4_
    /*00000184*/ LDR         R3, [R9, #88]               @ 0x58 
    /*00000188*/ LDR         R8, [R3, #28] 
    /*0000018c*/ LDR         R6, [R8, #104]              @ 0x68 
    /*00000190*/ ADD         R3, R8, #100                @ 0x64 
    /*00000194*/ STR         R3, [SP, #4] 
    /*00000198*/ CMP         R6, #0 
    /*0000019c*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x668
    /*000001a0*/ LDR         FP, [SP, #48]               @ 0x30 
    /*000001a4*/ MOV         R4, R3 
    /*000001a8*/ LDR         SL, [SP, #44]               @ 0x2c 
    /*000001ac*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1dc
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1b0:
    /*000001b0*/ LDR         R0, [R6, #16] 
    /*000001b4*/ MOV         R1, SL 
    /*000001b8*/ BL          memcmp
    /*000001bc*/ CMP         R0, #0 
    /*000001c0*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1f4
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1c4:
    /*000001c4*/ CMP         R0, #0 
    /*000001c8*/ MOVGE       R4, R6 
    /*000001cc*/ LDRLT       R6, [R6, #12] 
    /*000001d0*/ LDRGE       R6, [R6, #8] 
    /*000001d4*/ CMP         R6, #0 
    /*000001d8*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1fc
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1dc:
    /*000001dc*/ LDR         R7, [R6, #20] 
    /*000001e0*/ CMP         R7, FP 
    /*000001e4*/ MOVCC       R2, R7 
    /*000001e8*/ MOVCS       R2, FP 
    /*000001ec*/ CMP         R2, #0 
    /*000001f0*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1b0
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1f4:
    /*000001f4*/ SUB         R0, R7, FP 
    /*000001f8*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1c4
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x1fc:
    /*000001fc*/ LDR         R3, [SP, #4] 
    /*00000200*/ CMP         R3, R4 
    /*00000204*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x2b8
    /*00000208*/ LDR         R6, [R4, #20] 
    /*0000020c*/ CMP         FP, R6 
    /*00000210*/ MOVCC       R2, FP 
    /*00000214*/ MOVCS       R2, R6 
    /*00000218*/ CMP         R2, #0 
    /*0000021c*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x2a8
    /*00000220*/ LDR         R1, [R4, #16] 
    /*00000224*/ MOV         R0, SL 
    /*00000228*/ BL          memcmp
    /*0000022c*/ CMP         R0, #0 
    /*00000230*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x2a8
    /*00000234*/ CMP         R0, #0 
    /*00000238*/ ADDGE       R6, R4, #40                 @ 0x28 
    /*0000023c*/ BLT         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x2b8
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x240:
    /*00000240*/ LDR         R3, [R4, #40]               @ 0x28 
    /*00000244*/ CMP         R3, R6 
    /*00000248*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x260
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x24c:
    /*0000024c*/ LDR         R2, [R3, #8] 
    /*00000250*/ LDR         R3, [R3] 
    /*00000254*/ STR         R5, [R2, #24] 
    /*00000258*/ CMP         R3, R6 
    /*0000025c*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x24c
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x260:
    /*00000260*/ LDR         R2, [SP] 
    /*00000264*/ LDR         R3, [R9, #104]              @ 0x68 
    /*00000268*/ ADD         R2, R2, #1 
    /*0000026c*/ CMP         R3, R2 
    /*00000270*/ STR         R2, [SP] 
    /*00000274*/ BHI         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x64
    /*00000278*/ LDR         R0, [SP, #44]               @ 0x2c 
    /*0000027c*/ LDR         R3, [SP, #24] 
    /*00000280*/ CMP         R0, R3 
    /*00000284*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x28c
    /*00000288*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x28c:
    /*0000028c*/ LDR         R3, [SP, #28] 
    /*00000290*/ LDR         R2, [SP, #68]               @ 0x44 
    /*00000294*/ LDR         R3, [R3] 
    /*00000298*/ CMP         R2, R3 
    /*0000029c*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7f0
    /*000002a0*/ ADD         SP, SP, #76                 @ 0x4c 
    /*000002a4*/ POP         {R4, R5, R6, R7, R8, R9, SL, FP, PC} 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x2a8:
    /*000002a8*/ SUB         R0, FP, R6 
    /*000002ac*/ CMP         R0, #0 
    /*000002b0*/ ADDGE       R6, R4, #40                 @ 0x28 
    /*000002b4*/ BGE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x240
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x2b8:
    /*000002b8*/ MOV         R0, #52                     @ 0x34 
    /*000002bc*/ BL          _Znwj
    /*000002c0*/ LDR         R6, [SP, #44]               @ 0x2c 
    /*000002c4*/ ADD         R3, R0, #24 
    /*000002c8*/ LDR         SL, [SP, #48]               @ 0x30 
    /*000002cc*/ MOV         R2, R3 
    /*000002d0*/ STR         R3, [SP, #8] 
    /*000002d4*/ ADD         R3, R0, #16 
    /*000002d8*/ STR         R3, [SP, #12] 
    /*000002dc*/ MOV         R7, R0 
    /*000002e0*/ RSB         R3, SL, #0 
    /*000002e4*/ STR         R2, [R0, #16] 
    /*000002e8*/ CLZ         R2, R6 
    /*000002ec*/ CMP         R6, R3 
    /*000002f0*/ LSR         R2, R2, #5 
    /*000002f4*/ MOVEQ       R2, #0 
    /*000002f8*/ CMP         R2, #0 
    /*000002fc*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x30c
    /*00000300*/ LDR         R0, WORD_0828               @ LDR         R0, [PC, #1312]             @ 0x0000000000000828 
    /*00000304*/ ADD         R0, PC, R0 
    /*00000308*/ BL          _ZSt19__throw_logic_errorPKc
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x30c:
    /*0000030c*/ STR         SL, [SP, #32] 
    /*00000310*/ CMP         SL, #15 
    /*00000314*/ BHI         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x670
    /*00000318*/ CMP         SL, #1 
    /*0000031c*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6a0
    /*00000320*/ CMP         SL, #0 
    /*00000324*/ LDREQ       R3, [SP, #8] 
    /*00000328*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7c8
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x32c:
    /*0000032c*/ LDR         R2, [SP, #4] 
    /*00000330*/ ADD         R6, R7, #40                 @ 0x28 
    /*00000334*/ STR         SL, [R7, #20] 
    /*00000338*/ CMP         R2, R4 
    /*0000033c*/ STRB        R5, [R3, SL] 
    /*00000340*/ ADD         R3, R8, #96                 @ 0x60 
    /*00000344*/ STR         R3, [SP, #12] 
    /*00000348*/ STR         R5, [R7, #48]               @ 0x30 
    /*0000034c*/ STR         R6, [R7, #40]               @ 0x28 
    /*00000350*/ STR         R6, [R7, #44]               @ 0x2c 
    /*00000354*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x5f4
    /*00000358*/ LDR         R3, [R7, #16] 
    /*0000035c*/ LDR         FP, [R7, #20] 
    /*00000360*/ LDR         SL, [R4, #20] 
    /*00000364*/ MOV         R0, R3 
    /*00000368*/ STR         R3, [SP, #12] 
    /*0000036c*/ LDR         R3, [R4, #16] 
    /*00000370*/ CMP         FP, SL 
    /*00000374*/ STR         R3, [SP, #16] 
    /*00000378*/ MOV         R1, R3 
    /*0000037c*/ MOVCC       R3, FP 
    /*00000380*/ MOVCS       R3, SL 
    /*00000384*/ CMP         R3, #0 
    /*00000388*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x490
    /*0000038c*/ STR         R3, [SP, #20] 
    /*00000390*/ MOV         R2, R3 
    /*00000394*/ BL          memcmp
    /*00000398*/ LDR         R3, [SP, #20] 
    /*0000039c*/ CMP         R0, #0 
    /*000003a0*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x80c
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x3a4:
    /*000003a4*/ BLT         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x514
    /*000003a8*/ LDR         R0, [SP, #16] 
    /*000003ac*/ MOV         R2, R3 
    /*000003b0*/ LDR         R1, [SP, #12] 
    /*000003b4*/ BL          memcmp
    /*000003b8*/ CMP         R0, #0 
    /*000003bc*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x49c
    /*000003c0*/ CMP         R0, #0 
    /*000003c4*/ BLT         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x4a8
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x3c8:
    /*000003c8*/ LDR         R2, [SP, #8] 
    /*000003cc*/ LDR         R3, [SP, #12] 
    /*000003d0*/ CMP         R2, R3 
    /*000003d4*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x3e0
    /*000003d8*/ MOV         R0, R3 
    /*000003dc*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x3e0:
    /*000003e0*/ MOV         R0, R7 
    /*000003e4*/ ADD         R6, R4, #40                 @ 0x28 
    /*000003e8*/ BL          _ZdlPv
    /*000003ec*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x240
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x3f0:
    /*000003f0*/ BLS         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x484
    /*000003f4*/ LDR         R3, [R8, #136]              @ 0x88 
    /*000003f8*/ CMP         R3, R6 
    /*000003fc*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x428
    /*00000400*/ MOV         R0, R6 
    /*00000404*/ BL          _ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base
    /*00000408*/ LDR         R3, [R0, #16] 
    /*0000040c*/ MOV         R2, R0 
    /*00000410*/ CMP         R4, R3 
    /*00000414*/ BCS         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x760
    /*00000418*/ LDR         R3, [R6, #12] 
    /*0000041c*/ CMP         R3, #0 
    /*00000420*/ MOVNE       R6, R0 
    /*00000424*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x130
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x428:
    /*00000428*/ MOV         R2, R6 
    /*0000042c*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x150
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x430:
    /*00000430*/ LDR         R2, [R8, #128]              @ 0x80 
    /*00000434*/ CMP         R2, #0 
    /*00000438*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x444
    /*0000043c*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7ac
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x440:
    /*00000440*/ MOV         R2, R3 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x444:
    /*00000444*/ LDR         R1, [R2, #16] 
    /*00000448*/ CMP         R4, R1 
    /*0000044c*/ MOVCC       R0, #1 
    /*00000450*/ MOVCS       R0, #0 
    /*00000454*/ LDRCC       R3, [R2, #8] 
    /*00000458*/ LDRCS       R3, [R2, #12] 
    /*0000045c*/ CMP         R3, #0 
    /*00000460*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x440
    /*00000464*/ CMP         R0, #0 
    /*00000468*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7b0
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x46c:
    /*0000046c*/ MOV         R6, R2 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x470:
    /*00000470*/ CMP         R4, R1 
    /*00000474*/ BLS         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x484
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x478:
    /*00000478*/ CMP         R2, #0 
    /*0000047c*/ MOVEQ       R6, R2 
    /*00000480*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6cc
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x484:
    /*00000484*/ MOV         R0, R7 
    /*00000488*/ BL          _ZdlPv
    /*0000048c*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x178
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x490:
    /*00000490*/ SUB         R3, FP, SL 
    /*00000494*/ CMP         R3, #0 
    /*00000498*/ BLT         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x514
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x49c:
    /*0000049c*/ SUB         R0, SL, FP 
    /*000004a0*/ CMP         R0, #0 
    /*000004a4*/ BGE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x3c8
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x4a8:
    /*000004a8*/ LDR         R3, [R8, #112]              @ 0x70 
    /*000004ac*/ CMP         R3, R4 
    /*000004b0*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x50c
    /*000004b4*/ MOV         R0, R4 
    /*000004b8*/ BL          _ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base
    /*000004bc*/ LDR         R3, [R0, #20] 
    /*000004c0*/ MOV         SL, R0 
    /*000004c4*/ CMP         FP, R3 
    /*000004c8*/ MOVCC       R2, FP 
    /*000004cc*/ MOVCS       R2, R3 
    /*000004d0*/ CMP         R2, #0 
    /*000004d4*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6e4
    /*000004d8*/ LDR         R1, [R0, #16] 
    /*000004dc*/ LDR         R0, [SP, #12] 
    /*000004e0*/ STR         R3, [SP, #16] 
    /*000004e4*/ BL          memcmp
    /*000004e8*/ LDR         R3, [SP, #16] 
    /*000004ec*/ CMP         R0, #0 
    /*000004f0*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6e4
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x4f4:
    /*000004f4*/ CMP         R0, #0 
    /*000004f8*/ BGE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x63c
    /*000004fc*/ LDR         R3, [R4, #12] 
    /*00000500*/ CMP         R3, #0 
    /*00000504*/ MOVNE       R4, SL 
    /*00000508*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x578
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x50c:
    /*0000050c*/ MOV         SL, R4 
    /*00000510*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x5a0
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x514:
    /*00000514*/ LDR         R3, [R8, #108]              @ 0x6c 
    /*00000518*/ CMP         R3, R4 
    /*0000051c*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7c0
    /*00000520*/ MOV         R0, R4 
    /*00000524*/ BL          _ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base
    /*00000528*/ LDR         R3, [R0, #20] 
    /*0000052c*/ MOV         SL, R0 
    /*00000530*/ CMP         FP, R3 
    /*00000534*/ MOVCC       R2, FP 
    /*00000538*/ MOVCS       R2, R3 
    /*0000053c*/ CMP         R2, #0 
    /*00000540*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6d4
    /*00000544*/ LDR         R0, [R0, #16] 
    /*00000548*/ LDR         R1, [SP, #12] 
    /*0000054c*/ STR         R3, [SP, #16] 
    /*00000550*/ BL          memcmp
    /*00000554*/ LDR         R3, [SP, #16] 
    /*00000558*/ CMP         R0, #0 
    /*0000055c*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6d4
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x560:
    /*00000560*/ CMP         R0, #0 
    /*00000564*/ BGE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x63c
    /*00000568*/ LDR         R3, [SL, #12] 
    /*0000056c*/ CMP         R3, #0 
    /*00000570*/ MOVEQ       R4, #0 
    /*00000574*/ MOVNE       SL, R4 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x578:
    /*00000578*/ ADDS        R0, R4, #0 
    /*0000057c*/ LDR         R3, [SP, #4] 
    /*00000580*/ MOVNE       R0, #1 
    /*00000584*/ CMP         R3, SL 
    /*00000588*/ ORREQ       R0, R0, #1 
    /*0000058c*/ CMP         R0, #0 
    /*00000590*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x5d4
    /*00000594*/ LDR         R3, [R7, #16] 
    /*00000598*/ LDR         FP, [R7, #20] 
    /*0000059c*/ STR         R3, [SP, #12] 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x5a0:
    /*000005a0*/ LDR         R4, [SL, #20] 
    /*000005a4*/ CMP         R4, FP 
    /*000005a8*/ MOVCC       R2, R4 
    /*000005ac*/ MOVCS       R2, FP 
    /*000005b0*/ CMP         R2, #0 
    /*000005b4*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6dc
    /*000005b8*/ LDR         R1, [SL, #16] 
    /*000005bc*/ LDR         R0, [SP, #12] 
    /*000005c0*/ BL          memcmp
    /*000005c4*/ CMP         R0, #0 
    /*000005c8*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6dc
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x5cc:
    /*000005cc*/ LSR         R0, R0, #31 
    /*000005d0*/ LDR         R3, [SP, #4] 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x5d4:
    /*000005d4*/ MOV         R2, SL 
    /*000005d8*/ MOV         R1, R7 
    /*000005dc*/ MOV         R4, R7 
    /*000005e0*/ BL          _ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS_
    /*000005e4*/ LDR         R3, [R8, #116]              @ 0x74 
    /*000005e8*/ ADD         R3, R3, #1 
    /*000005ec*/ STR         R3, [R8, #116]              @ 0x74 
    /*000005f0*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x240
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x5f4:
    /*000005f4*/ LDR         R3, [R8, #116]              @ 0x74 
    /*000005f8*/ CMP         R3, #0 
    /*000005fc*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x63c
    /*00000600*/ LDR         SL, [R8, #112]              @ 0x70 
    /*00000604*/ LDR         FP, [R7, #20] 
    /*00000608*/ LDR         R4, [SL, #20] 
    /*0000060c*/ CMP         R4, FP 
    /*00000610*/ MOVCC       R2, R4 
    /*00000614*/ MOVCS       R2, FP 
    /*00000618*/ CMP         R2, #0 
    /*0000061c*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x74c
    /*00000620*/ LDR         R1, [R7, #16] 
    /*00000624*/ LDR         R0, [SL, #16] 
    /*00000628*/ BL          memcmp
    /*0000062c*/ CMP         R0, #0 
    /*00000630*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x74c
    /*00000634*/ CMP         R0, #0 
    /*00000638*/ BLT         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x758
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x63c:
    /*0000063c*/ ADD         R2, R7, #16 
    /*00000640*/ ADD         R1, R8, #96                 @ 0x60 
    /*00000644*/ ADD         R0, SP, #36                 @ 0x24 
    /*00000648*/ BL          _ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_NS0_4listIP16hiRUNTIME_BLOB_SSaISA_EEEESt10_Select1stISD_ESt4lessIS5_ESaISD_EE24_M_get_insert_unique_posERS7_
    /*0000064c*/ LDR         SL, [SP, #40]               @ 0x28 
    /*00000650*/ LDR         R4, [SP, #36]               @ 0x24 
    /*00000654*/ CMP         SL, #0 
    /*00000658*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x578
    /*0000065c*/ LDR         R3, [R7, #16] 
    /*00000660*/ STR         R3, [SP, #12] 
    /*00000664*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x3c8
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x668:
    /*00000668*/ MOV         R4, R3 
    /*0000066c*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x2b8
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x670:
    /*00000670*/ ADD         R1, SP, #32 
    /*00000674*/ ADD         R0, R7, #16 
    /*00000678*/ BL          _ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_createERjj
    /*0000067c*/ LDR         R3, [SP, #32] 
    /*00000680*/ STR         R0, [R7, #16] 
    /*00000684*/ STR         R3, [R7, #24] 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x688:
    /*00000688*/ MOV         R2, SL 
    /*0000068c*/ MOV         R1, R6 
    /*00000690*/ BL          memcpy
    /*00000694*/ LDR         SL, [SP, #32] 
    /*00000698*/ LDR         R3, [R7, #16] 
    /*0000069c*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x32c
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6a0:
    /*000006a0*/ LDRB        R2, [R6] 
    /*000006a4*/ LDR         R3, [SP, #8] 
    /*000006a8*/ STRB        R2, [R7, #24] 
    /*000006ac*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x32c
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6b0:
    /*000006b0*/ LDR         R3, [R8, #140]              @ 0x8c 
    /*000006b4*/ CMP         R3, #0 
    /*000006b8*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x430
    /*000006bc*/ LDR         R2, [R8, #136]              @ 0x88 
    /*000006c0*/ LDR         R3, [R2, #16] 
    /*000006c4*/ CMP         R4, R3 
    /*000006c8*/ BLS         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x430
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6cc:
    /*000006cc*/ MOV         R6, #0 
    /*000006d0*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x130
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6d4:
    /*000006d4*/ SUB         R0, R3, FP 
    /*000006d8*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x560
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6dc:
    /*000006dc*/ SUB         R0, FP, R4 
    /*000006e0*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x5cc
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6e4:
    /*000006e4*/ SUB         R0, FP, R3 
    /*000006e8*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x4f4
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6ec:
    /*000006ec*/ LDR         R2, [R8, #128]              @ 0x80 
    /*000006f0*/ CMP         R2, #0 
    /*000006f4*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x700
    /*000006f8*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7d0
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6fc:
    /*000006fc*/ MOV         R2, R3 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x700:
    /*00000700*/ LDR         R1, [R2, #16] 
    /*00000704*/ CMP         R4, R1 
    /*00000708*/ MOVCC       R0, #1 
    /*0000070c*/ MOVCS       R0, #0 
    /*00000710*/ LDRCC       R3, [R2, #8] 
    /*00000714*/ LDRCS       R3, [R2, #12] 
    /*00000718*/ CMP         R3, #0 
    /*0000071c*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6fc
    /*00000720*/ CMP         R0, #0 
    /*00000724*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x46c
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x728:
    /*00000728*/ CMP         FP, R2 
    /*0000072c*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x478
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x730:
    /*00000730*/ STR         R2, [SP, #4] 
    /*00000734*/ MOV         R0, R2 
    /*00000738*/ BL          _ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base
    /*0000073c*/ LDR         R1, [R0, #16] 
    /*00000740*/ MOV         R6, R0 
    /*00000744*/ LDR         R2, [SP, #4] 
    /*00000748*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x470
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x74c:
    /*0000074c*/ SUB         R0, R4, FP 
    /*00000750*/ CMP         R0, #0 
    /*00000754*/ BGE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x63c
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x758:
    /*00000758*/ MOV         R4, #0 
    /*0000075c*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x578
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x760:
    /*00000760*/ LDR         R2, [R8, #128]              @ 0x80 
    /*00000764*/ CMP         R2, #0 
    /*00000768*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x774
    /*0000076c*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7d8
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x770:
    /*00000770*/ MOV         R2, R3 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x774:
    /*00000774*/ LDR         R1, [R2, #16] 
    /*00000778*/ CMP         R4, R1 
    /*0000077c*/ MOVCC       R0, #1 
    /*00000780*/ MOVCS       R0, #0 
    /*00000784*/ LDRCC       R3, [R2, #8] 
    /*00000788*/ LDRCS       R3, [R2, #12] 
    /*0000078c*/ CMP         R3, #0 
    /*00000790*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x770
    /*00000794*/ CMP         R0, #0 
    /*00000798*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x46c
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x79c:
    /*0000079c*/ LDR         R3, [R8, #132]              @ 0x84 
    /*000007a0*/ CMP         R3, R2 
    /*000007a4*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x730
    /*000007a8*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x478
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7ac:
    /*000007ac*/ MOV         R2, SL 
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7b0:
    /*000007b0*/ LDR         R3, [R8, #132]              @ 0x84 
    /*000007b4*/ CMP         R3, R2 
    /*000007b8*/ BNE         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x730
    /*000007bc*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x6cc
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7c0:
    /*000007c0*/ MOV         SL, R4 
    /*000007c4*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x578
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7c8:
    /*000007c8*/ LDR         R0, [SP, #8] 
    /*000007cc*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x688
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7d0:
    /*000007d0*/ MOV         R2, SL 
    /*000007d4*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x728
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7d8:
    /*000007d8*/ MOV         R2, SL 
    /*000007dc*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x79c
    /*000007e0*/ BL          __cxa_begin_catch
    /*000007e4*/ MOV         R0, R7 
    /*000007e8*/ BL          _ZdlPv
    /*000007ec*/ BL          __cxa_rethrow
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7f0:
    /*000007f0*/ BL          __stack_chk_fail
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7f4:
    /*000007f4*/ LDR         R0, [SP, #44]               @ 0x2c 
    /*000007f8*/ LDR         R3, [SP, #24] 
    /*000007fc*/ CMP         R0, R3 
    /*00000800*/ BEQ         _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x808
    /*00000804*/ BL          _ZdlPv
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x808:
    /*00000808*/ BL          __cxa_end_cleanup
    _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x80c:
    /*0000080c*/ SUB         R2, FP, SL 
    /*00000810*/ CMP         R2, #0 
    /*00000814*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x3a4
    /*00000818*/ BL          __cxa_end_catch
    /*0000081c*/ B           _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv_x7f4
    /*00000820*/ WORD_0820: .word 0x000007f8
    /*00000824*/ WORD_0824: .word 0x00000000
    /*00000828*/ WORD_0828: .word 0x0000051c
FUNC_END _ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv


@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .ARM.extab.text._ZN4hirt16ConnectorSegTask16resetDstBlobsNumEv
@ Size: 0x2c
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
@ .text.startup._GLOBAL__sub_I_SegTask.cpp
@ Size: 0x54
@ - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

FUNC_BEGIN _GLOBAL__sub_I_SegTask.cpp
    /*00000000*/ MOV         IP, #16384                  @ 0x4000 
    /*00000004*/ PUSH        {R4, R5, R6, LR} 
    /*00000008*/ SUB         IP, SP, IP 
    /*0000000c*/ STR         R0, [IP, #4080]             @ 0xff0 
    /*00000010*/ LDR         R4, WORD_0044               @ LDR         R4, [PC, #44]               @ 0x0000000000000044 
    /*00000014*/ LDR         R5, WORD_0048               @ LDR         R5, [PC, #44]               @ 0x0000000000000048 
    /*00000018*/ ADD         R4, PC, R4 
    /*0000001c*/ ADD         R5, PC, R5 
    /*00000020*/ MOV         R0, R4 
    /*00000024*/ BL          _ZNSt8ios_base4InitC1Ev
    /*00000028*/ LDR         R3, WORD_004c               @ LDR         R3, [PC, #28]               @ 0x000000000000004c 
    /*0000002c*/ MOV         R0, R4 
    /*00000030*/ LDR         R2, WORD_0050               @ LDR         R2, [PC, #24]               @ 0x0000000000000050 
    /*00000034*/ LDR         R1, [R5, R3] 
    /*00000038*/ ADD         R2, PC, R2 
    /*0000003c*/ POP         {R4, R5, R6, LR} 
    _GLOBAL__sub_I_SegTask.cpp_x40:
    /*00000040*/ B           _GLOBAL__sub_I_SegTask.cpp_x40@ __aeabi_atexit [R_ARM_JUMP24: +0x0] 
    /*00000044*/ WORD_0044: .word 0x00000024
    /*00000048*/ WORD_0048: .word 0x00000024
    /*0000004c*/ WORD_004c: .word 0x00000000
    /*00000050*/ WORD_0050: .word 0x00000010
FUNC_END _GLOBAL__sub_I_SegTask.cpp


